decentraland/builder

.env.example
.gitignore
README.md
package-lock.json
package.json
src/index.tsx
src/reducer.ts
src/sagas.ts
src/store.ts
src/translations/en.json
src/translations/index.ts
src/types.ts
tsconfig.json
tslint.json

feat: add decentraland-dapps

---

src/components/HomePage/HomePage.css
src/components/HomePage/HomePage.tsx
src/index.css
src/index.tsx
src/themes/index.js
src/themes/theme.css

feat: add decentraland UI styles

---

src/components/DecorationDetails/DecorationDetails.tsx
src/components/DecorationDetails/index.ts
src/components/DecorationPalette/DecorationPalette.tsx
src/components/DecorationPalette/index.ts
src/components/Drawer/Drawer.tsx
src/components/EditorPage/EditorPage.css
src/components/EditorPage/EditorPage.tsx
src/components/HomePage/HomePage.tsx
src/components/Preview/Preview.css
src/components/SideBar/SideBar.css
src/components/SideBar/SideBar.tsx
src/components/SideBar/index.ts
src/components/TopBar/TopBar.css
src/components/TopBar/TopBar.tsx
src/components/TopBar/index.ts
src/components/ViewPort/ViewPort.tsx
src/components/ViewPort/ViewPort.types.ts
src/components/ViewPort/index.ts
src/modules/translation/languages/en.json
src/routing/Routes.tsx
src/themes/theme.css
tslint.json

feat: basic layout

---

src/components/AssetCard/AssetCard.tsx
src/components/AssetCard/AssetCard.types.ts
src/components/AssetCard/HorizontalCard/HorizontalCard.css
src/components/AssetCard/HorizontalCard/HorizontalCard.tsx
src/components/AssetCard/HorizontalCard/HorizontalCard.types.ts
src/components/AssetCard/HorizontalCard/index.ts
src/components/AssetCard/VerticalCard/VerticalCard.css
src/components/AssetCard/VerticalCard/VerticalCard.tsx
src/components/AssetCard/VerticalCard/VerticalCard.types.ts
src/components/AssetCard/VerticalCard/index.ts
src/components/AssetCard/index.ts
src/components/Drawer/Drawer.css
src/components/Drawer/Drawer.tsx
src/components/Drawer/Drawer.types.ts
src/components/Drawer/index.ts
src/components/SideBar/ItemDrawer/ItemDrawer.css
src/components/SideBar/ItemDrawer/ItemDrawer.tsx
src/components/SideBar/ItemDrawer/ItemDrawer.types.ts
src/components/SideBar/ItemDrawer/index.ts
src/components/SideBar/SideBar.tsx
src/modules/assetpack/types.ts
src/modules/translation/languages/en.json
src/themes/theme.css

Closes #28 
The component is used like this:
```tsx
<ItemDrawer
items={[
{
assetId: '1',
title: 'Test',
thumbnail: 'https://market.decentraland.org/static/media/logo.b7751b3e.svg'
},
{
assetId: '1',
title: 'Item Test',
thumbnail: 'https://market.decentraland.org/static/media/logo.b7751b3e.svg'
},
{
assetId: '1',
title: 'Short',
thumbnail: 'https://market.decentraland.org/static/media/logo.b7751b3e.svg'
},
{
assetId: '1',
title: 'Something longer',
thumbnail: 'https://market.decentraland.org/static/media/logo.b7751b3e.svg'
}
]}
/>
```

feat: added asset drawer

---

public/assetPack/packv1.json
src/components/SideBar/ItemDrawer/ItemDrawer.tsx
src/components/SideBar/ItemDrawer/ItemDrawer.types.ts
src/components/SideBar/SideBar.container.tsx
src/components/SideBar/SideBar.tsx
src/components/SideBar/SideBar.types.tsx
src/modules/asset/reducer.ts
src/modules/category/reducer.ts
src/modules/category/selectors.ts
src/modules/category/types.ts

feat: list categories on item drawer

---

public/assetPack/packv1.json
src/components/AssetCard/AssetCard.tsx
src/components/AssetCard/AssetCard.types.ts
src/components/AssetCard/VerticalCard/VerticalCard.css
src/components/SideBar/ItemDrawer/ItemDrawer.tsx
src/components/SideBar/ItemDrawer/ItemDrawer.types.ts
src/components/SideBar/SideBar.container.tsx
src/components/SideBar/SideBar.tsx
src/components/SideBar/SideBar.types.tsx
src/modules/asset/selectors.ts
src/modules/asset/types.ts
src/modules/assetPack/sagas.ts
src/modules/assetPack/types.ts
src/modules/editor/sagas.ts
src/modules/project/reducer.ts
src/modules/scene/actions.ts
src/modules/scene/selectors.ts

feat: load asset packs from content server

---

src/components/AssetCard/HorizontalCard/HorizontalCard.css
src/components/SideBar/ItemDrawer/ItemDrawer.tsx

fix: item drawer list view

---

src/modules/asset/selectors.ts
src/modules/scene/sagas.ts
src/modules/scene/selectors.ts
src/modules/scene/types.ts
src/modules/scene/writers.ts

We should optimize the mappings sent to the editor, we are sending all of them when only a few are needed.
We should optimize the js code generation, creating randomly named variables is good enough but we can use an array and be sure that we will never have naming collisions. Also we should only use ES5 syntax.
Closes #44

chore: editor interoop enhancements

---

src/components/TopBar/TopBar.container.ts
src/components/TopBar/TopBar.tsx
src/components/TopBar/TopBar.types.ts
src/components/TopBar/index.ts

feat: add the current project title to topbar

---

src/components/HomePage/HomePage.css
src/components/HomePage/HomePage.tsx
src/modules/common/store.ts
src/modules/project/reducer.ts
src/modules/scene/reducer.ts
src/modules/translation/languages/en.json

feat: local store projects

---

src/components/AssetCard/HorizontalCard/HorizontalCard.css
src/components/Metrics/Metrics.css
src/components/Metrics/Metrics.tsx
src/components/Preview/Preview.css
src/modules/translation/languages/en.json

I didn't change the editor loading background, waiting for confirmation
Closes #86

fix: style and wording problems

---

package-lock.json
package.json
src/components/EditorPage/EditorPage.tsx
src/components/Preview/Preview.container.ts
src/components/Preview/Preview.css
src/components/Preview/Preview.tsx
src/components/Preview/Preview.types.ts
src/components/Preview/index.ts
src/modules/editor/actions.ts
src/modules/editor/reducer.ts
src/modules/editor/sagas.ts
src/modules/editor/selectors.ts
src/modules/scene/selectors.ts

feat: wait for editor to be ready

---

src/components/AssetCard/VerticalCard/VerticalCard.css
src/components/AssetCard/VerticalCard/VerticalCard.tsx
src/components/Preview/Preview.tsx

feat: hide names in vertical cards

---

src/modules/ui/sidebar/reducer.ts

fix: clear search when opening editor

---

src/components/EditorPage/EditorPage.css
src/components/EditorPage/EditorPage.tsx
src/components/SideBar/ItemDrawer/ItemDrawer.css

fix: scrolling on firefox

---

src/themes/components/Dimmer.css
src/themes/index.ts

fix: modal z-index

---

src/modules/scene/sagas.ts

feat: copy rotation in duplicated items

---

src/modules/editor/sagas.ts

fix: reset camera on multi-parcel projects

---

src/components/Modals/EditProjectModal/EditProjectModal.container.ts
src/components/Modals/EditProjectModal/EditProjectModal.tsx
src/components/Preview/Preview.container.ts
src/components/ProjectCard/ProjectCard.css
src/components/ProjectCard/ProjectCard.tsx
src/components/TopBar/TopBar.container.ts
src/modules/editor/actions.ts
src/modules/editor/sagas.ts
src/modules/editor/utils.ts
src/modules/project/selectors.ts
src/modules/scene/selectors.ts
tsconfig.json

feat: project thumbnails

---

src/components/AssetCard/HorizontalCard/HorizontalCard.css
src/components/AssetCard/VerticalCard/VerticalCard.css
src/components/AssetCard/VerticalCard/VerticalCard.tsx
src/components/Drawer/Drawer.css
src/components/SideBar/ItemDrawer/ItemDrawer.css

Fix horizontal scroll, added grab cursor and tooltips to items

fix: sidebar

---

src/components/ProjectCard/ProjectCard.container.ts
src/components/ProjectCard/ProjectCard.css
src/components/ProjectCard/ProjectCard.tsx
src/components/ProjectCard/ProjectCard.types.ts
src/components/ProjectCard/index.ts
src/modules/common/store.ts
src/modules/project/actions.ts
src/modules/project/reducer.ts
src/modules/project/sagas.ts
src/modules/translation/languages/en.json

feat: delete project

---

package-lock.json
package.json
src/components/Preview/Preview.types.ts
src/ecsScene/scene.ts
src/modules/editor/actions.ts
src/modules/editor/sagas.ts

fix: preview

---

package-lock.json
package.json
src/components/EditorPage/EditorPage.container.ts
src/components/EditorPage/EditorPage.types.ts
src/components/Modals/ContestModal/ContestModal.container.ts
src/components/Modals/ContestModal/ContestModal.tsx
src/components/Modals/EditProjectModal/EditProjectModal.container.ts
src/components/Modals/EditProjectModal/EditProjectModal.tsx
src/components/Modals/Modals.types.ts
src/components/Modals/ShortcutsModal/ShortcutsModal.container.ts
src/components/Modals/ShortcutsModal/ShortcutsModal.tsx
src/components/TopBar/TopBar.container.ts
src/components/TopBar/TopBar.types.ts
src/modules/editor/utils.ts
src/modules/modal/actions.ts
src/modules/modal/types.ts

Depends on: https://github.com/decentraland/decentraland-dapps/pull/33
will need a bump once it's merged. Will fail until this happens

feat: type modal names

---

src/components/EditorPage/Metrics/Metrics.tsx
src/components/HomePage/HomePage.container.ts
src/components/HomePage/HomePage.tsx
src/components/HomePage/HomePage.types.ts
src/components/LayoutPicker/LayoutPicker.css
src/components/LayoutPicker/LayoutPicker.tsx
src/components/LayoutPicker/LayoutPicker.types.ts
src/components/LayoutPicker/index.ts
src/components/Modals/CustomLayoutModal/CustomLayoutModal.container.ts
src/components/Modals/CustomLayoutModal/CustomLayoutModal.css
src/components/Modals/CustomLayoutModal/CustomLayoutModal.tsx
src/components/Modals/CustomLayoutModal/CustomLayoutModal.types.ts
src/components/Modals/CustomLayoutModal/index.ts
src/components/Modals/EditProjectModal/EditProjectModal.css
src/components/Modals/index.ts
src/lib/layout.ts
src/modules/editor/sagas.ts
src/modules/template/types.ts
src/modules/template/utils.ts
src/modules/translation/languages/en.json
src/themes/components/Modal.css

feat: custom layout

---

package-lock.json
package.json
src/modules/editor/sagas.ts
src/modules/project/utils.ts
src/modules/template/utils.ts

feat: 16x16m

---

.circleci/config.yml
public/index.html
src/components/EditorPage/Metrics/Metrics.tsx
src/modules/analytics/track.ts
src/modules/scene/constants.ts
src/modules/scene/types.ts

fix: segment

---

src/components/Modals/ShortcutsModal/ShortcutsModal.tsx
src/modules/analytics/track.ts
src/modules/scene/actions.ts
src/modules/scene/sagas.ts

fix: things

---

src/components/Modals/ShortcutsModal/ShortcutsModal.tsx

fix: don't blow up on keys

---

src/components/SideBar/ItemDrawer/ItemDrawer.css
src/components/SideBar/ItemDrawer/ItemDrawer.tsx
src/components/SideBar/ItemDrawer/ItemDrawer.types.ts

Looks like this:
[full.zip](https://github.com/decentraland/builder/files/2877349/full.zip)
Animation removed to avoid jankyness:
[janky.zip](https://github.com/decentraland/builder/files/2877352/janky.zip)
Sorry for the zips
Closes #132

feat: search scroll and clear

---

package-lock.json
package.json
public/index.html
src/components/AssetCard/VerticalCard/VerticalCard.tsx
src/components/Preview/Preview.tsx
src/components/SideBar/ItemDrawer/ItemDrawer.css
src/components/SideBar/SideBar.css
src/components/SideBar/SideBar.tsx
src/components/TemplateCard/TemplateCard.css
src/ecsScene/scene.ts
src/index.css
src/routing/Routes.tsx

☝️ Tested on slow connection 
- Added loader before before react mounts
- Updated ECS (now uses IndexedDB cache for 3d assets)
- Updated spinner on sidebar 
- Updated placeholder graphic when asset thumbnails fail to load
- Preview is reused and some initialization steps are now skipped
Also on the content server's side assets are now served with a better cache policy
Closes #126

feat: better UX on slow connections

---

src/components/EditorPage/EditorPage.css
src/components/EditorPage/Tools/Tools.css
src/components/EditorPage/Tools/Tools.tsx
src/components/Modals/ShortcutsModal/ShortcutsModal.tsx
src/components/ShortcutTooltip/ShortcutTooltip.css
src/components/ShortcutTooltip/ShortcutTooltip.tsx
src/components/ShortcutTooltip/ShortcutTooltip.types.ts
src/components/TopBar/TopBar.css
src/components/TopBar/TopBar.tsx
src/modules/keyboard/utils.tsx
src/modules/translation/languages/en.json
src/themes/components/Popup.css
src/themes/index.ts

feat: tooltip styles

---

src/modules/editor/types.ts
src/modules/editor/utils.ts

chore: add metadata to scene.json to track scene origin

---

package-lock.json
package.json
src/components/Modals/ShortcutsModal/ShortcutsModal.css
src/components/Modals/ShortcutsModal/ShortcutsModal.tsx
src/components/Preview/Preview.types.ts
src/components/ShortcutTooltip/ShortcutTooltip.tsx
src/modules/analytics/track.ts
src/modules/editor/actions.ts
src/modules/editor/reducer.ts
src/modules/editor/sagas.ts
src/modules/editor/selectors.ts
src/modules/keyboard/types.ts
src/modules/keyboard/utils.ts
src/modules/scene/sagas.ts
src/modules/scene/utils.ts
src/modules/translation/languages/en.json

feat: select entity, spawn on camera target and snap to grid

---

src/components/ProjectCard/ProjectCard.tsx
src/modules/editor/sagas.ts
src/modules/project/actions.ts
src/modules/project/reducer.ts
src/modules/project/sagas.ts
src/modules/scene/reducer.ts

fix: delete scenes

---

src/components/Preview/Preview.css
src/components/Preview/Preview.tsx
src/index.css

feat: add a class to the canvas, and hide it

---

src/components/App/App.tsx
src/index.tsx
src/routing/Routes.tsx

feat: remove sign in (for now)

---

src/themes/components/Radio.css
src/themes/index.ts

feat: override base css color for radio borders

---

src/modules/common/sagas.ts
src/modules/modal/sagas.ts

feat: close modals on URL change

---

src/components/LayoutPicker/LayoutPicker.tsx
src/modules/translation/languages/en.json

feat: widthxheight for rowsxcols

---

src/routing/Routes.tsx

Addresses the redirect from #242 
There are still things TBD

feat: don't redirect for mobile pages

---

package-lock.json
package.json
src/components/TopBar/TopBar.tsx
src/modules/editor/reducer.ts
src/modules/editor/sagas.ts
src/modules/keyboard/utils.ts
src/modules/scene/sagas.ts
src/modules/scene/utils.ts
src/modules/translation/languages/en.json

feat: free movement

---

src/modules/keyboard/sagas.ts
src/modules/keyboard/utils.ts

fix: default mousetrap to keyup

---

src/modules/analytics/sagas.ts
src/modules/analytics/track.ts
src/modules/common/sagas.ts
src/modules/editor/reducer.ts
src/modules/editor/sagas.ts

Added more events as requested by @dnul 
Closes #249

chore: added more events to segment

---

src/components/Chip/Chip.css
src/components/EditorPage/EditorPage.tsx
src/components/TopBar/TopBar.container.ts
src/components/TopBar/TopBar.tsx
src/components/TopBar/TopBar.types.ts
src/routing/Routes.tsx

feat: preview fixes

---

src/modules/project/sagas.ts
src/modules/scene/reducer.ts

feat: clean undo/redo history on layout change

---

src/modules/ui/sidebar/utils.ts

feat: category order

---

package-lock.json
package.json
src/ecsScene/scene.ts

fix: #279
fix: #278 
fix: #274

fix: editor fixes

---

src/modules/analytics/sagas.ts

chore: track update item

---

src/modules/scene/sagas.ts

fix: remove previous ground components

---

package-lock.json
package.json

chore: bump ecs

---

config/webpack.config.js
src/components/ErrorPage/ErrorPage.tsx
src/components/HomePage/HomePage.tsx
src/components/MobilePage/MobilePage.tsx
src/components/NotFoundPage/NotFoundPage.tsx
src/components/ProjectCard/ProjectCard.tsx
src/components/UnsupportedBrowserPage/UnsupportedBrowserPage.container.ts
src/components/UnsupportedBrowserPage/UnsupportedBrowserPage.css
src/components/UnsupportedBrowserPage/UnsupportedBrowserPage.tsx
src/components/UnsupportedBrowserPage/UnsupportedBrowserPage.types.ts
src/components/UnsupportedBrowserPage/index.ts
src/modules/translation/languages/en.json
src/routing/Routes.tsx

Also renames some i18n keys
Closes #205

feat: ms edge page

---

package-lock.json
package.json

Fixes camera issues #127 and #252

chore: bump ecs version

---

src/modules/contest/sagas.ts

Closes https://github.com/decentraland/builder-contest-server/issues/7

fix: remove thumbnail from project before sending

---

src/components/AssetCard/VerticalCard/VerticalCard.tsx

feat: add a tooltip to vertical cards

---

src/components/EditorPage/EditorPage.container.ts
src/components/EditorPage/EditorPage.tsx
src/components/EditorPage/EditorPage.types.ts
src/modules/editor/sagas.ts

fix: disable keybindings when the editor is loading

---

src/components/EditorPage/EditorPage.css
src/components/EditorPage/EditorPage.tsx
src/components/EditorPage/LocalStorageToast/LocalStorageToast.css
src/components/EditorPage/Metrics/Metrics.css
src/components/EditorPage/Metrics/Metrics.tsx
src/components/EditorPage/Metrics/Metrics.types.tsx
src/components/EditorPage/Tools/Tools.tsx
src/components/Popups/ClosePopup/ClosePopup.tsx
src/components/Popups/ClosePopup/ClosePopup.types.ts
src/modules/translation/languages/en.json

feat: metrics popup

---

package-lock.json
package.json
src/modules/editor/sagas.ts

Closes #311 
Closes #313 
Closes #314 
Closes tu vieja

fix: important enhancements

---

package-lock.json
package.json
src/components/ErrorPage/ErrorPage.tsx
src/components/TopBar/TopBar.tsx
src/components/ViewPort/ViewPort.tsx

- Updates decentraland-dapps
- Renders/Unmounts intercom widget when entering and exiting Preview
- Updates ErrorPage to use new intercom api
Closes #265

chore: hide intercom in preview

---

src/modules/editor/sagas.ts

feat: allow dropping items outside of the scene

---

src/components/EditorPage/Metrics/Metrics.container.ts
src/components/EditorPage/Metrics/Metrics.tsx
src/components/TopBar/TopBar.container.ts
src/components/TopBar/TopBar.css
src/components/TopBar/TopBar.tsx
src/components/TopBar/TopBar.types.ts
src/modules/scene/selectors.ts
src/modules/scene/utils.ts
src/modules/translation/languages/en.json

feat: disable contest button on exceeded metrics

---

src/components/Modals/AddToContestModal/AddToContestModal.tsx
src/modules/translation/languages/en.json

feat: add success state to add to contest

---

src/components/EditorPage/EditorPage.css
src/components/EditorPage/LocalStorageToast/LocalStorageToast.css
src/components/EditorPage/Metrics/Metrics.css
src/components/EditorPage/Metrics/Metrics.tsx
src/components/EditorPage/Tools/Tools.tsx
src/components/SquaresGrid/Square/Square.css
src/components/TopBar/TopBar.css
src/modules/translation/languages/en.json

feat: fix tooltip maddness for the bottom icons

---

src/components/EditorPage/LocalStorageToast/LocalStorageToast.css
src/components/EditorPage/Metrics/Metrics.tsx
src/components/EditorPage/Metrics/Metrics.types.tsx
src/components/EditorPage/Tools/Tools.tsx

Closes #334 
We might want to add the FAQ to a different issue

feat: remove metricts Popup

---

src/components/ContestButton/ContestButton.css
src/components/ContestButton/ContestButton.tsx
src/components/ContestButton/ContestButton.types.ts
src/components/ContestButton/index.ts
src/components/Modals/TutorialModal/TutorialModal.css
src/components/Modals/TutorialModal/TutorialModal.tsx
src/components/Modals/TutorialModal/slides.tsx
src/components/TopBar/TopBar.css
src/components/TopBar/TopBar.tsx
src/modules/translation/languages/en.json

chore: remove sign up button from tutorial

---

src/modules/translation/languages/es.json
src/modules/translation/languages/index.ts

feat: spanish, joder!

---

src/modules/analytics/sagas.ts
src/modules/editor/reducer.ts

fix: update out of bounds on delete

---

src/components/HomePage/HomePage.tsx
src/components/Modals/ContestModal/ContestModal.css
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/fr.json
src/modules/translation/languages/ja.json
src/modules/translation/languages/ko.json
src/modules/translation/languages/zh.json

chore: remove banner cta, update copies

---

src/modules/translation/languages/en.json

chore: update copies

---

src/modules/analytics/sagas.ts
src/modules/analytics/track.ts

fix: prevent sending so many enable precision events

---

src/components/App/index.ts
src/components/Preview/Preview.container.ts
src/index.tsx
src/modules/translation/sagas.ts
src/routing/Routes.tsx

Use `?locale="en|es|zh|"` 
Closes #365

feat: change locales via query string

---

src/components/TopBar/TopBar.css
src/components/TopBar/TopBar.tsx

fix: allow for long titles on smaller resolutions

---

src/modules/translation/languages/es.json

feat: adjust spanish translation

---

src/components/ContestButton/ContestButton.css
src/themes/theme.css

feat: Optimize color of `Submit to contest` button

---

src/components/EditorPage/Metrics/Metrics.tsx

fix: metrics alert on exiting preview

---

src/modules/common/migrations.ts
src/modules/common/store.ts
src/modules/editor/utils.ts
src/modules/project/reducer.ts
src/modules/scene/reducer.ts

fix: optimize localstorage

---

package-lock.json

chore: fix vulnerabilities

---

src/components/Modals/VideoModal/VideoModal.css
src/components/Modals/VideoModal/VideoModal.tsx
src/components/TemplateCard/TemplateCard.css
src/components/TemplateCard/TemplateCard.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/fr.json
src/modules/translation/languages/ja.json
src/modules/translation/languages/ko.json
src/modules/translation/languages/zh.json
src/routing/Routes.tsx

- Centers template grid icons
- Fixes video modal wording and styles
- Fixes custom layout modal wording
- Fixes Builder link highlight on navbar

fix: homepage

---

src/modules/editor/sagas.ts
src/modules/scene/actions.ts
src/modules/scene/sagas.ts

fix: vertical snap to bounds

---

package-lock.json
package.json
src/components/HomePageHero/HomePageHero.css
src/components/Modals/AddToContestModal/AddToContestModal.tsx
src/modules/contest/reducer.ts
src/modules/contest/types.ts
src/modules/translation/languages/index.ts
src/modules/translation/languages/ko.json

feat: korean

---

src/routing/Routes.container.ts
src/routing/Routes.types.ts

fix: router

---

src/components/MobilePageHero/MobilePageHero.tsx

fix: mobile video

---

src/components/EditorPage/EditorPage.css
src/components/EditorPage/EditorPage.tsx

fix: preview height

---

src/modules/project/sagas.ts
src/modules/ui/sidebar/selectors.ts
src/modules/ui/sidebar/utils.ts

chore: remove empty ground option

---

src/components/Banners/HomePageBanner/HomePageBanner.tsx
src/components/Modals/TutorialModal/TutorialModal.container.ts
src/components/Modals/TutorialModal/TutorialModal.tsx
src/components/Modals/TutorialModal/TutorialModal.types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/ko.json
src/modules/translation/languages/zh.json

chore: updated banner, removed skip tutorial

---

README.md

chore: multiple asset pack format

---

src/components/SideBar/ItemDrawer/ItemDrawer.tsx

feat: skip category list in single category asset packs

---

Dockerfile

ci: fix postinstall in docker deployment

---

src/components/Preview/Preview.types.ts
src/ecsScene/scene.ts
src/modules/editor/sagas.ts

feat: unload scene when the editor is closed

---

src/modules/scene/constants.ts
src/modules/scene/sagas.ts
src/modules/scene/selectors.ts

fix: allow duplicate NFT shapes

---

package-lock.json
src/components/AssetCard/AssetCard.tsx
src/modules/scene/selectors.ts

fix: perf and disabled nft click

---

src/components/HomePage/HomePage.tsx
src/components/SideBar/AssetList/AssetList.tsx
src/components/SideBar/AssetPackList/AssetPackList.tsx
src/components/SideBar/WalletSignIn/WalletSignIn.css
src/components/SideBar/WalletSignIn/WalletSignIn.tsx
src/modules/analytics/sagas.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json

- copy changes
- tracking changes
- hide promo banners if dapper is active
Closes #520

chore: collectible campaign changes

---

src/modules/asset/sagas.ts

chore: whitelist new NFTs

---

src/components/Modals/DeployModal/DeployModal.container.ts
src/components/Modals/DeployModal/DeployModal.tsx
src/components/Modals/DeployModal/DeployModal.types.ts
src/lib/api.ts
src/modules/deployment/actions.ts
src/modules/deployment/sagas.ts
src/modules/translation/languages/ko.json
src/modules/translation/languages/zh.json
src/modules/user/actions.ts
src/modules/user/reducer.ts
src/modules/user/selectors.ts
src/modules/user/types.ts

Should fill the eth address deployment field with the selected wallet address if available

chore: auto fill eth address

---

src/components/Modals/AdBlockModal/AdBlockModal.tsx

fix: close adblock modal after continuing

---

src/modules/analytics/sagas.ts
src/modules/analytics/track.ts

chore: search assets tracking behaviour

---

src/components/Modals/DeployModal/ClearDeployment/ClearDeployment.tsx
src/components/Modals/DeployModal/DeployToLand/LandAtlas/LandAtlas.tsx
src/components/ProjectCard/ProjectCard.css
src/modules/analytics/sagas.ts

fix: publish to LAND polish

---

src/components/Modals/ImportModal/ImportModal.tsx

chore: track import scene failure

---

src/components/Modals/ShortcutsModal/ShortcutsModal.css

fix: make shortcuts modal scroll internally

---

src/components/Modals/DeployModal/DeployToLand/LandAtlas/LandAtlas.tsx
src/lib/api.ts

old endpoint: `/address/:address/parcels/authorized`
new endpoint: `/addresses/:address/parcels`

fix: authorized parcels endpoint

---

src/components/HomePage/HomePage.css
src/components/HomePage/HomePage.tsx
src/components/ProjectCard/ProjectCard.container.ts
src/components/ProjectCard/ProjectCard.css
src/components/ProjectCard/ProjectCard.tsx
src/components/ProjectCard/ProjectCard.types.ts
src/components/SyncToast/SyncToast.container.ts
src/components/SyncToast/SyncToast.css
src/components/SyncToast/SyncToast.tsx
src/components/SyncToast/SyncToast.types.ts
src/components/SyncToast/index.ts
src/modules/sync/domain/reducer.ts
src/modules/sync/domain/utils.ts
src/modules/sync/selectors.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Closes #575 
- Syncing indicators
- Error indicators
- Retry sync button

feat: show errors and syncing indicators

---

src/lib/api/auth.ts
src/lib/api/avatars.ts
src/lib/api/index.ts
src/modules/auth/sagas.ts

fix: fetch profile on login

---

src/components/HomePage/HomePage.container.ts
src/components/HomePage/HomePage.css
src/components/HomePage/HomePage.tsx
src/components/HomePage/HomePage.types.ts
src/lib/api/builder.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json
src/modules/ui/dashboard/selectors.ts
src/modules/ui/dashboard/types.ts
src/routing/locations.ts

feat: pagination

---

src/components/TopBar/TopBar.css
src/components/TopBar/TopBar.tsx

fix: prevent editing project while loading manifest

---

src/modules/common/store.ts

feat: warn user before leaving page while syncing

---

src/modules/editor/sagas.ts

fix: wait for assets to take screenshots

---

src/modules/common/store.ts
src/modules/sync/domain/actions.ts
src/modules/sync/domain/reducer.ts
src/modules/sync/reducer.ts

fix: remove ids from sync domain

---

src/modules/editor/sagas.ts
src/modules/scene/actions.ts
src/modules/scene/sagas.ts
src/modules/sync/sagas.ts

feat: skip save on manifest load

---

src/components/ProjectCard/ProjectCard.tsx

bust cache for remote thumbnails

fix: bust thumbnail cache

---

src/components/Modals/DeployModal/DeployToPool/DeployToPool.container.ts
src/components/Modals/DeployModal/DeployToPool/DeployToPool.tsx
src/components/Modals/DeployModal/DeployToPool/DeployToPool.types.ts
src/modules/analytics/sagas.ts
src/modules/analytics/track.ts
src/modules/common/sagas.ts

chore: track cloud saves events

---

src/components/Modals/DeployModal/DeployToLand/DeployToLand.container.ts
src/components/Modals/DeployModal/DeployToLand/DeployToLand.tsx
src/components/Modals/DeployModal/DeployToLand/DeployToLand.types.ts
src/components/Modals/DeployModal/DeployToLand/LandAtlas/LandAtlas.tsx
src/components/Modals/DeployModal/DeployToLand/LandAtlas/LandAtlas.types.ts
src/modules/deployment/sagas.ts

fix: publish to LAND while logged out

---

src/components/HomePage/HomePage.container.ts
src/components/HomePage/HomePage.tsx
src/components/HomePage/HomePage.types.ts

fix: prevent showing returning user banner to logged in user

---

src/modules/deployment/sagas.ts
src/modules/sync/sagas.ts

fix: wait for projects to be saved before syncing deployments

---

src/components/EditorPage/EditorPage.container.ts
src/components/EditorPage/EditorPage.tsx
src/components/EditorPage/EditorPage.types.ts
src/components/LocalStorageToast/LocalStorageToast.container.ts
src/components/LocalStorageToast/LocalStorageToast.css
src/components/LocalStorageToast/LocalStorageToast.tsx
src/components/LocalStorageToast/LocalStorageToast.types.ts
src/components/LocalStorageToast/index.ts
src/components/UserMenu/UserMenu.tsx
src/modules/analytics/sagas.ts
src/modules/auth/actions.ts
src/modules/auth/reducer.ts
src/modules/auth/sagas.ts
src/modules/auth/utils.ts
src/modules/location/sagas.ts
src/modules/scene/selectors.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

This PR adds back the localstorag toast, makes it appear after the user has 5 items in the scene, and changes the copy to prompt the user to sign in.

feat: add localstorage toast

---

src/components/HomePage/HomePage.container.ts
src/components/HomePage/HomePage.tsx
src/components/HomePage/HomePage.types.ts
src/modules/common/sagas.ts
src/modules/common/store.ts
src/modules/ui/dashboard/actions.ts
src/modules/ui/dashboard/reducer.ts
src/modules/ui/dashboard/sagas.ts
src/modules/ui/dashboard/selectors.ts
src/modules/ui/sagas.ts

Fixes #626  
Now:
Fixes #627 
Now: 
The usual flow still works fine:

fix: logged out state

---

src/modules/analytics/delighted.ts

chore: add email to delighted survey

---

package-lock.json
package.json

fix(Atlas): bump decentraland-ui

---

package-lock.json
src/components/DeploymentStatus/DeploymentStatus.container.ts
src/components/DeploymentStatus/DeploymentStatus.types.ts
src/components/Modals/DeployModal/DeployModal.container.ts
src/components/Modals/DeployModal/DeployModal.types.ts
src/components/ProjectCard/ProjectCard.container.ts
src/components/TopBar/TopBar.container.ts
src/modules/asset/selectors.ts
src/modules/deployment/sagas.ts
src/modules/deployment/selectors.ts
src/modules/editor/sagas.ts
src/modules/editor/selectors.ts
src/modules/project/sagas.ts
src/modules/scene/sagas.ts
src/modules/scene/selectors.ts
src/modules/scene/types.ts

chore: refactor selectors

---

src/components/AssetPackEditor/AssetPackEditor.css
src/lib/api/builder.ts
src/modules/asset/reducer.ts
src/modules/assetPack/reducer.ts
src/modules/assetPack/sagas.ts
src/modules/assetPack/utils.ts
src/modules/translation/languages/es.json

- Progress bar fix
- Copy fix
- Styles fix (error and overflow container on AssetPackEditor)
- Parallel requests fix
- Track new asset packs on state when created

fix: progress bar and requests

---

package-lock.json
package.json
src/components/AssetsEditor/AssetsEditor.css
src/components/AssetsEditor/SingleAssetEditor/SingleAssetEditor.css
src/components/Modals/CreateAssetPackModal/CreateAssetPackModal.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: add modal navigation

---

src/components/AssetImporter/AssetImporter.css
src/components/AssetImporter/AssetImporter.tsx
src/components/AssetImporter/AssetImporter.types.ts
src/components/FileImport/FileImport.css

feat: add spinner to asset importer

---

src/components/AssetsEditor/SingleAssetEditor/SingleAssetEditor.css
src/components/Modals/CreateAssetPackModal/CreateAssetPackModal.tsx
src/components/SideBar/SidebarHeader/SidebarHeader.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: added tooltip to create assetpack button

---

src/components/SideBar/AssetPackList/AssetPackList.tsx
src/components/SideBar/SidebarCard/SidebarCard.css
src/components/SideBar/SidebarCard/SidebarCard.tsx
src/components/SideBar/SidebarCard/SidebarCard.types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json
src/modules/ui/sidebar/selectors.ts
src/modules/ui/sidebar/utils.ts

feat: feature new asset packs

---

src/modules/analytics/delighted.ts

fix: race condition with delighted

fix: race condition with delighted

---

src/components/AssetsEditor/SingleAssetEditor/SingleAssetEditor.tsx
src/components/Modals/CreateAssetPackModal/CreateAssetPackModal.tsx

fix: setting ground

---

src/components/Modals/DeployModal/DeployToLand/LandAtlas/LandAtlas.css

fix: make rotate buttons clickeable

---

src/modules/translation/languages/es.json

fix: spanish translation errors

---

src/modules/ui/sidebar/selectors.ts
src/modules/ui/sidebar/utils.ts

fix: asset pack order

---

package-lock.json
package.json

fix: tags' placeholder styles 

---

src/components/Modals/EditAssetPackModal/EditAssetPackModal.tsx
src/components/Modals/EditAssetPackModal/EditAssetPackModal.types.ts

feat: ask for confirmation before exit only if dirty

---

src/components/Modals/CreateAssetPackModal/CreateAssetPackModal.container.ts
src/components/Modals/CreateAssetPackModal/CreateAssetPackModal.tsx
src/components/Modals/CreateAssetPackModal/CreateAssetPackModal.types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: added default asset pack name

---

src/components/AssetThumbnail/AssetThumbnail.css
src/components/AssetsEditor/AssetsEditor.tsx
src/components/Modals/CreateAssetPackModal/CreateAssetPackModal.tsx
src/components/Modals/EditAssetPackModal/EditAssetPackModal.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

chore: asset editing enhancements

---

src/modules/project/sagas.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

chore: translate default scene title

---

package-lock.json
package.json
src/components/EditorPage/EditorPage.tsx
src/experiments/index.ts

- add library [decentraland-experiments](https://github.com/decentraland/decentraland-experiments)
- implement first A/B testing: show or not TutorialModal

feat: add EXPERIMENT_TUTORIAL_OPEN

---

package-lock.json
src/components/AssetsEditor/AssetsEditor.css
src/components/AssetsEditor/AssetsEditor.tsx
src/components/SideBar/SidebarHeader/SidebarHeader.css
src/modules/assetPack/sagas.ts

- Resets category on asset pack delete
- Fixes Edit button css issue (chinese)
- Fixes pagination styles on edit mode
- Fixes progress bar bug
Closes #710

fix: reset category after deleting asset pack

---

src/components/EditorPage/EditorPage.container.ts
src/components/EditorPage/EditorPage.types.ts
src/components/Modals/DeployModal/DeployToLand/DeployToLand.tsx
src/components/Modals/DeployModal/DeployToLand/DeployToLand.types.ts
src/components/SideBar/ItemDrawer/ItemDrawer.container.tsx
src/components/SideBar/ItemDrawer/ItemDrawer.tsx
src/components/SideBar/ItemDrawer/ItemDrawer.types.ts

feat: try connecting the wallet preemptively before actions that require it

---

src/modules/editor/sagas.ts
src/modules/editor/utils.ts

fix: snap scale

---

src/components/Modals/CustomLayoutModal/CustomLayoutModal.tsx
src/components/Modals/EditProjectModal/EditProjectModal.tsx
src/components/Modals/ExportModal/ExportModal.tsx
src/components/Modals/ImportModal/ImportModal.tsx

feat: flip cancel/submit buttons

---

src/components/ProjectCard/ProjectCard.css

feat: don't hide the dropdown after blur

---

package-lock.json

chore: update lock for vulnerabilities (audit)

---

src/ecsScene/scene.ts
src/modules/migrations/manifest.ts

fix: add mappings on the third migration to fix some scenes

---

src/components/Modals/DeployModal/DeployToLand/LandAtlas/LandAtlas.tsx

feat: add colors consistent with the marketplace

---

package-lock.json
src/components/LocalStorageToast/LocalStorageToast.tsx
src/components/SyncToast/SyncToast.container.ts
src/components/SyncToast/SyncToast.css
src/components/SyncToast/SyncToast.tsx
src/components/SyncToast/SyncToast.types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Adds sign in link to sync toast
Missing copy changes because link first looks ugly @abarmat

feat: sync sign in

---

src/components/Preview/Preview.types.ts
src/modules/editor/sagas.ts

arguments for setGridResolution were pass in the wrong order

fix: entities rotation

---

package-lock.json
package.json

fix: update kernel version to fix builder's scene reset

---

.gitignore
package.json
scripts/postinstall.js
src/modules/project/export.ts

This prettifies the ECS, which seems to solve the weird error when uploading the `bin/game.js` to the content server.

fix: deploy to LAND

---

src/components/TopBar/TopBar.css
src/modules/scene/sagas.ts
src/modules/scene/utils.ts

Closes #839 
And makes it so that entity fields are also affected by renameEntity/removeEntityReferences

fix: renameEntity and removeEntityReferences

---

src/components/SideBar/EntityEditor/ActionField/ActionField.tsx
src/components/SideBar/EntityEditor/EntityField/EntityField.tsx
src/components/SideBar/EntityEditor/OptionsField/OptionsField.tsx

@belohlavek only if you like it

chore: more tooltips

---

src/components/SideBar/EntityEditor/ActionField/ActionField.tsx

fix: default values in actions

---

src/components/SideBar/EntityEditor/EntityField/EntityField.tsx
src/modules/scene/sagas.ts

fix: smart item duplication metrics

---

src/components/SideBar/EntityEditor/ActionField/ActionField.css
src/components/SideBar/EntityEditor/EntityField/EntityField.css
src/components/SideBar/EntityEditor/OptionsField/OptionsField.css
src/components/SideBar/EntityEditor/OptionsField/OptionsField.tsx
src/modules/scene/sagas.ts

Fixes option styles
Waits for editor to be ready before adding items

fix: option styles

---

src/components/SideBar/ItemDrawer/ItemDrawer.container.tsx
src/components/SideBar/ItemDrawer/ItemDrawer.tsx
src/components/SideBar/ItemDrawer/ItemDrawer.types.ts
src/components/SideBar/SidebarHeader/SidebarHeader.container.ts
src/components/SideBar/SidebarHeader/SidebarHeader.css
src/components/SideBar/SidebarSearch/SidebarSearch.container.tsx
src/components/SideBar/SidebarSearch/SidebarSearch.css
src/components/SideBar/SidebarSearch/SidebarSearch.tsx
src/components/SideBar/SidebarSearch/SidebarSearch.types.tsx
src/modules/ui/sidebar/actions.ts
src/modules/ui/sidebar/reducer.ts
src/modules/ui/sidebar/selectors.ts

feat: sort and filter smart items

---

src/components/EditorPage/EditorPage.tsx

fix: preview styles

---

src/components/Modals/ImportModal/ImportModal.tsx
src/components/ProjectCard/ProjectCard.css
src/modules/deployment/sagas.ts

Closes #831 
Closes #771 
Closes #812

fix: styles and sync

---

package-lock.json
package.json
src/components/SideBar/EntityEditor/ActionField/ActionField.tsx
src/components/SideBar/EntityEditor/EntityField/EntityField.css
src/components/SideBar/EntityEditor/EntityField/EntityField.tsx
src/components/SideBar/EntityEditor/EntityField/EntityField.types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: smart item search

---

package-lock.json
src/components/EditorPage/EditorPage.container.ts
src/components/EditorPage/EditorPage.tsx
src/components/EditorPage/EditorPage.types.ts
src/ecsScene/scene.ts
src/modules/asset/selectors.ts
src/modules/assetPack/sagas.ts
src/modules/editor/reducer.ts
src/modules/editor/sagas.ts
src/modules/editor/selectors.ts
src/modules/migrations/ISSUE-485/index.ts
src/modules/project/export.ts
src/modules/scene/actions.ts
src/modules/scene/reducer.ts
src/modules/scene/sagas.ts
src/modules/scene/selectors.ts
src/modules/scene/types.ts
src/modules/scene/utils.ts

Sync assets before loading scenes from the pool
Also remove `src` from `GLTFShape` component definition, closes #915

fix: sync pool scene assets

---

src/modules/migrations/manifest.ts
src/modules/migrations/store.ts
src/modules/migrations/utils.ts
src/modules/scene/utils.ts

fix: sanitize asset names

---

src/modules/project/export.ts

export project title into scene.json

fix: export name

---

src/modules/asset/sagas.ts
src/modules/asset/types.ts

fix: handle DAR asset with null name

---

src/index.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

site under maintenance

---

src/components/Modals/CreateItemModal/CreateItemModal.tsx
src/components/Modals/CreateItemModal/CreateItemModal.types.ts
src/lib/api/builder.ts
src/lib/getModelData.ts
src/modules/item/types.ts

Changes the shape of `Item` to support multiple representations. Also fixes the issues with the camera and the thumbnails generated from the models.

feat: representations

---

src/components/ItemCard/ItemImage/ItemImage.tsx
src/components/Modals/CreateItemModal/CreateItemModal.tsx
src/lib/api/builder.ts
src/modules/collection/types.ts
src/modules/item/types.ts

feat: use server

---

src/components/AvatarPage/AvatarPage.css
src/components/AvatarPage/AvatarPage.tsx
src/components/Modals/CreateCollectionModal/CreateCollectionModal.container.ts
src/components/Modals/CreateCollectionModal/CreateCollectionModal.css
src/components/Modals/CreateCollectionModal/CreateCollectionModal.tsx
src/components/Modals/CreateCollectionModal/CreateCollectionModal.types.ts
src/components/Modals/CreateCollectionModal/index.ts
src/components/Modals/index.ts
src/modules/collection/sagas.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: create collection

---

src/components/ItemBadge/ItemBadge.css
src/components/ItemBadge/ItemBadge.tsx
src/components/ItemDetailPage/ItemDetailPage.container.ts
src/components/ItemDetailPage/ItemDetailPage.tsx
src/components/ItemDetailPage/ItemDetailPage.types.ts
src/components/ItemDropdown/ItemDropdown.container.ts
src/components/ItemDropdown/ItemDropdown.css
src/components/ItemDropdown/ItemDropdown.tsx
src/components/ItemDropdown/ItemDropdown.types.ts
src/components/ItemDropdown/index.ts
src/components/Modals/CreateItemModal/CreateItemModal.css
src/components/Modals/CreateItemModal/CreateItemModal.tsx
src/components/Modals/CreateItemModal/CreateItemModal.types.ts
src/modules/item/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: add representation to item

---

src/components/CollectionDetailPage/CollectionItem/CollectionItem.tsx
src/components/ItemDetailPage/ItemDetailPage.tsx

fix: correctly create the open in editor link

---

src/components/ItemDetailPage/ItemDetailPage.container.ts
src/components/ItemDetailPage/ItemDetailPage.css
src/components/ItemDetailPage/ItemDetailPage.tsx
src/components/ItemDetailPage/ItemDetailPage.types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: add supply and collection to item detail

---

src/components/ActivityPage/Transaction/Transaction.tsx
src/components/ActivityPage/Transaction/TransactionDetail/TransactionDetail.tsx
src/components/ActivityPage/Transaction/TransactionDetail/TransactionDetail.types.ts
src/components/CollectionDetailPage/CollectionItem/CollectionItem.tsx
src/components/ItemEditorPage/LeftPanel/Collections/Collections.tsx
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.container.ts
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.tsx
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.types.ts
src/contracts/ERC721CollectionV2.json
src/contracts/ERC721CollectionV2.ts
src/contracts/ERC721CollectionV2Abi.ts
src/modules/collection/sagas.ts
src/modules/item/actions.ts
src/modules/item/reducer.ts
src/modules/item/sagas.ts
src/modules/item/types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Depends on #1086 
Closes #1089

feat: edit published items

---

src/components/AvatarPage/CollectionCard/CollectionCard.container.ts
src/components/AvatarPage/CollectionCard/CollectionCard.css
src/components/AvatarPage/CollectionCard/CollectionCard.tsx
src/components/AvatarPage/CollectionCard/CollectionCard.types.ts
src/components/AvatarPage/ItemCard/ItemCard.css
src/components/AvatarPage/ItemCard/ItemCard.tsx
src/components/CollectionBadge/CollectionBadge.css
src/components/CollectionBadge/CollectionBadge.tsx
src/components/CollectionBadge/CollectionBadge.types.ts
src/components/CollectionBadge/index.ts
src/components/CollectionDetailPage/CollectionDetailPage.tsx
src/components/ItemDetailPage/ItemDetailPage.tsx
src/components/ItemEditorPage/LeftPanel/Header/Header.css
src/components/ItemEditorPage/LeftPanel/Header/Header.tsx
src/components/ItemEditorPage/RightPanel/MultiSelect/MultiSelect.tsx
src/components/ItemEditorPage/RightPanel/MultiSelect/MultiSelect.types.ts
src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/components/ItemEditorPage/RightPanel/Select/Select.tsx
src/components/ItemEditorPage/RightPanel/Select/Select.types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Depends #1086 
Closes #1100 #1091

feat: disable published actions + collection badge

---

src/components/Modals/CollectionManagersModal/EmptyManager/EmptyManager.css
src/components/Modals/CollectionManagersModal/EmptyManager/EmptyManager.tsx
src/components/Modals/CreateCollectionModal/CreateCollectionModal.tsx
src/components/Modals/CreateItemModal/CreateItemModal.tsx
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.tsx
src/components/Modals/MintItemsModal/MintItemsModal.tsx
src/components/Modals/MintItemsModal/MintableItem/MintableItem.css
src/components/Modals/MintItemsModal/MintableItem/MintableItem.tsx
src/themes/components/Field.css

feat: enter key modals

---

src/components/CollectionDetailPage/CollectionItem/CollectionItem.css
src/components/CollectionDetailPage/CollectionItem/CollectionItem.tsx
src/components/ItemDetailPage/ItemDetailPage.tsx
src/components/ItemEditorPage/LeftPanel/Items/Items.css
src/components/ItemEditorPage/LeftPanel/Items/Items.tsx
src/components/Modals/CreateItemModal/CreateItemModal.tsx
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.tsx
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.types.ts
src/components/Modals/MintItemsModal/MintableItem/MintableItem.tsx
src/lib/api/builder.ts
src/modules/collection/export.ts
src/modules/collection/sagas.ts
src/modules/collection/utils.ts
src/modules/deployment/contentUtils.ts
src/modules/deployment/sagas.ts
src/modules/item/actions.ts
src/modules/item/export.ts
src/modules/item/reducer.ts
src/modules/item/sagas.ts
src/modules/item/types.ts
src/modules/item/utils.ts

feat: post items to the content server

---

src/components/Modals/CreateItemModal/CreateItemModal.tsx
src/lib/api/builder.ts
src/modules/collection/actions.ts
src/modules/collection/reducer.ts
src/modules/collection/sagas.ts
src/modules/collection/types.ts
src/modules/item/actions.ts
src/modules/item/export.ts
src/modules/item/reducer.ts
src/modules/item/sagas.ts
src/modules/item/types.ts
src/modules/item/utils.ts

Closes #1109 
Also fixed issue where collections where uploaded with `items` and was breaking the server's schema

feat: added image with rarity background to item deployment

---

src/components/CollectionDetailPage/CollectionItem/CollectionItem.css
src/components/CollectionDetailPage/CollectionItem/CollectionItem.tsx

chore: add missing translations and mana symbol

---

src/lib/getModelData.ts

fix: hide hair mat

---

src/components/AvatarPage/CollectionCard/CollectionCard.dnd.ts
src/components/AvatarPage/CollectionCard/CollectionCard.tsx

fix: prevent drag and drop on published collections

---

src/components/ItemEditorPage/LeftPanel/Collections/Collections.tsx
src/components/ItemEditorPage/LeftPanel/Collections/SidebarCollection/SidebarCollection.css
src/components/ItemEditorPage/LeftPanel/Collections/SidebarCollection/SidebarCollection.tsx
src/components/ItemEditorPage/LeftPanel/Header/Header.tsx
src/components/ItemEditorPage/LeftPanel/Items/Items.tsx
src/components/ItemEditorPage/RightPanel/Input/Input.css
src/components/ItemEditorPage/RightPanel/Input/Input.tsx
src/components/ItemEditorPage/RightPanel/RightPanel.container.ts
src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/components/ItemEditorPage/RightPanel/RightPanel.types.ts
src/components/ItemEditorPage/RightPanel/Tags/Tags.css
src/components/ItemEditorPage/RightPanel/Tags/Tags.tsx

fix: disable published items and collections

---

src/modules/collection/sagas.ts
src/modules/item/sagas.ts

fix: connect and switch wallet

---

src/modules/analytics/track.ts

chore: track wearables

---

src/components/AvatarPage/AvatarPage.css
src/components/AvatarPage/AvatarPage.tsx
src/components/CollectionDetailPage/CollectionItem/CollectionItem.tsx
src/components/ItemEditorPage/LeftPanel/Collections/SidebarCollection/SidebarCollection.css
src/components/ItemEditorPage/LeftPanel/LeftPanel.css
src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx
src/components/ItemEditorPage/RightPanel/MultiSelect/MultiSelect.tsx
src/components/ItemEditorPage/RightPanel/Tags/Tags.tsx
src/modules/editor/sagas.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Added button to open editor from the dashboard:
Also added an empty state for the editor and fixed a bunch of small bugs and warnings

feat: open editor

---

src/components/ItemEditorPage/RightPanel/Input/Input.tsx
src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/components/ItemEditorPage/RightPanel/Tags/Tags.tsx
src/components/Modals/CreateItemModal/CreateItemModal.tsx
src/modules/item/types.ts
src/modules/item/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

also fixed the metadata issue with bodyshapes + added description to metadata on chain

feat: ability to change item's description

---

src/components/ItemEditorPage/LeftPanel/Header/Header.container.ts
src/components/ItemEditorPage/LeftPanel/Header/Header.tsx
src/components/ItemEditorPage/LeftPanel/Header/Header.types.ts

fix: hide actions for logged out user

---

src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.tsx

fix: make beneficiary mandatory

---

src/components/LandDetailPage/LandDetailPage.tsx
src/lib/file.ts
src/modules/deployment/sagas.ts
src/modules/deployment/utils.ts
src/modules/stats/action.ts

Fixes #1176 
Fixes #1177 
Fixes #1178 
Closes #1084

fix a few bugs

---

src/components/LandEditPage/LandEditPage.css
src/components/LandEditPage/LandEditPage.tsx
src/components/LandOperatorPage/LandOperatorForm/LandOperatorForm.css
src/components/LandOperatorPage/LandOperatorForm/LandOperatorForm.tsx
src/components/LandTransferPage/LandTransferPage.css
src/components/LandTransferPage/LandTransferPage.tsx
src/components/Modals/DissolveModal/DissolveModal.tsx
src/components/Modals/EstateEditorModal/EstateEditorModal.tsx

feat: keep the cancel-submit order for forms

---

src/modules/translation/languages/en.json
src/modules/translation/languages/zh.json

Fix
https://github.com/decentraland/builder/issues/1192

Bug: Fix typo on use as alias

---

src/components/ENSListPage/ENSListPage.css

Fix
https://github.com/decentraland/builder/issues/1193

Bug: Fix cursor pointer on name list

---

src/components/Modals/UseAsAliasModal/UseAsAliasModal.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Fix
https://github.com/decentraland/builder/issues/1195

Bug: Fix use as alias when oldname changes

---

src/components/LandAssignENSPage/LandAssignENSPage.tsx

Fix
https://github.com/decentraland/builder/issues/1200

fix: without massive loading in fullscreen

---

src/modules/ens/reducer.ts

Fix:
Cleaning previous error state when request happens.
https://github.com/decentraland/builder/issues/1211

Fix: retry tx not working

---

src/components/ENSListPage/ENSListPage.tsx
src/components/ENSListPage/ENSListPage.types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

FIX
https://github.com/decentraland/builder/issues/1194

Bug: ordering name ens table

---

src/modules/translation/languages/en.json

FIX
https://github.com/decentraland/builder/issues/1215

Fix: Bug activity text past tense

---

src/components/ClaimENSPage/ClaimENSPage.tsx

Fix
https://github.com/decentraland/builder/issues/1198

Bug: loading mana allowance and rejection

---

src/components/ActivityPage/Transaction/Transaction.tsx
src/components/ClaimENSPage/ClaimENSPage.container.ts
src/components/ClaimENSPage/ClaimENSPage.css
src/components/ClaimENSPage/ClaimENSPage.tsx
src/components/ClaimENSPage/ClaimENSPage.types.ts
src/modules/ens/actions.ts
src/modules/ens/reducer.ts
src/modules/ens/sagas.ts
src/modules/ens/selectors.ts
src/modules/ens/types.ts
src/modules/ens/utils.ts
src/modules/land/reducer.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: allow mana as a transaction

---

src/components/ClaimENSPage/ClaimENSPage.css
src/components/ClaimENSPage/ClaimENSPage.tsx
src/components/ENSListPage/ENSListPage.css

Fix: css for dropdown (ens list table) and chars counter (claim name page)

Fix: css for dropdown (ens list table) and chars counter (claim name page)

---

src/modules/ens/sagas.ts

Fix for upgrading avatar (in use as alias) correctly.

fix: updating avatar with new version

---

src/modules/analytics/track.ts

Feat: ENS analytics

---

src/components/ClaimENSPage/ClaimENSPage.tsx
src/components/Modals/ClaimNameFatFingerModal/ClaimNameFatFingerModal.tsx
src/modules/ens/utils.ts

Fixes #1199 
Fixes #1236 
Fixes #1237

fix: claim name bugs

---

src/components/ClaimENSPage/ClaimENSPage.tsx
src/components/ENSListPage/ENSListPage.tsx

feat: change to https

---

src/components/Modals/CreateCollectionModal/CreateCollectionModal.container.ts
src/components/Modals/CreateCollectionModal/CreateCollectionModal.css
src/components/Modals/CreateCollectionModal/CreateCollectionModal.tsx
src/components/Modals/CreateCollectionModal/CreateCollectionModal.types.ts
src/modules/collection/sagas.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: prevent repeated collection names

---

package-lock.json
src/components/AvatarPage/AvatarPage.container.ts
src/components/CollectionDetailPage/CollectionDetailPage.container.ts
src/components/CollectionDetailPage/CollectionDetailPage.tsx
src/components/CollectionDetailPage/CollectionDetailPage.types.ts
src/components/CollectionDetailPage/CollectionItem/CollectionItem.container.ts
src/components/CollectionDetailPage/CollectionItem/CollectionItem.tsx
src/components/CollectionDetailPage/CollectionItem/CollectionItem.types.ts
src/components/CollectionImage/CollectionImage.container.ts
src/components/ItemDetailPage/ItemDetailPage.container.ts
src/components/ItemDropdown/ItemDropdown.container.ts
src/components/ItemEditorPage/RightPanel/RightPanel.container.ts
src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/components/ItemEditorPage/RightPanel/RightPanel.types.ts
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.container.ts
src/components/Modals/MintItemsModal/MintItemsModal.container.ts
src/components/Modals/MintItemsModal/MintItemsModal.tsx
src/components/Modals/MintItemsModal/MintItemsModal.types.ts
src/modules/collection/selectors.ts
src/modules/collection/utils.ts
src/modules/item/selectors.ts
src/modules/item/utils.ts

This PR allows managers and minters to see collections/items

Feat: allow item and collection managers and minters to edit items

---

package-lock.json
package.json
src/components/CurationPage/CollectionRow/CollectionRow.css
src/components/CurationPage/CollectionRow/CollectionRow.tsx
src/components/ItemDropdown/ItemDropdown.tsx
src/components/ItemEditorPage/CenterPanel/CenterPanel.tsx
src/components/ItemEditorPage/ItemEditorPage.tsx
src/components/ItemEditorPage/TopPanel/ReviewModal/ReviewModal.css
src/components/ItemEditorPage/TopPanel/ReviewModal/ReviewModal.tsx
src/components/ItemImage/ItemImage.tsx
src/lib/api/builder.ts
src/modules/collection/reducer.ts
src/modules/collection/sagas.ts
src/modules/collection/types.ts
src/modules/common/sagas.ts
src/modules/forum/actions.ts
src/modules/forum/sagas.ts
src/modules/forum/types.ts
src/modules/forum/utils.ts
src/modules/item/export.ts
src/modules/item/sagas.ts
src/modules/item/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Continues: #1281 
Depends on: https://github.com/decentraland/builder-server/pull/185
Closes: #1242

feat: forum

---

src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/components/Modals/CreateItemModal/CreateItemModal.tsx
src/components/Modals/CreateItemModal/utils.ts
src/modules/item/utils.ts

Closes https://github.com/decentraland/account/issues/106
Closes https://github.com/decentraland/account/issues/108

feat: disable categories for gltf/glb items

---

src/modules/forum/utils.ts
src/modules/wallet/sagas.ts

Example of the new template:
https://forum.decentraland.org/t/a-new-wearables-collection-created-by-new-address-who-dis-is-ready-for-review/635
Closes https://github.com/decentraland/builder-server/issues/200

feat: update forum template

---

src/components/AssetPackEditor/AssetPackEditor.tsx
src/components/ItemEditorPage/LeftPanel/Collections/Collections.tsx
src/components/ItemEditorPage/LeftPanel/Items/Items.tsx
src/components/ItemEditorPage/RightPanel/RightPanel.container.ts
src/components/ItemEditorPage/RightPanel/RightPanel.css
src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/components/ItemEditorPage/RightPanel/RightPanel.types.ts
src/components/ItemImage/ItemImage.tsx
src/components/ItemImage/ItemImage.types.ts
src/components/LandPage/TableRow/TableRow.tsx
src/components/Modals/CreateItemModal/CreateItemModal.container.ts
src/components/Modals/CreateItemModal/CreateItemModal.css
src/components/Modals/CreateItemModal/CreateItemModal.tsx
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.container.ts
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.tsx
src/components/ProjectCard/ProjectCard.tsx
src/lib/api/builder.ts
src/lib/sort.ts
src/modules/deployment/contentUtils.ts
src/modules/item/actions.ts
src/modules/item/export.ts
src/modules/item/sagas.ts
src/modules/item/types.ts
src/modules/item/utils.ts
src/modules/ui/sidebar/selectors.ts
src/modules/ui/sidebar/utils.ts

Closes https://github.com/decentraland/account/issues/107

feat update thumbnails

---

src/components/ItemDetailPage/ItemDetailPage.tsx

fix: show item category correctly on the detail

---

src/components/CollectionDetailPage/CollectionDetailPage.container.ts
src/components/CollectionDetailPage/CollectionDetailPage.css
src/components/CollectionDetailPage/CollectionDetailPage.tsx
src/components/CollectionDetailPage/CollectionDetailPage.types.ts
src/components/CollectionDetailPage/ContextMenu/ContextMenu.container.ts
src/components/CollectionDetailPage/ContextMenu/ContextMenu.css
src/components/CollectionDetailPage/ContextMenu/ContextMenu.tsx
src/components/CollectionDetailPage/ContextMenu/ContextMenu.types.ts
src/components/CollectionDetailPage/ContextMenu/index.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json
src/themes/components/Popup.css
src/themes/index.ts

feat: view collection forum and collection address

---

src/modules/collection/sagas.ts

Related to https://github.com/decentraland/builder-server/issues/206

fix: do not create more than one forum post

---

src/components/Modals/CreateItemModal/CreateItemModal.tsx

fix: center thumbnails for texture items

---

src/components/ItemBadge/ItemBadge.css
src/components/ItemBadge/ItemBadge.tsx
src/components/ItemDetailPage/ItemDetailPage.tsx
src/components/Modals/CreateItemModal/CreateItemModal.css
src/components/Modals/CreateItemModal/CreateItemModal.tsx
src/modules/item/types.ts
src/modules/item/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: add representation to item detail

---

src/components/ItemImage/ItemImage.tsx
src/components/Modals/CreateItemModal/CreateItemModal.tsx
src/components/Modals/CreateItemModal/CreateItemModal.types.ts
src/components/Modals/PublishCollectionModal/PublishCollectionModal.tsx
src/modules/item/utils.ts

feat: fix representation check

---

src/components/ItemEditorPage/LeftPanel/Header/Header.tsx
src/components/ItemEditorPage/RightPanel/MultiSelect/MultiSelect.css
src/components/ItemEditorPage/RightPanel/MultiSelect/MultiSelect.tsx
src/components/ItemEditorPage/RightPanel/RightPanel.css
src/components/Modals/CreateItemModal/CreateItemModal.css
src/components/Modals/CreateItemModal/CreateItemModal.tsx
src/modules/item/export.ts
src/modules/item/utils.ts
src/modules/translation/languages/en.json

Depends on https://github.com/decentraland/builder-server/pull/213
Closes #1338
Closes https://github.com/decentraland/builder-server/issues/211

fix: allow for published item editing

---

src/components/Modals/CreateItemModal/CreateItemModal.tsx
src/modules/item/types.ts
src/modules/item/utils.ts

Testing files:
[Archive.zip](https://github.com/decentraland/builder/files/6424551/Archive.zip)
[hwn_2020_ddlm_01_eyes.zip](https://github.com/decentraland/builder/files/6424552/hwn_2020_ddlm_01_eyes.zip)
Current:
Expected:

fix: zip files with mask

---

src/modules/editor/sagas.ts
src/modules/item/sagas.ts

fix: update editor on published item update

---

src/modules/item/sagas.ts

feat: send a tx before POSTing new items

---

src/components/CollectionDetailPage/ContextMenu/ContextMenu.container.ts
src/components/CollectionDetailPage/ContextMenu/ContextMenu.tsx
src/components/CollectionDetailPage/ContextMenu/ContextMenu.types.ts
src/lib/api/builder.ts
src/modules/collection/reducer.ts
src/modules/collection/sagas.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: add an option to post a published collection to the forum

---

src/modules/forum/utils.ts

Took some liberties with the <author> part of the issue. I don't know if it's the best idea. The new title will look like this:
`Collection 'Juanca ladora' created by 0x1D9a...98f8a is ready for review` 
@nachomazzara 
Closes #1360

chore: new forum post title

---

src/components/ItemEditorPage/RightPanel/RightPanel.tsx

chore: submit -> save

---

src/components/Modals/PublishCollectionModal/PublishCollectionModal.tsx

feat: update mana symbol on publish to Matic's

---

src/components/Info/Info.css
src/components/Info/Info.tsx
src/components/Info/Info.types.ts
src/components/Info/index.ts
src/components/ItemEditorPage/RightPanel/MultiSelect/MultiSelect.css
src/components/ItemEditorPage/RightPanel/MultiSelect/MultiSelect.tsx
src/components/Modals/CollectionManagersModal/CollectionManagersModal.tsx
src/components/Modals/CreateItemModal/CreateItemModal.tsx
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.css
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.tsx
src/components/Modals/EstateEditorModal/EstateEditorModal.css
src/components/Modals/EstateEditorModal/EstateEditorModal.tsx
src/components/Modals/PublishCollectionModal/PublishCollectionModal.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Still working out some details in Figma
Closes #1353

chore: new copies

---

src/modules/analytics/track.ts

feat: update tracking

---

.ci/.env.dev
.ci/.env.prd
.ci/.env.stg
.env.example
now.json
src/components/Modals/PublishCollectionModal/PublishCollectionModal.container.ts
src/components/Modals/PublishCollectionModal/PublishCollectionModal.css
src/components/Modals/PublishCollectionModal/PublishCollectionModal.tsx
src/components/Modals/PublishCollectionModal/PublishCollectionModal.types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: prevent 0 mana publish

---

src/lib/api/auth.ts
src/modules/identity/sagas.ts

fix: send auth addresses as lowecase

---

src/components/CurationPage/CurationPage.tsx

fix: pagination margin on curation page

---

src/components/AssetCard/VerticalCard/VerticalCard.css
src/components/AssetCard/VerticalCard/VerticalCard.tsx
src/components/CollectionDetailPage/CollectionItem/CollectionItem.tsx
src/components/DeployButton/DeployButton.css
src/components/DeployButton/DeployButton.tsx
src/components/DeploymentStatus/DeploymentStatus.tsx
src/components/ENSListPage/ENSListPage.css
src/components/ENSListPage/ENSListPage.tsx
src/components/Info/Info.css
src/components/IntroPopup/IntroPopup.css
src/components/ItemEditorPage/CenterPanel/CenterPanel.css
src/components/ItemEditorPage/CenterPanel/CenterPanel.tsx
src/components/ItemEditorPage/LeftPanel/Items/SidebarItem/SidebarItem.css
src/components/ItemEditorPage/LeftPanel/Items/SidebarItem/SidebarItem.tsx
src/components/ItemEditorPage/RightPanel/RightPanel.css
src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/components/Modals/DeployModal/DeployToLand/LandAtlas/LandAtlas.css
src/modules/collection/utils.ts
src/modules/item/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json
src/themes/components/Popup.css
src/themes/theme.css

I think it might be useful to show the collection staus on the editor page!
Closes #1381

feat: prevent approved collection editing. link to forum

---

src/components/ItemEditorPage/RightPanel/RightPanel.container.ts
src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/components/ItemEditorPage/RightPanel/RightPanel.types.ts
src/components/Modals/CreateItemModal/CreateItemModal.tsx
src/modules/transaction/selectors.ts

Closes #1379 
Closes #1380  
Closes #1390

fix: correctly handle categories/props on updated items

---

src/modules/wallet/sagas.ts

fix: use the correct chain id for MANA auth

---

src/modules/ens/selectors.ts

fix: claim ens

---

src/components/Modals/CreateItemModal/CreateItemModal.tsx

fix: counting twice as many textures

---

src/lib/api/builder.ts

Fixes a problem where the duplicated collection name error was not reflected correctly

feat: show the actual error the server returned for api requests

---

src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.css
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json

fix: prevent overlapping between X and titles

---

src/components/CollectionDetailPage/CollectionItem/CollectionItem.tsx
src/components/ItemDetailPage/ItemDetailPage.tsx
src/modules/item/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: show item as free on the detail page

---

src/components/ItemEditorPage/RightPanel/RightPanel.tsx

fix: disallow repeated overrides and hides categories

---

src/components/ItemEditorPage/TopPanel/TopPanel.css
src/components/ItemEditorPage/TopPanel/TopPanel.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: disable curation if items are being uploaded

---

src/components/Modals/CreateItemModal/CreateItemModal.tsx

fix: save published items representations correctly

---

src/components/CollectionBadge/CollectionBadge.tsx
src/components/DeployButton/DeployButton.tsx
src/components/ENSListPage/ENSListPage.tsx
src/components/ItemEditorPage/RightPanel/RightPanel.css
src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/components/SideBar/SidebarHeader/SidebarHeader.tsx
src/modules/item/export.ts
src/modules/item/sagas.ts
src/modules/item/utils.ts
src/modules/toast/sagas.ts

feat: retry deployment

---

src/modules/item/export.ts
src/modules/item/types.ts

feat: remove unused catalyst properties

---

src/components/AssetImporter/AssetImporter.tsx

Related to https://github.com/decentraland/builder-server/pull/236

fix: don't send duplicated asset ids anymore

---

src/lib/api/peer.ts
src/modules/deployment/utils.ts
src/modules/ens/utils.ts
src/modules/item/utils.ts

feat: get thumbnails from content server

---

src/modules/deployment/utils.ts

https://github.com/decentraland/builder-server/blob/master/scripts/seed/1567613264447_data/e6fa9601-3e47-4dff-9a84-e8e017add15a.json#L2327

fix: update default ground asset id

---

src/modules/project/export.ts

This PR fixes an issue where, if two assets had some file with the exact same path + filename, the mappings from one asset would override the other. This only happened with static assets, since they were not namespaced with the asset id, and were saved all together under a `/models` folder. The smart items were namespaced, but stored at the root level. To keep things more consistent, I stored all the assets (either smart or not) under an `/assets` folder, and they are all namespaced using the asset id.
Some assets were reported to have this behavior, like most of the fountain assets.
A scene like this:
Would end up like this once deployed (notice the repeated models):
After this fix, it looks like this:
This issue also affected exported scenes (.zip files to be used with the SDK), which …

fix: namespace all files with asset id to prevent overrides

---

src/components/ActivityPage/Transaction/Transaction.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: show grants/revokes on transaction activity

---

src/components/ClaimENSPage/ClaimENSPage.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Add message about using Ethereum MANA for name claiming

---

package-lock.json
package.json
src/modules/collection/utils.ts
src/modules/item/utils.ts

Use the `getURNProtocol` helper from `@dcl/schemas` to generate item or collection URNs

feat: use getURNProtocol to generate URNs

---

.github/workflows/node.yml
README.md
jest.config.js
package.json
src/modules/item/selectors.spec.ts
src/modules/item/selectors.ts

This PR adds the Jest configs, some tests and the CI process to run tests and report coverage.
The CI only runs the tests because Vercel already builds and deploys the site.

chore: Add tests and CI

---

.github/workflows/node.yml
jest.config.js
src/components/Modals/CreateItemModal/CreateItemModal.css
src/components/Modals/CreateItemModal/CreateItemModal.tsx
src/lib/api/builder.ts
src/modules/item/sagas.spec.ts
src/modules/item/sagas.ts
src/modules/item/selectors.ts
src/modules/item/utils.ts
src/modules/modal/sagas.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json
src/setupTests.ts

feat: save published items

---

src/modules/project/export.ts
src/modules/project/sagas.ts
src/modules/project/utils.ts

fix: export

---

package-lock.json
package.json
src/modules/collection/sagas.ts

Close #1543
Waiting for the new committee smart contract to be deployed on matic mainnet

Feat: update committee smart contract

---

src/components/CollectionsPage/CollectionCard/CollectionCard.tsx
src/components/Modals/CreateThirdPartyCollectionModal/CreateThirdPartyCollectionModal.tsx
src/lib/urn.spec.ts
src/lib/urn.ts
src/modules/collection/utils.spec.ts
src/modules/collection/utils.ts
src/modules/item/export.ts
src/modules/item/sagas.ts
src/modules/item/selectors.ts
src/modules/item/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Missing tests for the newly introduced decodeURN method
Closes #1630 
Closes #1650

feat: list third party collections

---

src/components/ItemDetailPage/ItemDetailPage.tsx

fix: Show edit representation action on published item

---

src/components/CollectionDetailPage/CollectionContextMenu/CollectionContextMenu.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

https://user-images.githubusercontent.com/692077/141854898-5d6aea95-5f6a-406f-b085-4c15c4fc71b9.mov
@nachomazzara you think it's better to just hide `Copy URN` for non-published collections?
Closes #1564

feat: copy dcl collection urn

---

src/components/ThirdPartyCollectionDetailPage/CollectionItem/CollectionItem.container.ts
src/components/ThirdPartyCollectionDetailPage/CollectionItem/CollectionItem.tsx
src/components/ThirdPartyCollectionDetailPage/CollectionItem/CollectionItem.types.ts
src/lib/api/builder.ts
src/modules/collection/sagas.ts
src/modules/item/sagas.ts

feat: delete third party items from Collection detail

---

src/components/Modals/BuyItemSlotsModal/BuyItemSlotsModal.types.ts
src/modules/analytics/track.ts
src/modules/common/types.ts
src/modules/thirdParty/reducer.ts
src/modules/tiers/actions.ts
src/modules/tiers/reducer.spec.ts
src/modules/tiers/reducer.ts
src/modules/tiers/sagas.ts
src/modules/tiers/types.ts

The types in the tiers module weren't written as they're meant to be, this PR fixes that.

fix: Tiers types

---

package-lock.json
package.json
public/index.html

This PR removes the segment script and uses it from the analytics module.

feat: Use segment from the analytics module

---

src/modules/tiers/actions.spec.ts

This PR fixes the it texts for the actions selectors.

fix: It text in tiers actions

---

src/components/ItemImage/ItemImage.css
src/components/ItemImage/ItemImage.tsx
src/components/SmartBadge/SmartBadge.css
src/components/SmartBadge/SmartBadge.tsx
src/components/SmartBadge/index.ts
src/components/SmartIcon/SmartIcon.css
src/components/SmartIcon/SmartIcon.tsx
src/components/SmartIcon/index.ts
src/components/SmartIcon/smart.svg
src/lib/urn.spec.ts
src/lib/urn.ts
src/modules/item/sagas.spec.ts
src/modules/item/sagas.ts
src/modules/item/types.ts
src/modules/item/utils.spec.ts
src/modules/item/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Added support to publish smart wearables + badge

feat: smart wearables

---

src/modules/editor/sagas.ts
src/modules/editor/types.ts

This PR removes the base wearables that hide or replace others.
This is done to fix a issue where base wearables hide the user's items.

fix: Remove wearables that hide or replace others

---

README.md
now.json

Removing outdated content in README.md. Fixes: https://github.com/decentraland/builder/issues/1714
I'm not familiar with this repo so if something is wrong please let me know and I will change it

Removes outdated content in README.md

---

src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx

fix: show items in left sidebar

---

src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.tsx

feat: Render Not Found page if the collection is not of TP type

---

src/components/AssetImporter/AssetImporter.tsx

fix: Allow zipped asset imports

---

src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/components/ThirdPartyCollectionDetailPage/CollectionContextMenu/CollectionContextMenu.module.css
src/components/ThirdPartyCollectionDetailPage/CollectionContextMenu/CollectionContextMenu.tsx
src/components/ThirdPartyCollectionDetailPage/CollectionItem/CollectionItem.module.css
src/components/ThirdPartyCollectionDetailPage/CollectionItem/CollectionItem.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: Block Item/Collection URN editing when published

---

src/components/ItemEditorPage/LeftPanel/LeftPanel.container.ts
src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx
src/components/ItemEditorPage/LeftPanel/LeftPanel.types.ts

fix: TP items not showing in Item Editor

---

src/components/ItemEditorPage/TopPanel/TopPanel.tsx
src/components/Modals/ApprovalFlowModal/ApprovalFlowModal.container.ts
src/components/Modals/ApprovalFlowModal/ApprovalFlowModal.tsx
src/components/Modals/ApprovalFlowModal/ApprovalFlowModal.types.ts
src/modules/collection/constants.ts
src/modules/collection/sagas.ts
src/modules/collection/utils.ts
src/modules/item/sagas.ts
src/modules/item/selectors.ts
src/modules/thirdParty/actions.ts
src/modules/thirdParty/sagas.spec.ts
src/modules/thirdParty/sagas.ts
src/modules/thirdParty/utils.ts
src/modules/transaction/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: Update the ApprovalFlowModal to support TP items

---

src/modules/curations/itemCuration/reducer.spec.ts
src/modules/thirdParty/actions.ts
src/modules/thirdParty/sagas.spec.ts
src/modules/thirdParty/sagas.ts

fix: Add thirdPartyId param when dispatching request fetch available slots

---

src/modules/collection/sagas.spec.ts
src/modules/collection/sagas.ts

feat: redirect to the collection detail after create

---

src/modules/collection/sagas.spec.ts
src/modules/collection/sagas.ts

fix: Redirect to TP detail page after creating a new one

---

src/components/ThirdPartyCollectionDetailPage/CollectionItem/CollectionItem.module.css
src/components/ThirdPartyCollectionDetailPage/CollectionItem/CollectionItem.tsx

fix: collection name overlap

---

src/components/Modals/BuyItemSlotsModal/BuyItemSlotsModal.module.css
src/components/Modals/BuyItemSlotsModal/BuyItemSlotsModal.tsx
src/components/Modals/BuyItemSlotsModal/BuyItemSlotsModal.types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: disallow invalid slots to buy

---

src/components/ThirdPartyCollectionDetailPage/CollectionContextMenu/CollectionContextMenu.module.css
src/components/ThirdPartyCollectionDetailPage/CollectionContextMenu/CollectionContextMenu.tsx
src/components/ThirdPartyCollectionDetailPage/CollectionItem/CollectionItem.module.css
src/modules/collection/reducer.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json
src/themes/components/Dropdown.css

feat: can't delete published collections

---

src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.container.ts
src/modules/collection/sagas.ts
src/modules/location/selectors.spec.ts
src/modules/location/selectors.ts

feat: redirect to the collection list after TP delete

---

src/modules/item/selectors.ts

fix: Display the right status for TP items with changes

---

src/components/CollectionProvider/CollectionProvider.container.ts
src/components/CollectionProvider/CollectionProvider.tsx
src/components/CollectionProvider/CollectionProvider.types.ts
src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.tsx
src/modules/item/utils.ts

The following screenshots show an item with changes but since there was no approval yet, the push changes is blocked.
Closes #1878

feat: Do not let push changes until TP collection is approved

---

src/modules/item/types.ts
src/modules/thirdParty/sagas.spec.ts
src/modules/thirdParty/sagas.ts
src/modules/thirdParty/types.ts
src/modules/thirdParty/utils.ts

chore: remove signedMessage from the publish endpoint body

---

package-lock.json
package.json
src/modules/collection/sagas.spec.ts
src/modules/thirdParty/sagas.spec.ts
src/modules/thirdParty/sagas.ts

feat: add p-queue to queue up requests

---

src/modules/item/sagas.spec.ts
src/modules/item/sagas.ts

This PR fixes an issue with the catalyst image not being regenerated after a rarity change.

fix: Catalyst image not regenerating with rarity change

---

src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx
src/modules/collection/actions.ts
src/modules/collection/sagas.spec.ts
src/modules/collection/sagas.ts
src/modules/curations/itemCuration/reducer.spec.ts
src/modules/curations/itemCuration/reducer.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: update approve state

---

src/modules/item/selectors.spec.ts
src/modules/item/selectors.ts
src/modules/item/utils.spec.ts
src/modules/item/utils.ts

This PR fixes a bug where the sync state of the TP and standard items was not correct.

fix: Sync state for items

---

package-lock.json
package.json
src/modules/collection/sagas.ts
src/modules/collection/utils.ts
src/modules/item/export.ts
src/modules/item/types.ts

This PR enables the deployment of TP items.
The deployment of TP items can be tested in `peer-uw-1.decentraland.zone`.

feat: Enable TP item deployment

---

src/components/ThirdPartyCollectionDetailPage/CollectionPublishButton/CollectionPublishButton.tsx
src/components/ThirdPartyCollectionDetailPage/CollectionPublishButton/CollectionPublishButton.types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: Add logic to block publish button when are exceeding max slots

---

src/components/ThirdPartyCollectionDetailPage/CollectionContextMenu/CollectionContextMenu.tsx
src/modules/translation/languages/en.json

feat: Add Forum link to TP collections

---

src/components/ItemEditorPage/RightPanel/RightPanel.container.ts
src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/components/ItemEditorPage/RightPanel/RightPanel.types.ts
src/modules/collection/selectors.spec.ts
src/modules/collection/selectors.ts

fix: Allow TP manager to edit TP items

---

src/lib/api/builder.ts

fix: Download cached wearable

---

src/components/Modals/CreateMultipleItemsModal/CreateMultipleItemsModal.tsx
src/lib/urn.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: Add check for a valid URN in asset.json when uploading files

---

src/components/CollectionImage/CollectionImage.container.ts
src/components/CollectionImage/CollectionImage.tsx
src/components/CollectionImage/CollectionImage.types.ts
src/lib/api/pagination.ts

Fetches the images needed in they weren't fetched before:

feat: Add logic to fetch collection items for images if needed

---

src/lib/api/builder.ts
src/modules/curations/itemCuration/actions.ts
src/modules/curations/itemCuration/reducer.spec.ts
src/modules/curations/itemCuration/reducer.ts
src/modules/curations/itemCuration/sagas.spec.ts
src/modules/curations/itemCuration/sagas.ts
src/modules/item/actions.ts
src/modules/item/sagas.spec.ts
src/modules/item/sagas.ts

fix: Update item curation on item save

---

src/modules/item/reducer.ts
src/modules/item/sagas.ts

fix: Add default pagination data when the collection has no items

---

src/components/Modals/EditCurationAssigneeModal/EditCurationAssigneeModal.container.ts
src/components/Modals/EditCurationAssigneeModal/EditCurationAssigneeModal.tsx
src/components/Modals/EditCurationAssigneeModal/EditCurationAssigneeModal.types.ts

Closes #2000
https://user-images.githubusercontent.com/8763687/165789407-af5fedac-ec1c-452d-9528-8c259a76c904.mov

fix: Removes Profile JSX for text so the user can autocomplete

---

src/components/CurationPage/CollectionRow/CollectionRow.tsx
src/components/ItemEditorPage/TopPanel/ConfirmApprovalModal/ConfirmApprovalModal.css
src/components/ItemEditorPage/TopPanel/ConfirmApprovalModal/ConfirmApprovalModal.tsx
src/components/ItemEditorPage/TopPanel/ConfirmApprovalModal/ConfirmApprovalModal.types.ts
src/components/ItemEditorPage/TopPanel/ConfirmApprovalModal/index.ts
src/components/ItemEditorPage/TopPanel/TopPanel.container.ts
src/components/ItemEditorPage/TopPanel/TopPanel.tsx
src/components/ItemEditorPage/TopPanel/TopPanel.types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: Show confirmation modal if the curator is not the assignee

---

src/components/Modals/EditCurationAssigneeModal/EditCurationAssigneeModal.tsx
src/modules/curations/collectionCuration/utils.ts

fix: Error when the curator has no profile data

---

src/components/CurationPage/CurationPage.tsx

feat: Sorts the assignees list

---

src/modules/item/sagas.spec.ts
src/modules/item/sagas.ts

feat: Redirect to item detail when creating an orphan one

---

src/components/Modals/CreateAndEditMultipleItemsModal/CreateAndEditMultipleItemsModal.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

This PR generates the thumbnails of the items that don't include one when uploading multiple items.

fix: Generate thumbnail if it doesn't exist

---

package-lock.json
package.json

chore: bump dcl-dapps

---

src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/modules/item/utils.ts

fix: If the item is hidding body shape show it so it can be removed

---

src/components/ItemEditorPage/ItemEditorPage.tsx
src/components/ItemEditorPage/ItemEditorPage.types.ts
src/components/ItemEditorPage/LeftPanel/Items/Items.css
src/components/ItemEditorPage/LeftPanel/Items/Items.tsx
src/components/ItemEditorPage/LeftPanel/Items/Items.types.ts
src/components/ItemEditorPage/LeftPanel/Items/SidebarItem/SidebarItem.css
src/components/ItemEditorPage/LeftPanel/LeftPanel.container.ts
src/components/ItemEditorPage/LeftPanel/LeftPanel.css
src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx
src/components/ItemEditorPage/LeftPanel/LeftPanel.types.ts
src/components/ItemEditorPage/TopPanel/TopPanel.container.ts
src/components/ItemEditorPage/TopPanel/TopPanel.css
src/components/ItemEditorPage/TopPanel/TopPanel.tsx
src/components/ItemEditorPage/TopPanel/TopPanel.types.ts
src/components/ItemEditorPage/constants.ts
src/modules/item/selectors.spec.ts
src/modules/item/selectors.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Closes #2065
https://user-images.githubusercontent.com/8763687/169021367-d596ac20-8925-422a-98ed-1e28d2ad27f9.mov

feat: Add Get Random Sample to TP items review flow

---

src/components/Modals/CreateAndEditMultipleItemsModal/CreateAndEditMultipleItemsModal.tsx
src/components/Modals/CreateAndEditMultipleItemsModal/CreateAndEditMultipleItemsModal.types.ts
src/modules/item/sagas.ts

Closes #2071
For a batch of 500 zip files (405,6 MB) it took:
- `6:32` minutes to process the files and generate the thumbnails
- `8:17` minutes to deploy the 500 files to the catalyst

feat: Add pqueue to the multiple upload process

---

package-lock.json
package.json
src/components/Modals/CreateAndEditMultipleItemsModal/CreateAndEditMultipleItemsModal.tsx

This feature replaces the old `asset.json` file with the new `wearable.json` file.
Closes #2089

feat: Add support for the wearable.json file

---

package-lock.json
package.json
src/components/CollectionImage/CollectionImage.container.ts
src/components/CollectionProvider/CollectionProvider.container.ts
src/components/CollectionProvider/CollectionProvider.tsx
src/components/CollectionProvider/CollectionProvider.types.ts
src/components/ItemEditorPage/LeftPanel/Collections/Collections.css
src/components/ItemEditorPage/LeftPanel/Collections/Collections.tsx
src/components/ItemEditorPage/LeftPanel/Collections/Collections.types.ts
src/components/ItemEditorPage/LeftPanel/Collections/SidebarCollection/SidebarCollection.css
src/components/ItemEditorPage/LeftPanel/Items/Items.tsx
src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx

feat: Paginates the collection list and removes the virtualized one

---

src/components/CollectionsPage/CollectionsPage.tsx

Closes #2099 
Closes #2100 
Closes #2101

fix: Collections pagination page issue

---

src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx

fix: filter the published items when reviewing a tp collection

---

src/components/ItemProvider/ItemProvider.tsx
src/components/ItemProvider/ItemProvider.types.ts

This PR makes the `ItemProvider` component load the item once.
Closes #2120

fix: Item provider loading items multiple times

---

src/modules/collection/reducer.spec.ts
src/modules/collection/reducer.ts

Clear error from redux after closing the modal. Otherwise when an error happens you can't publish again until reloading.

fix: clear error

---

src/components/ItemDetailPage/ItemDetailPage.tsx

Closes #2109
https://user-images.githubusercontent.com/8763687/171808266-547413c7-939b-4d3a-b6dc-4cf930c98d66.mov
https://user-images.githubusercontent.com/8763687/171808278-ed045762-03a9-43ff-af65-7b8dfb5e6f08.mov

fix: item detail back navigation

---

src/components/Preview/Preview.tsx

Prefix with `PUBLIC_URL` so it works in the CDN

fix: prefix unity config with public url

---

src/components/Modals/PublishCollectionModalWithOracle/PublishCollectionModal.tsx

Closes https://github.com/decentraland/builder/issues/2178

feat: Properly formated mana and usd prices in publish modal

---

src/modules/thirdParty/sagas.spec.ts
src/modules/thirdParty/sagas.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: Show Error Toast when a TP action fails

---

src/components/Modals/PublishCollectionModalWithOracle/PublishCollectionModal.tsx

Closes https://github.com/decentraland/builder/issues/2179

feat: Show error when fetching rarities fails

---

src/lib/getModelData.ts

This PR updates the wearable materials count strategy to have a more accurate number of materials.
Closes: #2187

fix: Update wearable materials count strategy

---

src/components/CollectionProvider/CollectionProvider.tsx
src/components/CollectionProvider/CollectionProvider.types.ts
src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx
src/components/ThirdPartyCollectionDetailPage/CollectionItem/CollectionItem.container.ts
src/components/ThirdPartyCollectionDetailPage/CollectionItem/CollectionItem.module.css
src/components/ThirdPartyCollectionDetailPage/CollectionItem/CollectionItem.tsx
src/components/ThirdPartyCollectionDetailPage/CollectionItem/CollectionItem.types.ts
src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.css
src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.tsx
src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.types.ts
src/lib/api/builder.ts
src/modules/item/actions.ts
src/modules/item/sagas.spec.ts
src/modules/item/sagas.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Closes #2140
Demo:
https://user-images.githubusercontent.com/8763687/178472807-642f0a23-a9eb-4a9b-a698-9c2f94b22975.mov
**UPDATED**

feat: Add Synced filter to the TP Collection Page

---

src/modules/collection/sagas.ts
src/modules/features/selectors.ts
src/modules/features/types.ts
src/modules/item/selectors.ts
src/modules/item/utils.ts

feat: introduces a new FF for emotes and wraps the breaking change code

---

src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.types.ts
src/components/Modals/CreateSingleItemModal/utils.ts
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.css

feat: Use the Wearable Preview for Wearable screenshots

---

src/modules/item/sagas.spec.ts
src/modules/item/sagas.ts

Fix: Close create single item modal

---

src/components/CollectionDetailPage/CollectionDetailPage.container.ts
src/components/CollectionDetailPage/CollectionDetailPage.css
src/components/CollectionDetailPage/CollectionDetailPage.tsx
src/components/CollectionDetailPage/CollectionDetailPage.types.ts
src/components/CollectionDetailPage/CollectionItem/CollectionItem.module.css
src/components/CollectionDetailPage/CollectionItem/CollectionItem.tsx
src/components/ItemBadge/ItemBadge.tsx
src/components/ItemBadge/ItemBadge.types.ts
src/components/RarityBadge/RarityBadge.module.css
src/components/RarityBadge/RarityBadge.tsx
src/components/RarityBadge/RarityBadge.types.ts
src/components/RarityBadge/index.ts
src/modules/item/types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json
src/routing/locations.ts
src/routing/utils.ts

feat: Add Emotes/Wearables tabs in the collection detail page

---

src/modules/translation/languages/en.json

chore: fix copy

---

src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.types.ts
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.css
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.tsx
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.types.ts

This PR fixes the fields resetting values when toggling the checkboxes and updates some styles.
Closes #2248
Closes #2249

Fix: EditPriceAndBeneficiaryModal

---

src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: disable beneficiary checkbox when item is free

---

src/components/CollectionDetailPage/CollectionPublishButton/CollectionPublishButton.container.ts
src/components/CollectionDetailPage/CollectionPublishButton/CollectionPublishButton.tsx
src/components/CollectionDetailPage/CollectionPublishButton/CollectionPublishButton.types.ts
src/modules/features/selectors.ts
src/modules/features/types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: Block publish button for emotes

---

src/modules/ens/sagas.ts

chore: Rename ens sagas function

---

src/modules/item/export.ts

Fix emote category when deploying

fix: emote category

---

src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx

This PR fixes update the thumbnail in emotes flow.

fix: Update thumbnail

---

src/components/Modals/EditThumbnailModal/EditThumbnailModal.tsx

fix: Close the edit thumbnail modal when clicking on the back button

---

src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.container.ts
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.types.ts
src/components/Modals/CreateSingleItemModal/EditThumbnailStep/EditThumbnailStep.tsx
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.css
src/lib/getModelData.ts

Closes several issues reported

feat: Modify Learn More link for Emotes and removes canvas

---

src/components/ItemEditorPage/CenterPanel/CenterPanel.tsx
src/modules/editor/actions.ts
src/modules/editor/sagas.ts

This PR sets the avatar to IDLE when pressing the stop button.
Closes #2289

fix: Stop emote animation when pressing button stop

---

src/modules/item/types.ts

Reverts decentraland/builder#2320

Revert "fix: Allow push changes when some item couldn't be uploaded to the content server"

---

src/modules/item/utils.ts

Reverts decentraland/builder#2330

Revert "fix: remove emote from metadata until graph has new change"

---

src/components/EventBanner/EventBanner.css
src/components/EventBanner/EventBanner.tsx
src/modules/features/types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: Update mvmf event FF and banner text

---

src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.types.ts

fix: Skip the set thumbnail step if the user has already taken a screenshot in the details step

---

src/components/Modals/CreateSingleItemModal/ImportStep/ImportStep.tsx

This PR fixes the error when trying to upload a wearable using png files.
https://user-images.githubusercontent.com/3170051/197005974-6e9b778e-7959-49a0-a4b3-461b35605c6f.mp4
Closes #2375

fix: Upload wearables using png files

---

src/modules/item/errors.ts
src/modules/item/export.ts
src/modules/item/sagas.spec.ts
src/modules/item/sagas.ts
src/modules/item/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

This PR updates the max item size calculation, computing the model's contents and thumbnails with different limits.
Closes #2382

fix: Update calculation of the max item size

---

src/components/Modals/PublishWizardCollectionModal/PublishWizardCollectionModal.tsx
src/components/Modals/PublishWizardCollectionModal/ReviewContentPolicyStep/ReviewContentPolicyStep.css
src/components/Modals/PublishWizardCollectionModal/ReviewContentPolicyStep/ReviewContentPolicyStep.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

This PR adds the review content policy step.
Closes #2202

feat: new publish wizard review content policy step

---

src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/components/ItemImage/ItemImage.tsx
src/components/Modals/ApprovalFlowModal/ApprovalFlowModal.tsx
src/components/Modals/ManageCollectionRoleModal/ManageCollectionRoleModal.tsx
src/lib/api/auth.ts
src/lib/number.ts
src/modules/land/utils.ts
src/routing/locations.ts

This PR fixes the eslint restrict-plus-operands rule

fix: eslint restrict-plus-operands rule

---

src/components/ClaimENSPage/ClaimENSPage.tsx
src/components/Modals/ContestModal/ContestModal.tsx
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
src/components/Modals/EditAssetPackModal/EditAssetPackModal.tsx

This PR fixes the eslint require-await rule

fix: eslint require-await rule

---

src/lib/api/builder.ts

This PR updates the `builder api` returns types

fix: eslint builder api

---

package.json
src/components/CollectionDetailPage/CollectionDetailPage.tsx
src/components/CurationPage/CurationPage.css
src/components/CurationPage/CurationPage.tsx
src/components/CurationPage/CurationPage.types.ts
src/lib/api/builder.ts
src/modules/collection/sagas.ts
src/modules/collection/selectors.ts
src/modules/collection/types.ts
src/modules/collection/utils.spec.ts
src/modules/collection/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json
src/routing/locations.ts

feat: Add filter by type in the curation page

---

src/components/Modals/MintItemsModal/MintItemsModal.css
src/components/Modals/MintItemsModal/MintItemsModal.tsx
src/components/Modals/MintItemsModal/MintItemsModal.types.ts
src/components/Modals/MintItemsModal/MintableItem/MintableItem.css
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: create a confirmation modal on mint items from collection

---

src/components/HomePage/HomePage.container.ts
src/components/HomePage/HomePage.css
src/components/HomePage/HomePage.tsx
src/components/HomePage/HomePage.types.ts
src/components/Navigation/Navigation.tsx
src/components/Navigation/Navigation.types.ts
src/components/ProjectCard/ProjectCard.css
src/components/ProjectCard/ProjectCard.tsx
src/components/ScenesPage/ScenesPage.container.ts
src/components/ScenesPage/ScenesPage.css
src/components/ScenesPage/ScenesPage.tsx
src/components/ScenesPage/ScenesPage.types.ts
src/components/ScenesPage/index.ts
src/images/home-page-collections.svg
src/images/home-page-land.svg
src/images/home-page-names.svg
src/images/home-page-scenes.svg
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json
src/routing/Routes.tsx
src/routing/locations.ts
src/themes/theme.css

This PR renames the current `homepage screen` to `scenes screen` and creates a new homepage overview.
Closes #2345

feat: Update builder homepage screen

---

src/modules/collection/sagas.spec.ts
src/modules/collection/sagas.ts

This PR finishes the collection publishing when some items are missing the tokenId.
Closes #2446

fix: Finish collection publishing

---

package-lock.json
package.json
src/components/Intercom/Intercom.tsx
src/components/Intercom/index.ts
src/routing/Routes.tsx

This PR sends the segment `anonymousId ` to the intercom interface.

feat: Send segment userid to intercom

---

src/components/Intercom/Intercom.tsx

This PR updates the intercom field to store the user segment id.

feat: Update segment id field to send to intercom

---

src/components/CollectionsPage/CollectionsPage.container.ts
src/components/CollectionsPage/CollectionsPage.tsx
src/components/CollectionsPage/CollectionsPage.types.ts
src/components/CurationPage/CurationPage.container.ts
src/components/CurationPage/CurationPage.tsx
src/components/CurationPage/CurationPage.types.ts
src/modules/features/selectors.ts
src/modules/features/types.ts

Remove collections sort feature flag

feat: remove feature flag collections sort

---

src/components/CollectionsPage/CollectionRow/CollectionRow.tsx
src/components/CollectionsPage/CollectionsPage.tsx
src/components/CollectionsPage/ItemRow/ItemRow.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json
src/routing/Routes.tsx

Add last updated and created column in collections list view
Closes #2465

feat: add created and last modified column in collections list

---

src/lib/api/builder.spec.ts
src/lib/api/builder.ts

fix: Await super request response instead of returning the promise

---

src/components/Modals/UseAsAliasModal/UseAsAliasModal.container.ts
src/components/Modals/UseAsAliasModal/UseAsAliasModal.tsx
src/components/Modals/UseAsAliasModal/UseAsAliasModal.types.ts
src/modules/profile/selectors.ts

fix: add "hasClaimedName" to the alias success check

---

src/components/ConfirmDelete/ConfirmDelete.tsx
src/components/ItemDetailPage/ItemDetailPage.tsx
src/modules/collection/sagas.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: add move to collection option in detail page

---

src/components/ENSListPage/ENSListPage.container.ts
src/components/ENSListPage/ENSListPage.tsx
src/components/ENSListPage/ENSListPage.types.ts
src/components/LoggedInDetailPage/LoggedInDetailPage.container.ts
src/components/LoggedInDetailPage/LoggedInDetailPage.tsx
src/components/LoggedInDetailPage/LoggedInDetailPage.types.ts
src/modules/land/reducer.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

This PR adds an error message when loading names fails.

feat: Add error message when loading names

---

src/components/Modals/UseAsAliasModal/UseAsAliasModal.container.ts
src/components/Modals/UseAsAliasModal/UseAsAliasModal.tsx
src/components/Modals/UseAsAliasModal/UseAsAliasModal.types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: show error if the alias deployment fails

---

src/modules/ens/sagas.ts

fix: Use PQueue for fetching the ENS associated to each domain

---

smart-items.md

Fix: typos
Signed-off-by: omahs <73983677+omahs@users.noreply.github.com>

Fix: typos

---

src/components/Preview/Preview.tsx
src/modules/editor/sagas.ts
src/modules/editor/utils.ts

This PR fixes loading unity scripts for scenes when creating a new Scene.

fix: Lazy loading unity scripts for scenes

---

src/lib/api/builder.ts
src/modules/item/sagas.ts

This PR fixes publishing collection retry. The request error did not contain the error code, and the retry method was not triggered.

fix: Publish collection retry

---

src/config/env/dev.json
src/config/env/prod.json
src/config/env/stg.json

Using a new lambda for mail subscription

feat: change subscribe endpoint

---

src/modules/features/selectors.spec.ts
src/modules/features/selectors.ts
src/modules/features/types.ts

Add ff for deploy to worlds from builder feature

feat: add ff for deploy to worlds

---

src/components/Modals/DeployModal/DeployModal.container.ts
src/components/Modals/DeployModal/DeployModal.css
src/components/Modals/DeployModal/DeployModal.tsx
src/components/Modals/DeployModal/DeployModal.types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Add new deploy to world option in publish scene modal
Closes #2580 
(This is under a feature flag)

feat: publish scene modal update

---

src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.tsx

fix: Don't show price is too low when the price is actually the min value

---

src/lib/api/builder.ts
src/modules/common/utils.ts

This PR enables a retry mechanism for the builder-api.
Depends on: https://github.com/decentraland/decentraland-dapps/pull/410

feat: Add retry logic to the builder-api fetches

---

src/modules/asset/utils.ts
src/modules/template/utils.ts

This PR increases the max size of scenes created in the Builder to support 20x20 scenes. It also increases the max size for files from 10mb to 25mb.

feat: lift parcel limit

---

src/components/Icon/sprite.css
src/components/Modals/DeployModal/DeployToWorld/DeployToWorld.container.ts
src/components/Modals/DeployModal/DeployToWorld/DeployToWorld.module.css
src/components/Modals/DeployModal/DeployToWorld/DeployToWorld.tsx
src/components/Modals/DeployModal/DeployToWorld/DeployToWorld.types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

This PR shows scene metrics in the Deploy World Modal thumbnail.
Closes #2582
Depends on: #2620

feat: Show world scene metrics

---

src/components/Modals/DeployModal/DeployToWorld/DeployToWorld.module.css
src/components/Modals/DeployModal/DeployToWorld/DeployToWorld.tsx

Redirect to scene page when closing "Deploy to Worlds" success page instead of the editor

feat: redirect scene page success

---

src/components/WorldListPage/WorldListPage.container.ts
src/components/WorldListPage/WorldListPage.css
src/components/WorldListPage/WorldListPage.tsx
src/components/WorldListPage/WorldListPage.types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
vercel.json

This PR fixes the empty world list alignment text and validates a valid project for each world before showing the edit scene button.

fix: Worlds list

---

src/components/Modals/DeployModal/DeployToLand/DeployToLand.tsx
src/components/Modals/ImportModal/ImportModal.tsx

- Only consider land deployments when deploying to land
- Remove debugger

fix: deploy to land 0,0

---

src/components/ProjectCard/ProjectCard.css
src/components/SceneListPage/PoolCard/PoolCard.tsx
src/components/ScenesPage/ScenesPage.css
src/components/ScenesPage/ScenesPage.tsx
src/themes/theme.css

Fix scenes page layout so its responsive
https://github.com/decentraland/builder/assets/11800206/ca3a1324-d7af-45a2-ad15-bee233b589d1

fix: cards layout on scenes page

---

src/components/SceneDetailPage/DeploymentDetail/DeploymentDetail.css
src/components/SceneDetailPage/DeploymentDetail/DeploymentDetail.tsx
src/components/SceneStats/Stats/Stats.css

This PR updates the scene details to show the deployment location(`land|world`).

feat: Update scene details

---

src/components/Modals/DeployToWorldAnnouncementModal/DeployToWorldAnnouncementModal.container.ts
src/components/Modals/DeployToWorldAnnouncementModal/DeployToWorldAnnouncementModal.css
src/components/Modals/DeployToWorldAnnouncementModal/DeployToWorldAnnouncementModal.tsx
src/components/Modals/DeployToWorldAnnouncementModal/DeployToWorldAnnouncementModal.types.ts
src/components/Modals/DeployToWorldAnnouncementModal/index.ts
src/components/Modals/index.ts
src/components/ScenesPage/ScenesPage.container.ts
src/components/ScenesPage/ScenesPage.tsx
src/components/ScenesPage/ScenesPage.types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

This PR adds the Deploy to Worlds announcing modal.
Closes #2594

feat: Launch announcing modal

---

src/components/Modals/DeployModal/DeployToWorld/DeployToWorld.tsx

This PR adds analytics to Deploy to Worlds.
Closes #2595

feat: Add analytics to Deploy to Worlds

---

src/lib/api/builder.ts
src/modules/deployment/sagas.ts

This PR fixes unpublish scenes error.

fix: Clear deployments

---

src/components/Modals/DeployModal/DeployToLand/utils.ts
src/modules/project/export.ts

This PR fixes the creation of the thumbnail when clearing a deployment.

Fix: Create clear deployment thumbnail

---

src/components/ScenesPage/ScenesPage.css
src/components/ScenesPage/ScenesPage.tsx

This PR adds the requirement to be logged in before interacting with scenes.

feat: Require login in the ScenesPage

---

src/components/Modals/TemplatesAnnouncementModal/TemplatesAnnouncementModal.module.css
src/components/Modals/TemplatesAnnouncementModal/TemplatesAnnouncementModal.tsx
src/components/ScenesPage/ScenesPage.tsx

fix: ftu modal

---

src/components/Modals/ImportModal/ImportModal.css
src/components/SceneViewPage/SceneViewPage.tsx
src/components/SceneViewPage/utils.ts
src/components/ScenesPage/ScenesPage.tsx
src/modules/deployment/sagas.ts
src/modules/project/sagas.ts
src/modules/scene/reducer.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Fix several issues in tempaltes

fix: templates download

---

src/modules/project/selectors.ts

fixes: https://drive.google.com/file/d/1hY03fkVz8gilh--ifbIzcy-s6-Zigy-a/view

fix: wait till projects loads to display scenes page

---

src/components/SceneCard/SceneCard.tsx
src/components/TemplateDetailPage/TemplateDetailPage.css
src/components/TemplateDetailPage/TemplateDetailPage.tsx
src/lib/video.ts

Add template video to detail page on hover

feat: add video to template detail page

---

src/components/SceneDetailPage/SceneDetailPage.css
src/components/TemplateDetailPage/TemplateDetailPage.css
src/components/TemplateDetailPage/TemplateDetailPage.tsx
src/modules/project/sagas.ts
src/modules/project/utils.ts

This PR fixes fetch the template thumbnail from the public folder when creating a new project from the template.

fix: Fetch templates thumbnail video

---

src/components/EditorPage/EditorPage.container.ts
src/components/EditorPage/EditorPage.tsx
src/components/EditorPage/EditorPage.types.ts
src/modules/project/sagas.ts
src/modules/project/utils.ts

This PR fixes the save thumbnail error when duplicating projects.

fix: Duplicate project save thumbnail

---

package-lock.json
package.json
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.types.ts
src/components/Modals/CreateSingleItemModal/ImportStep/ImportStep.tsx
src/modules/item/types.ts

feat: Detect smart wearables data in the CreateSingleItemModal

---

package-lock.json
package.json

This PR upgrades the decentraland-dapps package with places submenu in navbar

feat: update dapps v15.3.0 with places submenu in navbar

---

src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx

This PR fixes SW scenes path content

fix: SW scenes path

---

src/components/ItemEditorPage/RightPanel/RightPanel.tsx

This PR fixes show the override panel when selecting emotes

fix: Set hides to wearables

---

src/components/Modals/CreateSingleItemModal/UploadVideoStep/UploadVideoStep.module.css
src/components/Modals/CreateSingleItemModal/UploadVideoStep/UploadVideoStep.tsx
src/components/Modals/CreateSingleItemModal/UploadVideoStep/UploadVideoStep.types.ts
src/modules/item/errors.ts
src/modules/item/sagas.spec.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Enhance errors related to the upload video process

feat: Enhance upload video errors adding title and description

---

src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx

Add removesDefaultHiding property for wearable edition

fix: add removesDefaultHiding for item edition

---

src/lib/api/builder.ts
src/lib/api/transformations.ts
src/modules/item/types.ts

feat: Start tracking if items are smart

---

src/modules/curations/collectionCuration/sagas.ts
src/modules/curations/itemCuration/sagas.ts

This PR removes the put effect from the testing library and uses the put effect from the sagas one in production code.

fix: Use redux-sagas effects

---

src/components/CollectionDetailPage/CollectionDetailPage.tsx
src/components/ItemEditorPage/RightPanel/RightPanel.css
src/components/ItemEditorPage/TopPanel/TopPanel.tsx
src/components/JumpIn/JumpIn.css
src/components/JumpIn/JumpIn.tsx
src/components/JumpIn/JumpIn.types.ts
src/modules/deployment/contentUtils.ts
src/modules/item/export.ts
src/modules/item/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

This PR avoids sending the SW video to the content server and computing the hash content.

fix: Upload SW entities

---

package-lock.json
package.json
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.css
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Wait for https://github.com/decentraland/ui/pull/390 before merging this PR.

fix: Learn more next to fields headers

---

src/components/CollectionDetailPage/CollectionDetailPage.tsx
src/components/CollectionDetailPage/CollectionItem/CollectionItem.tsx
src/components/ThirdPartyCollectionDetailPage/CollectionItem/CollectionItem.module.css

feat: Keep collection item more options always visible

---

package-lock.json
package.json
src/__mocks__/node:crypto.ts
src/lib/api/builder.ts
src/modules/common/sagas.ts
src/modules/inspector/sagas.ts

This PR allows for the upload of assets to the Builder server, it is necessary not only for importing custom assets, but or using Builder assets from the catalog.
It needs this PR to be merged first: https://github.com/decentraland/builder-server/pull/685

feat: upload assets

---

src/components/ItemImport/ErrorMessage/ErrorMessage.module.css
src/components/ItemImport/ErrorMessage/ErrorMessage.tsx
src/components/ItemImport/ErrorMessage/ErrorMessage.types.ts
src/components/ItemImport/ErrorMessage/index.ts
src/components/ItemImport/ItemImport.module.css
src/components/ItemImport/ItemImport.tsx
src/components/Modals/CreateSingleItemModal/UploadVideoStep/UploadVideoStep.module.css
src/components/Modals/CreateSingleItemModal/UploadVideoStep/UploadVideoStep.tsx

This PR refactorizes the error message component when uploading a file.

feat: Refactor error message

---

src/components/CollectionProvider/CollectionProvider.tsx
src/components/ItemEditorPage/LeftPanel/Collections/SidebarCollection/SidebarCollection.tsx
src/components/ItemEditorPage/LeftPanel/LeftPanel.container.ts
src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx
src/components/ItemEditorPage/LeftPanel/LeftPanel.types.ts
src/modules/collection/utils.ts
src/modules/item/utils.spec.ts
src/modules/item/utils.ts
src/modules/location/selectors.spec.ts
src/modules/location/selectors.ts

This PR preselects items in the LeftPanel when entering the ItemEditor.
https://github.com/decentraland/builder/assets/3170051/856107ea-3db4-48b6-9020-b35474978d12

feat: Preselect items left panel

---

package-lock.json
package.json
src/components/ItemImport/ErrorMessage/ErrorMessage.module.css
src/components/ItemImport/ErrorMessage/ErrorMessage.tsx
src/components/ItemImport/ItemImport.types.ts
src/components/Modals/CreateSingleItemModal/ImportStep/ImportStep.tsx
src/components/Modals/CreateSingleItemModal/ImportStep/ImportStep.types.ts
src/modules/item/errors.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Closes #2802 
Wait until https://github.com/decentraland/builder-client/pull/60 is merged.

feat: Show WK error messages when uploading Smart Wearables

---

src/components/SceneViewPage/SceneViewPage.container.ts
src/components/SceneViewPage/SceneViewPage.css
src/components/SceneViewPage/SceneViewPage.tsx
src/components/SceneViewPage/SceneViewPage.types.ts
src/config/env/dev.json
src/config/env/prod.json
src/config/env/stg.json
src/modules/common/sagas.ts
src/modules/features/selectors.spec.ts
src/modules/features/selectors.ts
src/modules/features/types.ts

This PR updates the SceneView author element to redirect to the profile dApp when the FF: `dapps-profile` is enabled.
Closes https://github.com/decentraland/profile/issues/74

feat: Add profile dApp redirection

---

src/lib/api/builder.ts
src/modules/common/sagas.ts
src/modules/inspector/sagas.ts
src/modules/inspector/utils.ts
src/modules/scene/sagas.ts

Save crdt file on change and when project is migrated from sdk6 to sdk7. This file will be used on the preview feature

feat: save crdt file

---

src/components/InspectorPage/TopBar/TopBar.tsx
src/components/Modals/DeployModal/DeployModal.container.ts
src/components/Modals/DeployModal/DeployModal.tsx
src/components/Modals/DeployModal/DeployModal.types.ts
src/components/Modals/DeployModal/DeployToLand/DeployToLand.tsx
src/components/Modals/DeployModal/DeployToLand/DeployToLand.types.ts
src/components/Modals/DeployModal/DeployToLand/LandAtlas/LandAtlas.tsx
src/components/Modals/DeployModal/DeployToLand/LandAtlas/LandAtlas.types.ts
src/lib/api/builder.ts
src/modules/deployment/sagas.ts
src/modules/deployment/types.ts
src/modules/deployment/utils.ts
src/modules/media/sagas.ts

This PR adds support to publish SDK7 scenes to LAND and to Worlds

feat: publish SDK7 scenes

---

src/components/InspectorPage/TopBar/TopBar.tsx
src/components/ProjectCard/ProjectCard.tsx
src/components/SceneDetailPage/SceneDetailPage.tsx

Remove download button for sdk7 scenes until the feature is available

feat: remove download from sdk7 scenes

---

src/components/ItemEditorPage/RightPanel/RightPanel.css

fix: Rigth Panel flex with growing items

---

src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/components/ItemVideo/ItemVideo.tsx
src/components/Modals/EditVideoModal/EditVideoModal.tsx
src/components/Modals/EditVideoModal/EditVideoModal.types.ts
src/modules/item/utils.spec.ts
src/modules/item/utils.ts

Curators can't watch Smart Wearables video when curating them.

fix: Allow curators to watch video showcase

---

src/components/InspectorPage/InspectorPage.css
src/modules/inspector/utils.ts

- Fix creation of rectangular scenes
- Make inspector fix width

fix: sdk7 scene creation

---

.eslintrc.json
public/config/hotjar.js
public/index.html

Add hotjar configuration to incude feedback form in inspector page

feat: add hotjar config

---

src/components/ItemDetailPage/ItemDetailPage.container.ts
src/components/ItemDetailPage/ItemDetailPage.tsx
src/components/ItemDetailPage/ItemDetailPage.types.ts
src/components/ItemEditorPage/RightPanel/RightPanel.container.ts
src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/components/ItemEditorPage/RightPanel/RightPanel.types.ts
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.container.ts
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.types.ts
src/components/Modals/CreateSingleItemModal/ImportStep/ImportStep.tsx
src/components/Modals/CreateSingleItemModal/ImportStep/ImportStep.types.ts
src/components/Modals/EditThumbnailModal/EditThumbnailModal.tsx
src/components/Modals/EditThumbnailModal/EditThumbnailModal.types.ts
src/modules/item/errors.ts
src/modules/item/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

This PR updates the SW status when a new video is uploaded.
Depends on: https://github.com/decentraland/builder-server/pull/696

fix: Update SW status when video is updated

---

src/modules/item/selectors.spec.ts
src/modules/item/selectors.ts
src/modules/item/utils.ts

This PR fixes TP Collections push changes logic

fix: TP Push Changes logic

---

src/config/env/dev.json
src/config/env/prod.json
src/config/env/stg.json
src/lib/api/lists.ts
src/lib/api/marketplace.ts
src/lib/api/worlds.ts
src/modules/ens/sagas.spec.ts
src/modules/ens/sagas.ts

feat: do not show banned ENS in names section

---

src/components/Modals/PublishWizardCollectionModal/PublishWizardCollectionModal.container.ts
src/components/Modals/PublishWizardCollectionModal/PublishWizardCollectionModal.tsx
src/components/Modals/PublishWizardCollectionModal/ReviewContentPolicyStep/ReviewContentPolicyStep.css
src/components/Modals/PublishWizardCollectionModal/ReviewContentPolicyStep/ReviewContentPolicyStep.tsx
src/components/Modals/PublishWizardCollectionModal/ReviewContentPolicyStep/ReviewContentPolicyStep.types.ts
src/lib/api/builder.ts
src/modules/collection/actions.ts
src/modules/collection/sagas.spec.ts
src/modules/collection/sagas.ts
src/modules/common/sagas.ts
src/modules/newsletter/action.spec.ts
src/modules/newsletter/action.ts
src/modules/newsletter/sagas.spec.ts
src/modules/newsletter/sagas.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

feat: add newsletter subscription checkbox when submitting collections

---

src/components/InspectorPage/InspectorPage.container.ts
src/components/InspectorPage/InspectorPage.tsx
src/components/InspectorPage/InspectorPage.types.ts
src/components/Modals/CustomLayoutModal/CustomLayoutModal.container.ts
src/components/Modals/CustomLayoutModal/CustomLayoutModal.tsx
src/components/Modals/CustomLayoutModal/CustomLayoutModal.types.ts
src/components/ProjectCard/ProjectCard.container.ts
src/components/ProjectCard/ProjectCard.tsx
src/components/ProjectCard/ProjectCard.types.ts
src/components/SceneDetailPage/SceneDetailPage.container.ts
src/components/SceneDetailPage/SceneDetailPage.tsx
src/components/SceneDetailPage/SceneDetailPage.types.ts
src/components/SceneViewPage/SceneViewPage.container.ts
src/components/SceneViewPage/SceneViewPage.tsx
src/components/SceneViewPage/SceneViewPage.types.ts
src/components/TemplateDetailPage/TemplateDetailPage.container.ts
src/components/TemplateDetailPage/TemplateDetailPage.tsx
src/components/TemplateDetailPage/TemplateDetailPage.types.ts
src/modules/features/selectors.ts
src/modules/features/types.ts

Remove now deprecated `WEB_EDITOR` feature flag, and add new `SMART_ITEMS` feature flag

chore: smart items feature flag

---

src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.container.ts
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.tsx
src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.types.ts

This PR fixes showing the errors when saving items in the EditPriceAndBeneficiaryModal.

fix: Show errors when saving items in the EditPriceAndBeneficiaryModal

---

package-lock.json
package.json

This includes the `@dcl/inspector` with support for states and trigger conditions

feat: upgrade sdk

---

package-lock.json
package.json

feat: upgrade sdk to v7.3.15

---

package-lock.json
package.json

upgrade `@dcl/sdk` to `@next` version

feat: upgrade @dcl/sdk to @next version

---

src/config/env/dev.json
src/config/env/prod.json
src/config/env/stg.json
src/modules/common/sagas.ts
src/modules/common/store.ts
src/modules/ens/actions.spec.ts
src/modules/ens/actions.ts
src/modules/ens/reducer.spec.ts
src/modules/ens/reducer.ts
src/modules/ens/sagas.spec.ts
src/modules/ens/sagas.ts

feat: Add saga to fetch external ens names

---

src/modules/ens/actions.spec.ts
src/modules/ens/actions.ts
src/modules/ens/reducer.spec.ts
src/modules/ens/reducer.ts
src/modules/ens/sagas.spec.ts
src/modules/ens/sagas.ts
src/modules/ens/selectors.spec.ts
src/modules/ens/selectors.ts

Also renames actions to normalize throughout the feature

feat: Use wallet address if owner is not provided

---

package-lock.json
package.json
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.types.ts
src/components/Modals/CreateSingleItemModal/ImportStep/ImportStep.tsx
src/components/Modals/EmotesV2AnnouncementModal/EmotesV2AnnouncementModal.tsx

Add missing field from `emote.json` file to item creation flow and update ui and client dependencies

fix: item creation

---

src/lib/api/worlds.spec.ts
src/lib/api/worlds.ts
src/modules/common/reducer.ts
src/modules/common/types.ts
src/modules/worlds/actions.spec.ts
src/modules/worlds/actions.ts
src/modules/worlds/reducer.spec.ts
src/modules/worlds/reducer.ts
src/modules/worlds/sagas.spec.ts
src/modules/worlds/sagas.ts
src/modules/worlds/selectors.spec.ts
src/modules/worlds/selectors.ts

Also renames Wallet Worlds Stats type
Closes #2926

feat: Worlds module that includes the sagas to fetch wallet worlds stats

---

src/components/WorldListPage_WorldsForEnsOwnersFeature/NameTabs/NameTabs.spec.tsx
src/components/WorldListPage_WorldsForEnsOwnersFeature/NameTabs/NameTabs.tsx
src/components/WorldListPage_WorldsForEnsOwnersFeature/NameTabs/NameTabs.types.ts
src/components/WorldListPage_WorldsForEnsOwnersFeature/hooks.spec.ts
src/components/WorldListPage_WorldsForEnsOwnersFeature/hooks.ts

Hook that contains logic that will be used in various places.

feat: Use currently selected tab hook for worlds view

---

src/components/Modals/DeployModal/DeployToWorld_WorldsForEnsOwnersFeature/DeployToWorld.tsx
src/components/Modals/DeployModal/DeployToWorld_WorldsForEnsOwnersFeature/utils.spec.ts
src/components/Modals/DeployModal/DeployToWorld_WorldsForEnsOwnersFeature/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

fix: Show corresponding error

---

package-lock.json
package.json
src/lib/urn.spec.ts
src/modules/deployment/sagas.spec.ts
src/modules/deployment/sagas.ts

feat: Unpublish world

---

src/components/Modals/DeployModal/DeployToWorld_WorldsForEnsOwnersFeature/DeployToWorld.tsx
src/components/WorldListPage_WorldsForEnsOwnersFeature/NameTabs/NameTabs.spec.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

fix: ENS Domains and Decentraland NAMEs copy normalization

---

src/components/Modals/WorldsYourStorageModal/WorldsYourStorageModal.tsx
src/components/WorldListPage_WorldsForEnsOwnersFeature/WorldListPage.tsx
src/components/WorldListPage_WorldsForEnsOwnersFeature/WorldsStorage/WorldsStorage.module.css
src/components/WorldListPage_WorldsForEnsOwnersFeature/WorldsStorage/WorldsStorage.spec.tsx
src/components/WorldListPage_WorldsForEnsOwnersFeature/WorldsStorage/WorldsStorage.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Closes #2955 
EXTRA:
Uses formatNumber from decentraland-dapps to show numbers properly :D

fix: Update worlds storage component styles

---

src/components/WorldListPage_WorldsForEnsOwnersFeature/WorldListPage.tsx
src/modules/ens/utils.spec.ts
src/modules/ens/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

- Update is external name function
- Changes worlds for ens owners FTUE copies
- Change MB for Mb
- Show count correctly on worlds list page

fix: Various changes Worlds for ENS Owners

---

src/modules/deployment/sagas.ts

Add the `is_smart` tag to scenes with smart items when deploying it. 
It's part of https://github.com/decentraland/sdk/issues/950

feat: tag scenes with smart items

---

package-lock.json
package.json
src/components/InspectorPage/InspectorPage.container.ts
src/components/InspectorPage/InspectorPage.tsx
src/components/InspectorPage/InspectorPage.types.ts
src/config/env/dev.json
src/config/env/prod.json
src/config/env/stg.json

This PR adds the inspector segment props to track events from the builder.
This PR is part of https://github.com/decentraland/sdk/issues/950

feat: Add inspector segment props

---

package-lock.json
package.json

This PR upgrades the SDK package to send a new property in the inspector's segment event

chore: Upgrade SDK package

---

package-lock.json
package.json

This PR upgrades the package `@dcl/sdk`

chore: Upgrade @dcl/sdk package

---

package-lock.json
package.json
src/components/InspectorPage/InspectorPage.container.ts
src/components/InspectorPage/InspectorPage.tsx
src/components/InspectorPage/InspectorPage.types.ts

This PR sends the project id to the inspector to track scenes and items.

feat: Send projectId to the inspector

---

src/config/env/dev.json
src/config/env/stg.json
src/modules/common/store.ts

Set basepath depending on host

fix: basepath for subdomains

---

src/components/Modals/WorldsYourStorageModal/WorldsYourStorageModal.tsx
src/components/Preview/Preview.tsx

use link instead of href for local redirections

fix: redirections with basename

---

src/modules/forum/utils.ts

fix: collection forum posts

---

package-lock.json
package.json

Upgrade `@dcl/sdk` to `v7.3.31`

feat: upgrade @dcl/sdk

---

src/components/Modals/CreateSingleItemModal/UploadVideoStep/UploadVideoStep.tsx
src/modules/item/errors.tsx
src/modules/item/sagas.spec.ts
src/modules/item/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

This PR increases the max video file size and remove the length validation to smart wearables preview

feat: Increase the max video file size

---

.github/workflows/build-release.yaml

Disable fail with warnings during CI

ci: disable fail with warnings

---

package-lock.json
package.json
src/components/Navbar/Navbar.container.ts
src/components/Navbar/Navbar.tsx
src/components/Navbar/Navbar.types.ts
src/index.css
src/modules/features/selectors.spec.ts
src/modules/features/selectors.ts
src/modules/features/types.ts

This PR adds the new Navbar V2
Depends on: https://github.com/decentraland/decentraland-dapps/pull/548

feat: Upgrade Navbarv2

---

package-lock.json
package.json

This PR overrides some `@walletconnect` dependencies

fix: Wallet connect dependencies version

---

src/components/SignInPage/SignInPage.tsx
src/routing/locations.ts

Fix redirection to auth dapp on sign in page

fix: redirection to auth dapp

---

package-lock.json
package.json

feat: upgrade sdk to v7.3.41

---

src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.css
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
src/components/Modals/CreateSingleItemModal/ImportStep/ImportStep.tsx

This PR fixes uploading both representations for smart wearables.

fix: Handle multiple representation for SmartWearables

---

package-lock.json
package.json
src/components/ItemEditorPage/CenterPanel/CenterPanel.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

This PR adds the new following default emotes:
- Walk
- Run
- Jump
https://github.com/decentraland/builder/assets/3170051/bb634b67-b083-4d94-b204-b104cbec2e31

feat: Add new default emotes

---

package-lock.json
package.json
src/modules/deployment/types.ts
src/modules/project/export.ts

This PR adds the default prop: `description` to the `scene.json` file

feat: Add description field to the scene file

---

package-lock.json
package.json

This PR upgrades the package @dcl/sdk to version 7.4.3

chore: Upgrade package @dcl/sdk to version 7.4.3

---

src/components/InspectorPage/InspectorPage.tsx

This PR fixes the `sanitizeUrl` method

fix: sanitizeUrl

---

src/modules/scene/reducer.ts
src/modules/sync/sagas.ts

This PR fixes the save project sagas when executed outside the inspector.

fix: Save project

---

package-lock.json
package.json

Upgrade `@dcl/sdk` to `v7.4.9`

feat: upgrade @dcl/sdk to v7.4.9

---

package-lock.json
package.json

Upgrade `@dcl/sdk` to `v7.4.12`

feat: upgrade @dcl/sdk to v7.4.12

---

package-lock.json
src/components/ItemEditorPage/RightPanel/RightPanel.container.ts
src/components/ItemEditorPage/RightPanel/RightPanel.css
src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/components/ItemEditorPage/RightPanel/RightPanel.types.ts
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.types.ts
src/components/Modals/CreateSingleItemModal/ImportStep/ImportStep.tsx
src/components/Modals/CreateSingleItemModal/utils.ts
src/modules/editor/types.ts
src/modules/features/selectors.spec.ts
src/modules/features/selectors.ts
src/modules/features/types.ts
src/modules/item/export.ts
src/modules/item/types.ts
src/modules/item/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Add VRM export toggle on builder ui

feat: block vrm export

---

package-lock.json
package.json

Upgrade `@dcl/sdk` to `v7.4.14`
* fix: nested entities by @cazala in https://github.com/decentraland/js-sdk-toolchain/pull/925
**Full Changelog**: https://github.com/decentraland/js-sdk-toolchain/compare/7.4.12...7.4.14

feat: upgrade @dcl/sdk to v7.4.14

---

src/components/Modals/PublishWizardCollectionModal/PublishWizardCollectionModal.container.ts
src/modules/item/selectors.spec.ts
src/modules/item/selectors.ts

This PR adds a filter for the exotic rarity that comes from the builder-server based of the feature flag.

feat: Filter exotic rarity

---

package-lock.json
package.json

Upgrade `@dcl/sdk` to `v7.4.17`

feat: upgrade @dcl/sdk to v7.4.17

---

src/components/ItemEditorPage/RightPanel/RightPanel.container.ts
src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/components/ItemEditorPage/RightPanel/RightPanel.types.ts
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.container.ts
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.types.ts
src/components/Modals/PublishWizardCollectionModal/PublishWizardCollectionModal.container.ts
src/modules/features/selectors.ts
src/modules/features/types.ts
src/modules/item/selectors.spec.ts
src/modules/item/selectors.ts

This PR removes the exotic rarity FF which is no longer required.

fix: Remove exotic rarity FF

---

src/components/ItemEditorPage/RightPanel/RightPanel.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

This PR adds a tooltip to the utility TextArea.

fix: Add utility tooltip

---

package-lock.json
package.json

This PR updates the `decentraland-ui` dependency to change the utility icon.

fix: Update utility icon

---

package-lock.json
package.json

Upgrade `@dcl/sdk` to `v7.5.0`
* remove old observabels logic by @gonpombo8 in https://github.com/decentraland/js-sdk-toolchain/pull/935
* feat: easy floor placing by @cazala in https://github.com/decentraland/js-sdk-toolchain/pull/941
* feat: Game smart items simplified view by @cyaiox in https://github.com/decentraland/js-sdk-toolchain/pull/943
* feat: add more avatar attach points by @AlejandroAlvarezMelucciDCL in https://github.com/decentraland/js-sdk-toolchain/pull/947
* feat: hide metrics by @cazala in https://github.com/decentraland/js-sdk-toolchain/pull/952
* DevExp improvements by @gonpombo8 in https://github.com/decentraland/js-sdk-toolchain/pull/950
* Add new Scene Layout by @nicoecheza in https://github.com/decentraland/js-sdk-toolchain/pull/945
* feat: upgrade @dcl/explorer …

feat: upgrade @dcl/sdk to v7.5.0

---

package-lock.json
package.json

This PR upgrades the package `@dcl/sdk` to the version 7.5.1.

feat: Upgrade @dcl/sdk package

---

src/components/AssetCard/HorizontalCard/HorizontalCard.tsx
src/components/Back/Back.tsx
src/components/CollectionDetailPage/CollectionContextMenu/CollectionContextMenu.container.ts
src/components/CollectionDetailPage/CollectionContextMenu/CollectionContextMenu.tsx
src/components/CollectionDetailPage/CollectionContextMenu/CollectionContextMenu.types.ts
src/components/CollectionDetailPage/CollectionDetailPage.container.ts
src/components/CollectionDetailPage/CollectionDetailPage.tsx
src/components/CollectionDetailPage/CollectionDetailPage.types.ts
src/components/CollectionDetailPage/CollectionItem/CollectionItem.container.ts
src/components/CollectionDetailPage/CollectionItem/CollectionItem.tsx
src/components/CollectionDetailPage/CollectionItem/CollectionItem.types.ts
src/components/ThirdPartyCollectionDetailPage/CollectionItem/CollectionItem.container.ts
src/components/ThirdPartyCollectionDetailPage/CollectionItem/CollectionItem.tsx
src/components/ThirdPartyCollectionDetailPage/CollectionItem/CollectionItem.types.ts
src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.container.ts
src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.tsx
src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.types.ts

This is the first of a series of PRs that move components to functional components so that we can remove `connected-react-router` dependency

feat: move collection items to functional components

---

package-lock.json
package.json
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
src/modules/item/errors.tsx
src/modules/item/export.ts
src/modules/item/sagas.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

This PR updates the logic that calculates the max file size for the smart wearables.

fix: SW max file size calculation

---

src/components/Modals/EditURNModals/EditItemURNModal/EditItemURNModal.container.ts

This PR changes the way we were building the item's URN so it matches the new URNs.

fix: Editing new item URN

---

src/components/Modals/CreateAndEditMultipleItemsModal/CreateAndEditMultipleItemsModal.tsx
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
src/lib/urn.spec.ts
src/lib/urn.ts

This PR changes the way we're generating the default URN item suffix for the new items by using slug over the name plus a random string.

feat: New default item URN suffix

---

src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.container.ts
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.types.ts

This PR allows editing mappings when editing the item.

feat: Allow editing mappings

---

src/components/ActivityPage/Transaction/Transaction.tsx
src/components/ActivityPage/Transaction/TransactionDetail/TransactionDetail.tsx
src/components/ActivityPage/Transaction/TransactionDetail/TransactionDetail.types.ts
src/components/CollectionsPage/CollectionsPage.tsx
src/components/ItemEditorPage/TopPanel/RejectionModal/RejectionModal.container.ts
src/components/ItemEditorPage/TopPanel/RejectionModal/RejectionModal.tsx
src/components/ItemEditorPage/TopPanel/RejectionModal/RejectionModal.types.ts
src/components/ItemEditorPage/TopPanel/TopPanel.container.ts
src/components/ItemEditorPage/TopPanel/TopPanel.tsx
src/components/ItemEditorPage/TopPanel/TopPanel.types.ts
src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.module.css
src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.tsx
src/components/ThirdPartyImage/ThirdPartyImage.module.css
src/components/ThirdPartyImage/ThirdPartyImage.tsx
src/components/ThirdPartyImage/ThirdPartyImage.types.ts
src/components/ThirdPartyImage/index.ts
src/modules/collection/selectors.spec.ts
src/modules/curations/itemCuration/reducer.spec.ts
src/modules/thirdParty/actions.ts
src/modules/thirdParty/reducer.spec.ts
src/modules/thirdParty/reducer.ts
src/modules/thirdParty/sagas.spec.ts
src/modules/thirdParty/sagas.ts
src/modules/thirdParty/selectors.spec.ts
src/modules/thirdParty/selectors.ts
src/modules/thirdParty/types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

Third PR adds the capability to disable a third party as a curator.

feat: Add disable Third Party

---

package-lock.json
package.json
src/components/Modals/CreateAndEditMultipleItemsModal/CreateAndEditMultipleItemsModal.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

This PR adds the capability of adding the `mapping` keyword to the `wearable.json` file to build an item with mappings.
It restricts the `wearable.json` to always contain a mapping if the collection is linked.

feat: Add mapping to multiple uploads

---

src/components/CollectionsPage/CollectionsPage.container.ts
src/components/CollectionsPage/CollectionsPage.tsx
src/components/CollectionsPage/CollectionsPage.types.ts
src/components/Modals/CreateCollectionModal/CreateCollectionModal.container.ts
src/components/Modals/CreateCollectionModal/CreateCollectionModal.tsx
src/components/Modals/CreateCollectionModal/CreateCollectionModal.types.ts
src/components/Modals/CreateCollectionSelectorModal/CreateCollectionSelectorModal.tsx
src/components/Modals/CreateThirdPartyCollectionModal/CreateThirdPartyCollectionModal.container.ts
src/components/Modals/CreateThirdPartyCollectionModal/CreateThirdPartyCollectionModal.tsx
src/components/Modals/CreateThirdPartyCollectionModal/CreateThirdPartyCollectionModal.types.ts
src/modules/features/selectors.spec.ts
src/modules/features/selectors.ts
src/modules/features/types.ts

Only show the collection creation selector when the Third Party payments feature is available.

feat: Show collection creation selector with payments

---

src/components/CollectionsPage/CollectionCard/CollectionCard.container.ts
src/components/CollectionsPage/CollectionCard/CollectionCard.types.ts
src/components/ItemEditorPage/LeftPanel/Collections/Collections.tsx
src/components/ItemEditorPage/LeftPanel/Collections/Collections.types.ts
src/components/ItemEditorPage/LeftPanel/Collections/SidebarCollection/SidebarCollection.types.ts
src/components/ItemEditorPage/LeftPanel/LeftPanel.container.ts
src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx
src/components/ItemEditorPage/LeftPanel/LeftPanel.types.ts
src/components/ItemEditorPage/RightPanel/RightPanel.container.ts
src/components/ItemEditorPage/RightPanel/RightPanel.types.ts
src/lib/api/builder.ts
src/modules/item/sagas.spec.ts
src/modules/item/sagas.ts
src/modules/item/selectors.ts

This PR loads the item when upserting it. The idea behind this changes is to have the latest item whenever updating it.
There are some fixes as well alongside the PR where the `setCollection` action is removed from places it wasn't being used.

Feat: Load item when upserting

---

package-lock.json
package.json
src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
src/modules/item/export.ts
src/modules/item/sagas.spec.ts
src/modules/item/sagas.ts
src/modules/item/utils.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

This PR validates the model size, including the thumbnail size, until there's a clear definition of how the catalyst will calculate it.

fix: Update models file

---

src/components/CollectionsPage/CollectionCard/CollectionCard.css
src/components/CollectionsPage/CollectionCard/CollectionCard.tsx
src/components/ItemStatusBadge/ItemStatusBadge.tsx
src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.module.css
src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.tsx
src/config/env/dev.json
src/lib/api/builder.ts
src/modules/collection/types.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

This PR adds the concept of having a mapping completed to the collections.
This implies receiving the property and:
- Showing a banner in the Third Party Collection Detail component.
- Showing that a migration is needed in the CollectionCard component.

feat: Add mapping completion to collections

---

src/components/MappingEditor/MappingEditor.module.css
src/components/Modals/PublishThirdPartyCollectionModal/PublishThirdPartyCollectionModal.module.css
src/components/Modals/PublishThirdPartyCollectionModal/PublishThirdPartyCollectionModal.tsx
src/components/Modals/PublishThirdPartyCollectionModal/PublishThirdPartyCollectionModal.types.ts
src/config/env/dev.json
src/modules/thirdParty/sagas.spec.ts
src/modules/thirdParty/sagas.ts
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json
src/modules/ui/thirdparty/types.ts

This PR improves the Third Party Publishing modal by changing its design and adding a success step.

Feat: Improve the TP publishing modal

---

src/modules/thirdParty/sagas.spec.ts
src/modules/thirdParty/sagas.ts

Whenever the user pushes items' changes and the collection is not fully migrated, re-fetch the collection so the `isMappingComplete` flag is updated.

feat: Update collection when migration is incomplete

---

src/modules/item/reducer.spec.ts
src/modules/item/reducer.ts

This PR updates the third party items being published or with changes being pushed to have the `isMappingComplete` flag correctly set.

fix: Update the isMappingComplete flag when publishing items or pushing changes

---

src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx

This PR fixes the issue where curating third party items with pushed changes (already published ones) after having loaded them before, resulted in viewing all of the TP items, even the ones that didn't require curation. This happened due to filtering the items by if they're published or not instead of their curation status.

fix: Only show TP items that require curation

---

src/modules/deployment/sagas.ts

This PR fixes a loading race condition when fetching the worlds deployments

fix: Fetch Worlds deployments race condition

---

src/modules/item/sagas.ts

This PR adds a FF to fetch collection items from marketplace server

fix: Add FF to fetch collection items from marketplace server

---

src/modules/ens/utils.spec.ts

This PR fixes some mocks not being done correctly.

fix: ENS utils tests not being mocked correctly

---

src/components/ItemEditorPage/LeftPanel/Items/Items.tsx
src/components/ItemEditorPage/LeftPanel/Items/Items.types.ts
src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx

This PR fixes the review TP items methods

fix: Update review TP items

---

src/components/ItemEditorPage/LeftPanel/Items/Items.tsx
src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx

This PR fixes the loadRandomPage method for LW items

fix: Load random page

---

package-lock.json
package.json
src/components/Intercom/Intercom.tsx

This PR updates the intercom component used to a new one with data augmented to have a better knowledge of the users reporting an error, improving the support team flow

feat: Update intercom component

---

src/components/LandDetailPage/LandDetailPage.tsx
src/components/LandDetailPage/Scene/Scene.tsx
src/components/LandDetailPage/Scene/Scene.types.ts
src/components/LandDetailPage/Scene/index.ts

This PR changes the Scene component to not show the un-publish button on the scenes if the user is a lessor of the shown land.

fix: Prevent land unpublishing if lessor

---

src/modules/deployment/sagas.ts

This PR changes the clear deployment sagas to work with user owned estate land.
There was an error where it was considered that all the land that came back from the `getLand` selector was a parcel, but  if the land is currently under a estate, the object changes, breaking the code.

fix: Incorrectly assigned deployment parcel

---

package-lock.json
package.json
src/config/env/prod.json
src/config/env/stg.json

This PR enables the Contentful banners in prod.

feat: Enable Contentful banners in prod

---

package-lock.json
package.json
src/components/Modals/PublishWizardCollectionModal/PayPublicationFeeStep/PayPublicationFeeStep.module.css
src/components/Modals/PublishWizardCollectionModal/PayPublicationFeeStep/PayPublicationFeeStep.tsx
src/modules/translation/languages/en.json
src/modules/translation/languages/es.json
src/modules/translation/languages/zh.json

This PR adds the capability to automatically publish collections on the Builder for Magic users.

feat: Automatically authenticate and publish collection for Magic users

---

src/components/Modals/DissolveModal/DissolveModal.tsx
src/components/Modals/EstateEditorModal/EstateEditorModal.tsx

- Remove validation to dissolve estates of more than 20 parcels
- Remove validation to add/remove more than 20 parcels when editing a estate

Remove validation to dissolve states

---

src/modules/land/sagas.ts

This PR enhances the refresh lands method when operating with lands.

fix: Waiting for land txn
