decentraland/builder

package-lock.json, package.json, src/components/Preview/Preview.css, src/themes/theme.css
This fixes the background color and uses the new decentraland-ui which already has the right primary color. Removes temporarily the line from the navbar via CSS until we can do that from decentraland-dapps. It also uses the prevew background for the placeholder while the client is loading.
=> style: colors

src/ecsScene/scene.ts, src/modules/common/store.ts, src/modules/scene/reducer.ts, src/modules/scene/selectors.ts
Closes #90 
- Prevent going to broken states by tracking the right actions and removing broken states from history. I had to remove to track the `CREATE_SCENE` action but also I had to remove it from the past history, otherwise if you undo all the way back you could reach a point where the scene was not created yet, thus this code:
```tsx
export const sceneReducer = (state: any, action: any) => {
const newState = undoableReducer(state, action)
// This prevents going back to a broken state after creating a new scene
if (action.type === CREATE_SCENE) {
newState.past.pop()
}
return newState
}
```
- Remove unused components and entities from scene (before this PR undoing would not remove stuff you added to the scene). The engine still doesn't provide a way to remove the unused components from …
=> fix: undo/redo

package-lock.json, src/components/EditorPage/EditorPage.css, src/components/Modals/ShortcutsModal/ShortcutsModal.tsx, src/components/Preview/Preview.css, src/components/Preview/Preview.tsx, src/components/Preview/Preview.types.ts, src/components/SideBar/SideBar.container.tsx, src/components/SideBar/SideBar.tsx, src/components/SideBar/SideBar.types.tsx, src/components/TopBar/TopBar.container.ts, src/components/TopBar/TopBar.css, src/components/TopBar/TopBar.tsx, src/components/TopBar/TopBar.types.ts, src/components/ViewPort/ViewPort.css, src/modules/common/store.ts, src/modules/editor/actions.ts, src/modules/editor/reducer.ts, src/modules/editor/sagas.ts, src/modules/editor/selectors.ts, src/modules/editor/types.ts, src/modules/scene/actions.ts, src/modules/scene/reducer.ts, src/modules/scene/sagas.ts, src/modules/scene/selectors.ts, src/modules/translation/languages/en.json, src/scenarios/MetricsOutOfBounds.ts, src/themes/theme.css
Closes #46 
Closes #57 
Closes #58 
Closes #99 
I refactored the scene actions so they are all handled by sagas and in the end they dispatch a `provisionScene` action with the whole scene. I did this so in order to have a single action that writes the scene to the app state (this is useful for undo/redo since we just have to track one action) also it makes it easier to listen for changes and send them to the `ecsScene`, we don't have to listen to several actions.
I also did some renaming: 
+ Set Mode -> Set Gizmo
+ Add Asset -> Add Item (to match all the other item-related actions like reset/duplicate/delete, also it feels more accurate since adding an asset would be adding a new model to the available ones, rather than adding an instance of that model to the scene)
=> feat: reset/duplicate/delete item

src/components/Modals/EditProjectModal/EditProjectModal.tsx, src/components/TopBar/TopBar.css, src/components/TopBar/TopBar.tsx
Fixes bug where props are not updated when switching projects and re-entering the modal.
Makes title clickable to open modal.
=> fix: edit project modal

src/ecsScene/scene.ts
**Problem:**
When toggling the preview mode, gizmos are re-added to all entities, this makes grounds pickable and movable
**Solution:**
Create a component that marks entities as static, prevent those entities from ever getting gizmos
Closes #187
=> fix: prevent gizmos from being added to grounds

src/modules/scene/sagas.ts
=> fix: ground placement

src/ecsScene/scene.ts, src/modules/editor/sagas.ts
=> fix: restore gizmos after exiting preview mode

src/components/EditorPage/Metrics/Metrics.tsx
When two or more metrics where exceeded (say, `triangles` and `terxtures`) this component would report a `Metric exceeded` event on every call to `componentWillReceiveProps` (that's a lot) and it was polluting the analytics on segment.
This PR fixes that.
=> fix: prevent reporting each time props are received when more than one metric is exceeded

src/index.css
Closes #329 
This hides Intercom's "Need help?" message, but everything else still works:
=> feat: hide intercom message

src/modules/editor/sagas.ts
The gifs above show how the changes reflect on differently sized projects when entering preview mode
Closes #298
=> chore: spawn outside of scene

src/components/MobilePage/MobilePage.css, src/components/MobilePage/MobilePage.tsx
=> chore: mobile header styles

src/components/EditorPage/Metrics/Metrics.tsx
Closes #367 
Adds `count` and `limit` to the `Metrics Exceeded` event
=> chore: add count and limit to metrics exceeded event

src/components/EditorPage/EditorPage.tsx, src/components/SideBar/ItemDrawer/ItemDrawer.css, src/lib/api.ts, src/modules/assetPack/sagas.ts, src/modules/assetPack/types.ts, src/modules/assetPack/utils.ts, src/modules/common/store.ts, src/modules/project/actions.ts, src/modules/project/reducer.ts, src/modules/project/sagas.ts, src/modules/project/types.ts, src/modules/ui/sidebar/actions.ts, src/modules/ui/sidebar/reducer.ts, src/modules/ui/sidebar/selectors.ts, src/scenarios/helpers/assetPacks.ts, tsconfig.json
Closes #460 
Use the following variable in your `.env`
```
REACT_APP_ASSETS_URL=https://builder-packs-stg.now.sh
```
This PR changes the logic of loading asset packs to do the following:
1. Load the asset pack manifest
2. Get the user selection of asset packs (by default this is all the available asset packs)
3. For every selected asset pack:
3.1. Check if the asset pack is not in state and it has not already been loaded
3.2 If not loaded, it fetches it from the server, otherwise uses the one already in state
4. All the non-selected asset packs are added to the state and marked as not loaded (so we can render a UI for the user to select them)
5. All the asset packs that were not in the available asset pack since last time the user visited are marked as new
The selection of asset packs are …
=> feat: support for server with multiple asset packs

src/components/Banners/HomePageBanner/HomePageBanner.tsx, src/components/HomePage/PromoBanner/PromoBanner.tsx, src/components/SideBar/AssetPackList/AssetPackList.css, src/components/SideBar/AssetPackList/AssetPackList.tsx, src/components/SideBar/ItemDrawer/ItemDrawer.css, src/components/SideBar/ItemDrawer/ItemDrawer.tsx, src/modules/analytics/campaigns.ts, src/modules/analytics/sagas.ts, src/modules/common/store.ts, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/ko.json, src/modules/translation/languages/zh.json
=> chore: tracking and copy changes

src/modules/deployment/sagas.ts, src/modules/editor/sagas.ts, src/modules/project/sagas.ts, src/modules/scene/utils.ts
Fixes #582 
I added a helper `getSceneByProjectId` that tries to get the scene from the app state, and if not there, it downloads the manifest and returns it.
I used this helper in the sagas related to `Duplicate project`, `Download project` and `Unpublish` because those were breaking when used from the homepage do to the scene not being in memory.
=> fix: homepage actions

src/lib/api/builder.ts, src/modules/editor/sagas.ts, src/modules/editor/utils.ts, src/modules/sync/sagas.ts, src/modules/sync/utils.ts
Fixes #599 
How to reproduce bug in master:
1) Create a new project
2) Wait for the cloud icon to disappear
3) Go back to dashboard (you will see the screenshot, but taken prior to the ground to be loaded)
4) Refresh the page, and the screenshot is not there (it was never sent)
This PR fixes two things:
- Wait for the assets to be loaded before taking the screenshot, fixing the screenshot in step 3.
- Wait for thumbnail to exist before sending it to the server, fixing step 4.
You can do those steps in this branch to confirm the fix
=> Save screenshots of new projects

src/modules/project/sagas.ts, src/modules/project/utils.ts
Add thumbnail to the duplicated project
If the image is referenced remotely, fetch it and convert it to base64
On project save success the new media should be saved separately
Closes #613
=> fix: thumbnails for duplicated scenes

src/components/ProjectCard/ProjectCard.css
Fixes #601 
✅ Fixes the single-line long names with text ellipsis
✅ Supports multi-line names
✅ Leaves a space for the cloud icon
=> fix: long scene names

src/components/AvatarFace/AvatarFace.tsx, src/components/AvatarFace/AvatarFace.types.ts, src/components/AvatarFace/utils.ts, src/components/UserMenu/UserMenu.container.ts, src/components/UserMenu/UserMenu.tsx, src/components/UserMenu/UserMenu.types.ts
Use the `updateAt` prop to bust the avatar face cache to prevent the blinking on every render.
Before:
After:
=> fix: bust cache using updateAt to prevent blinking

src/components/Drawer/Drawer.tsx
=> fix: don't hide category assets after closing search drawer

src/modules/editor/sagas.ts, src/modules/scene/types.ts
Builder was crashing when trying to display scene's metrics.
=> fix: scene's metrics crash. removed old babylon scene metrics

src/modules/editor/sagas.ts, src/modules/media/sagas.ts
BJS was taking its angle from a vertical axis and Unity is using an horizontal axis. I manually converted rotation angles to fit Unity uses
=> fix: camera pitch rotation angle conversion from BJS to Unity

src/modules/migrations/utils.ts, src/modules/project/export.ts, src/modules/scene/sagas.ts, src/modules/scene/utils.ts
Properly generate ground entity names (entity{N})
Get unique names from assets rather than GLTFShapes (fixes case where there's an scene.gltf model that conflicts with the scene entity wrapper on export)
Keep old naming system for legacy purposes/migration
Closes #882
=> fix: ground entity names

src/modules/media/sagas.ts
Deselect the entity before taking pictures, so the gizmos and outlines don't show up
=> fix: deselect before screenshot

src/ecsScene/scene.ts, src/modules/migrations/manifest.ts, src/modules/migrations/store.ts, src/modules/migrations/utils.ts, src/modules/project/export.ts, src/modules/scene/sagas.ts, src/modules/scene/types.ts
This PR deprecates the `src` property in the `Script` components and uses the `assets.contents` to get the url of the script file instead.
This allows us to update the urls by just re-uploading the assets to the builder server.
=> feat: use asset contents instead of src

src/components/ItemEditorPage/LeftPanel/LeftPanel.css, src/components/ItemImage/ItemImage.css
adds scroll to the left panel to prevent this:
Also fixes the item image that looked stretched when there were 3 items:
I had to set a max-width to prevent this:
=> fix: left panel scroll and item image

src/components/AvatarPage/AvatarPage.css, src/components/HomePage/HomePage.css
Fixes the avatar page grid alignment, now it fits 4 elements per row:
Also a small page in the Scenes page to keep it consistent with Land and Avatar pages
=> fix: avatar page grid

src/components/TopBar/TopBar.container.ts, src/components/TopBar/TopBar.css, src/components/TopBar/TopBar.tsx, src/components/TopBar/TopBar.types.ts
This fixes an error intruduced by #1146 that causes the "back" button in the scene editor and the "back" button in the scene detail page to loop when clicking them (because the one in the editor does a push, and the one in the detail page does a pop). This PR fixes that.
=> fix: editor back button

src/components/ItemDetailPage/ItemDetailPage.tsx, src/components/ItemEditorPage/LeftPanel/Collections/SidebarCollection/SidebarCollection.tsx, src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx, src/components/ItemEditorPage/RightPanel/RightPanel.tsx, src/modules/editor/sagas.ts, src/modules/item/utils.ts
Few fixes:
+ Select a valid body shape for the selected item when opening the editor
+ Auto select the collection when opening an item that's inside a collection
+ Auto select the first item of the collection when opening a collection 
+ Show the loading spinners in the sidebars only the first load (when there's still no data in the store)
=> fix: opening editor edge cases

src/components/CollectionProvider/CollectionProvider.container.ts, src/components/CollectionProvider/CollectionProvider.tsx, src/components/CollectionProvider/CollectionProvider.types.ts, src/components/ItemProvider/ItemProvider.tsx, src/lib/api/builder.ts, src/modules/collection/actions.ts, src/modules/collection/reducer.ts, src/modules/collection/sagas.ts, src/modules/item/actions.ts, src/modules/item/reducer.ts, src/modules/item/sagas.ts
**Depends on:** https://github.com/decentraland/builder-server/pull/135
This PR makes the necessary changes to use the version of the server that does't return nested items and collections.
Since collections don't come with their items inside, I added an extra endpoint to the server and a corresponding action on the frontend to fetch a collection's items
=> refactor: remove nested collections and items

src/components/AssetImporter/AssetImporter.tsx, src/components/AssetImporter/utils.ts, src/ecsScene/scene.ts, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
This PR fixes an issue on prod where users can't import custom smart items. This is due to a change in the way the SDK bundles the JS, we were looking for a piece of code to extract the code of the smart item, but that piece of code doesn't exist anymore, so I updated it to a new regex that matches the way the code is bundled now.
Also I improved the error reporting of duplicated assets because the current one was not clear and caused confusion, now if an item has the id of an already existing item we show the following:
=> fix: custom smart items

src/lib/api/marketplace.ts, src/modules/ens/sagas.ts
Currently the builder loads a maximum of 100 names, this PR makes it so it loads as many as the user has. Also I changed a bit the saga so the names are loaded in parallel, which is way faster for users with many names (1000 names took me 5 minutes to load before, and now 20 seconds).
=> fix: names limit

src/modules/deployment/sagas.ts
Sending an empty `pointers` array causes the catalyst to return _all_ the entities, degrading the peer's performance and returning unexpected results. It will be fixed on the catalyst, but also we'll release this patch to prevent builder users from stressing the peers until then.
=> fix: prevent fetching empty coords

src/components/ItemEditorPage/TopPanel/ReviewModal/ReviewModal.css, src/components/ItemEditorPage/TopPanel/ReviewModal/ReviewModal.tsx
Strangely enough, because of how the files get built, this did not happen in development
Closes #1319
=> fix: appove/reject button size on loading

src/components/AssetImporter/utils.ts
This PR fixes an issue when importing system dependencies, like `@decentraland/Identity`.
The `@` present in was not matched by the regular expression, preventing dependencies included after them from being namespaced:
This is OK
This is WRONG:
This error resulted in converting this:
```
["require", "exports", "myFirstDep", "@decentraland/Identity", "mySecondDep"]
```
into:
```
["require", "exports", "smart-item-id/myFirstDep", "@decentraland/Identity", "mySecondDep"]
```
Notice that `mySecondDep` was not namespaced.
So I added `@` to the match regexp to solve this issue.
Then I added a `\w` at the beginning of the namespacing regexp to prevent the system dependencies that now are matched by the first regexp to be namespaced. Otherwise `@decentraland/Identity` would be namespaced into …
=> fix: smart item system deps

src/components/Modals/PublishCollectionModal/PublishCollectionModal.tsx
Used the URL directly instead of an ENV var because it's a really specific case without a dev equivalent
Closes #1371
=> chore: href to docs

src/modules/project/export.ts
fixes builder in world issue: https://github.com/decentraland/unity-renderer/issues/578
builder in world adds several unsupported components to entities.
`component` record is filtered by types but unsupported components in entities are still trying to be added while exporting
=> fix: undefined component while export

src/modules/item/export.ts
If we use `Date.now()`, we depend on the local machine's clock. If the clock is off, the deployment will fail. To avoid this issue, we will use the server's time.
=> fix: avoid Date.now()

src/components/CollectionDetailPage/CollectionDetailPage.tsx, src/components/CollectionDetailPage/CollectionMenu/CollectionMenu.container.ts, src/components/CollectionDetailPage/CollectionMenu/CollectionMenu.tsx, src/components/CollectionDetailPage/CollectionMenu/CollectionMenu.types.ts, src/modules/collection/utils.ts, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
This PR adds a "Open in editor" menu item to the collections option menu.
Closes #1313
=> Add menu item to go to the editor from the collection

src/components/AssetImporter/utils.ts, src/modules/project/export.ts
Renamed `getPath` into `buildAssetPath` and reused it on the generation of the JS file to avoid a mismatch in asset paths between mappings and the compiled js.
=> fix: smart items asset paths on deployed js

src/components/CurationPage/CollectionRow/CollectionRow.tsx
The width of the new column made the approved or rejected column to move down the row:
By resizing the other columns, we can fit the new column without any issues:
=> fix: Curator's page columns width

src/components/ItemDetailPage/ItemDetailPage.tsx, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
This PR adds the blockchain id to the items page.
Closes #1508
=> feat: Add blockchain id to the items page

src/components/Modals/ShareModal/ShareModal.css, src/components/Modals/ShareModal/ShareModal.tsx, src/components/Modals/ShareModal/ShareModal.types.ts
This PR fixes the copy button by using the `CopyToClipboard` component. It also adds a simple border to the button so it doesn't merge with the input next to it.
Closes #1483
=> fix: Copy button in Share Modal

src/components/Modals/CreateItemModal/CreateItemModal.tsx, src/components/Modals/CreateItemModal/CreateItemModal.types.ts, src/modules/deployment/contentUtils.ts, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
This PR adds a mechanism to prefix the contents so they don't get overwritten by having the same name. This was common if one of the representations (male/female) was added after the other one and had the same name.
The prefix uses the selected body-shape.
Closes #1488
=> fix: Import model with the same name

src/components/CollectionsPage/CollectionCard/CollectionCard.tsx
Closing #1517 
As it is the only option for collections, I decided to entirely remove the dropdown in this case so there is not an empty list of options.
=> Don't show delete option on published collections

src/components/Modals/CreateAssetPackModal/CreateAssetPackModal.tsx, src/modules/assetPack/reducer.ts
Closes #1511 
This was because on fail, the close button looped between different states of the modal view, going back to the same one every time.
=> Fix: When asset pack creation failed, the modal could not be closed

src/components/Modals/ClaimNameFatFingerModal/ClaimNameFatFingerModal.tsx, src/modules/translation/languages/es.json
Closes #1532 
Also fixes text in spanish on the ClaimNameFatFingerModal that was not being correctly replaced.
=> fix: Disable claim name confirm button when loading

src/modules/item/export.ts
Chrome seems to cache responses that come from non-fetched requests as the same responses that come from fetched requests. This is a big issue because non-fetched requests don't require CORS, but fetched requests might. This cache strategy caused an issue because, when trying to add a new representation of an existing item, the content got cached without CORS headers when we loaded it a preview image before doing the fetch, resulting in a fetch request without headers and a CORS request failing.
This PR adds headers to avoid using cache when requesting the older models when adding new representations to an item.
=> fix: Don't use cache when fetching contents

src/lib/headers.ts, src/modules/deployment/sagas.ts, src/modules/item/export.ts, src/modules/media/utils.ts, src/modules/project/export.ts
This PR adds headers to avoid cached requests when fetching content to deploy a scene.
=> fix: Fetch scene content without cache

src/components/CollectionDetailPage/CollectionMenu/CollectionMenu.tsx, src/components/JumpIn/JumpIn.tsx, src/modules/collection/utils.ts, src/modules/item/export.ts, src/modules/item/sagas.ts, src/modules/item/utils.ts
This PR fixes an issue where the wrong chain id was used to generate the URN protocol (it was using the connected `chainId` (either mainnet or ropsten))
=> fix: use matic urn protocol

src/components/Modals/CreateItemModal/CreateItemModal.tsx, src/modules/item/export.ts, src/modules/item/sagas.ts
This PR fixes an issue of calculating the thumbnail size twice when the user added a representation of an item that had a custom thumbnail.
The PR also tidies up a bit of the code.
=> fix: Avoid counting the thumbnail twice when computing the file sizes

src/components/ActivityPage/Transaction/Transaction.tsx, src/components/Modals/MintItemsModal/MintItemsModal.tsx, src/modules/collection/utils.spec.ts, src/modules/collection/utils.ts, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
This PR fixes the transaction message when the mint was/is minted. The amount was computed from the length of the mints, but each mint has an amount of times it should be minted.
This PR also fixes a small issue where the same item could be added twice to be minted.
=> fix: Mint message showing an incorrect amount of minted items

src/components/AssetImporter/AssetImporter.tsx, src/components/AssetsEditor/SingleAssetEditor/SingleAssetEditor.tsx, src/components/Modals/CreateItemModal/CreateItemModal.tsx, src/lib/getScreenshot.ts, src/modules/item/utils.ts
This PR does the following:
- Fixes a default value that resulted in all thumbnails to be 1024px in size.
- Makes the assets be 256px in size.
- Makes the wearable thumbnails to be 512px in size.
- Fetches the thumbnail to generate the catalyst image without cache.
=> fix: Thumbnail image too big

src/lib/api/builder.ts, src/modules/assetPack/sagas.ts
This PR uses the new query parameter to fetch simultaneously the asset packs created by the user and the default ones.
=> feat: Fetch default & created by the user asset packs

src/lib/api/analytics.ts, src/lib/api/builder.ts, src/modules/common/sagas.ts, src/modules/stats/sagas.ts, src/modules/stats/types.ts
Use the data cdn to show stats. I'm perma caching in memory the promise since it only changes every 24hs. Also I'm caching the promise and not the result because in many cases there are several requests fired simultaneously and awaiting the result before caching would end up in many requests, this way there's only one.
This is a temporary solution until we have a server or something in place, but from my tests this is loading in a reasonable time (500ms, 400kb using brotli compression)
=> fix: stats

src/modules/item/utils.spec.ts, src/modules/item/utils.ts
Fixes #1696
The issue was that if you had an item with BOTH representations, and you removed one, the item would not be marked as `unsynced`, so you wouldn't be able to push the changes for review (because we only checked that all the `item.contents` existed on the `entity.contents`). Now we compare that both representations are equal.
=> fix: compare representations in areSynced

src/modules/item/export.ts
Fixes issue with new `/status` endpoint where the timestamp ends up being `null`
=> fix: entity timestamp

src/components/CollectionsPage/CollectionCard/CollectionCard.tsx
Fixes https://github.com/decentraland/builder/issues/1709
=> Moves status icon to the beginning of the collection name

src/modules/collection/sagas.spec.ts, src/modules/deployment/sagas.ts, src/modules/deployment/utils.ts, src/modules/entity/actions.ts, src/modules/entity/reducer.spec.ts, src/modules/entity/reducer.ts, src/modules/entity/sagas.spec.ts, src/modules/entity/sagas.ts, src/modules/entity/selectors.ts, src/modules/item/sagas.spec.ts, src/modules/item/sagas.ts, src/modules/item/selectors.spec.ts, src/modules/item/selectors.ts, src/modules/item/utils.ts
Replaces the use of the deprecated and throttled `fetchAllDeployments` for `fetchEntitiesByPointers` and `fetchEntitiesByIds`. The first method returns a `DeploymentWithContentAndMetadata` and the latter ones an `Entity`, so I had to make some refactors but all the important data was available.
=> fix: use fetchEntitiesByPointers instead of fetchAllDeployments

src/components/InfoIcon/InfoIcon.tsx, src/components/ItemEditorPage/RightPanel/MultiSelect/MultiSelect.css, src/components/ItemEditorPage/RightPanel/MultiSelect/MultiSelect.tsx, src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.css, src/components/Modals/EditPriceAndBeneficiaryModal/EditPriceAndBeneficiaryModal.tsx, src/components/Modals/EstateEditorModal/EstateEditorModal.css, src/components/Modals/EstateEditorModal/EstateEditorModal.tsx
This PR fixes the Info popups that:
- Were not opening due to `react-semantic-ui` expecting a semantic component instead of a custom component for the popup trigger.
- Had issues with the styles due to being styled from other components.
=> fix: Info popups

src/components/Modals/ApprovalFlowModal/ApprovalFlowModal.tsx
The approval flow has many async steps that require the user to wait for them to be completed. While waiting, the user can close the modal by clicking outside of it or the cancel or close buttons but doing this might leave the user wondering what's happening behind the scenes. This PR removes the possibility of closing the modal until each of the operations finishes.
=> fix: Make the approval flow modal to not be closable

src/components/Modals/PublishThirdPartyCollectionModal/PublishThirdPartyCollectionModal.container.ts, src/components/Modals/PublishThirdPartyCollectionModal/PublishThirdPartyCollectionModal.tsx, src/components/Modals/PublishThirdPartyCollectionModal/PublishThirdPartyCollectionModal.types.ts, src/components/ThirdPartyCollectionDetailPage/CollectionPublishButton/CollectionPublishButton.container.ts, src/components/ThirdPartyCollectionDetailPage/CollectionPublishButton/CollectionPublishButton.tsx, src/components/ThirdPartyCollectionDetailPage/CollectionPublishButton/CollectionPublishButton.types.ts, src/modules/item/selectors.spec.ts, src/modules/item/selectors.ts, src/modules/item/utils.ts, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
* feat: Make the TP items updatable after being published
* chore: fix broken test
* feat: Add onPushChanges prop to TP publish modal
* feat: Add getStatusForItemIds selector
* feat: Add onPublishAndPushChanges prop
* chore: update broken test
* feat: Add logic to PublishTPCollectionModal to support different actions
* chore: move import to right place
* chore: fixes translation
* feat: Remove DCL logic from TP button
* chore: Remove old TODO
* feat: Update translations
* feat: Add isStatusAllowedToPushChanges util method
=> feat: Make the TP items updatable after being published (#1797)

src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.tsx, src/modules/thirdParty/utils.ts
Removed MAX_PUBLISH_ITEM_COUNT from src/modules/thirdParty/utils.ts and its usage from src/components/ThirdPartCollectionDetailPage/ThirdPartCollectionDetailPage.tsx.
=> Removed MAX_PUBLISH_ITEM_COUNT and its usage

src/components/CollectionImage/CollectionImage.container.ts, src/components/CollectionImage/CollectionImage.css, src/components/CollectionImage/CollectionImage.tsx, src/components/CurationPage/CollectionRow/CollectionRow.container.ts, src/components/CurationPage/CollectionRow/CollectionRow.tsx, src/components/CurationPage/CollectionRow/CollectionRow.types.ts, src/components/CurationPage/CurationPage.css, src/components/CurationPage/CurationPage.tsx, src/modules/collection/sagas.spec.ts, src/modules/collection/sagas.ts, src/modules/committee/sagas.ts, src/modules/item/actions.ts, src/modules/item/sagas.ts
Absolutely every item is being requested when opening the curation page and approving a collection.
Now only required items for the moment are fetched.
=> fix: Don't request all items at once

src/components/ThirdPartyCollectionDetailPage/CollectionPublishButton/CollectionPublishButton.tsx
The server is returning a 409 so `itemCurations`  is `undefined` instead of an array. This might be a temporary solution, we need to define if the server is returning the proper respose.
Closes #1868
=> fix: Add safe operator to access item curations

src/components/CollectionDetailPage/CollectionItem/CollectionItem.tsx, src/components/ItemDetailPage/ItemDetailPage.tsx, src/components/ItemEditorPage/RightPanel/RightPanel.tsx, src/components/Modals/ApprovalFlowModal/ApprovalFlowModal.tsx, src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.css, src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx, src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.types.ts, src/lib/getModelData.ts, src/lib/getScreenshot.ts, src/modules/item/export.ts, src/modules/item/types.ts, src/modules/item/utils.ts, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json, src/specs/item.ts
This PR adds support to create items of type `emote`. When the user drops a GLB we check if there are animations inside of it, and if so, assume it's an emote. Emotes are currently stored as a `Wearable` on the catalyst with an extra `emoteDataV0` property. On the blockchain side they are stored with a different type `e` and their own set of categories (`simple` and `loop`). There are several `any` and other castings done on the UI side, specially on the `CreateItemModal` and `RightPanel`, eventually we need to refactor these components in a way to support several item types each with their own schema in a graceful way.
=> feat: support creation of emotes

package-lock.json, package.json, src/components/Modals/ApprovalFlowModal/ApprovalFlowModal.container.ts, src/components/Modals/ApprovalFlowModal/ApprovalFlowModal.tsx, src/components/Modals/ApprovalFlowModal/ApprovalFlowModal.types.ts, src/modules/collection/sagas.spec.ts, src/modules/collection/sagas.ts, src/modules/item/types.ts, src/modules/thirdParty/actions.ts, src/modules/thirdParty/sagas.ts
This PR changes the `handleInitiateTPItemsApprovalFlow` so when the curator approves the TP items using an already consumed cheque, the cheque is not sent in the meta transaction to the ThirdParty registry.
Closes #1879
=> fix: Publish changes without cheques

src/components/ThirdPartyCollectionDetailPage/CollectionPublishButton/CollectionPublishButton.tsx
=> fix: Allow user to push changes even if there are no slots

src/components/LandDetailPage/LandDetailPage.tsx, src/lib/api/manager.ts, src/modules/land/types.ts
From trying to edit a estate looking like this:
to this:
=> fix: allow editing estates with size > 100 (<1000)

src/components/CurationPage/CurationPage.css, src/components/CurationPage/CurationPage.tsx
=> feat: Add scroll to assignee filter and contrast to selected option

src/components/CurationPage/CurationPage.tsx
Closes #2011
Example with pagination page 1, so it's clear that now the total is calculated based on the filtered ones:
=> fix: Curation Page pagination issue

src/lib/getScreenshot.ts
generated in parallel using the code in this PR
=> fix: Uses whenReadyAsync to generate screenshots in parallel

src/components/ThirdPartyCollectionDetailPage/CollectionPublishButton/CollectionPublishButton.tsx
The greater comparison was preventing collections with the exact number of items from being published.
=> fix: Change comparison on consumed slots

src/components/CollectionDetailPage/CollectionContextMenu/CollectionContextMenu.tsx, src/components/CollectionDetailPage/CollectionItem/CollectionItem.tsx, src/components/ItemEditorPage/TopPanel/TopPanel.tsx, src/components/JumpIn/JumpIn.tsx, src/components/JumpIn/JumpIn.types.ts, src/components/ThirdPartyCollectionDetailPage/CollectionContextMenu/CollectionContextMenu.container.ts, src/components/ThirdPartyCollectionDetailPage/CollectionContextMenu/CollectionContextMenu.tsx, src/components/ThirdPartyCollectionDetailPage/CollectionContextMenu/CollectionContextMenu.types.ts, src/components/ThirdPartyCollectionDetailPage/CollectionItem/CollectionItem.tsx, src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.tsx, src/modules/collection/utils.ts
=> feat: Add open in world in the collection detail for items

src/components/ItemEditorPage/LeftPanel/Items/Items.css, src/components/ItemEditorPage/LeftPanel/Items/Items.tsx, src/components/ItemEditorPage/LeftPanel/Items/Items.types.ts, src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx
The problem with the current loader was that if the user scrolls too fast, several pages were fetched at the same moment, so there was a race condition between the pages and the chances of missing pages while scrolling were high. This PR solves the issue, waiting to `isLoading` to be `false` to trigger the next page request.
Closes #2054
=> feat: improve the infinite scrolling UX for the LeftPanel

src/modules/curations/itemCuration/sagas.spec.ts, src/modules/curations/itemCuration/sagas.ts
The collection and collection items are fetched at the same time. Once the items request is done, the one for the item curations is trigger. If at that point we collection request is still ongoing, the itemCuration sagas will fail because it tries to get data from the collection before triggering the curations request.
We can get the same data from the items (`collectionId` and if the collection is TP or not). Let's do it that way so we don't have to way to both request (collection and item collections) to finish.
Closes #2056
=> fix: Avoid the race condition getting the data from the tp items

src/components/ItemEditorPage/LeftPanel/Collections/Collections.css, src/components/ItemEditorPage/LeftPanel/Collections/Collections.tsx, src/components/ItemEditorPage/LeftPanel/Items/Items.css, src/components/ItemEditorPage/LeftPanel/Items/Items.tsx
This PR adds some padding to the pagination component in the sidebar so it doesn't touch the rows.
Before:
After:
Also it removes the pagination component if there's only 1 page like here:
=> feat: remove pagination if not necessary + add padding

now.json, scripts/prebuild.js
The fix is basically calling the `dotenv.config()` that puts the stuff from the `.env` file into the `process.env` object. The rest is for debugging.
=> ci: fix prebuild

src/modules/curations/itemCuration/sagas.spec.ts, src/modules/curations/itemCuration/sagas.ts
After selecting all the items of a collection to publish or push changes, all the curations were requested at the same time using `/collections/collectionId/itemCurations` endpoint, failing the request due to reaching the maximum length of the URL.
=> fix: Fix retrieving batched item curations

src/modules/item/export.ts
Currently we can't deploy emotes because the metadata doesn't follow the wearable schema (missing hides/replaces/overrides and category is a different enum).
So I had to hack it to make it pass through. I deployed and minted the pride emotes in ropsten and tested them on play.decentraland.org?NETWORK=ropsten and they worked fine:
Eventually once the EMOTE entity type is live these emotes will need to be redeployed with the new entity type, and that one is going to have it's own schema so these hacks could be removed.
=> fix: make emotes follow the wearable schema to allow deployments

src/components/Modals/PublishCollectionModalWithOracle/PublishCollectionModal.container.ts, src/components/Modals/PublishCollectionModalWithOracle/PublishCollectionModal.tsx, src/components/Modals/PublishCollectionModalWithOracle/PublishCollectionModal.types.ts
Show errors from the `collection` module in `PublishCollectionModal`. These are errors like when the collection is locked, or when it is already published.
=> fix: show publication errors in modal

package-lock.json, package.json
There was very niche dependency problem causing EntityType to be `undefined` **inside** decentraland-dapps. Because the (not major 😠 ) version of @dcl/schemas removes EntityType I had to force-install 4.14.0 for it to work.
That said, I'm now hitting this error:
`"Failed to fetch https://peer.decentraland.zone/content/contents/QmV6f9iNyPGTFsFrWuv5AnQkjWcHkt8WXNZnjXSAGtofdy. Got status 404. Response was ''"`
in dev. Pls reviewer could you check with your names? as I'm not sure if this is a me thing
=> fix: use as alias

src/lib/api/builder.ts
This PR removes the fields `createdAt` and `updatedAt` from the payload sent to the backend for the `Items` upsert.
=> feat: Update Items type

src/components/Modals/MoveItemToCollectionModal/MoveItemToCollectionModal.tsx
This PR disables the move button when the user has not selected a collection and enables it when a collection is selected.
Closes: #2153
=> fix: Enable the move button only when selecting a collection

src/components/CollectionDropdown/CollectionDropdown.tsx, src/components/CollectionDropdown/CollectionDropdown.types.ts, src/components/Modals/MoveItemToCollectionModal/MoveItemToCollectionModal.tsx, src/lib/api/builder.ts
This PR allows filtering the available collections to show when moving an item to a collection.
Closes: #2143
=> feat: Filter collections to only show allowed ones when moving a single item to a collection

src/modules/item/sagas.spec.ts, src/modules/item/sagas.ts
This PR allows fetching the items list again when moving an orphan item to an unpublished collection successfully.
Closes: #2152
=> fix: Fetch the items list again when moving a single item to a collection successfully

src/modules/item/sagas.spec.ts, src/modules/item/sagas.ts, src/modules/wallet/utils.ts
This PR avoids updating the item metadata when setting a new item price/beneficiary. Instead, it gets the item metadata from the blockchain and uses it when sending the txn.
Closes: #1694
=> Fix: Edit item Price and Beneficiary should not change the item metadata

src/modules/item/sagas.spec.ts, src/modules/item/sagas.ts
This PR fixes the emotes redirection to the item editor when creating inside a collection.
Closes #2220
=> Fix: Emotes redirection to the item editor

src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx, src/components/Modals/CreateSingleItemModal/ImportStep/ImportStep.tsx, src/components/Modals/CreateSingleItemModal/ImportStep/ImportStep.types.ts
This PR fixes the missing prop `bodyShape` when adding an item representation.
=> fix: Fix the missing prop `bodyshape` when adding an item representation

src/modules/collection/sagas.spec.ts, src/modules/collection/sagas.ts, src/modules/item/export.ts
Until the new emotes code is released, we need to keep deploying them as pre-ADR74 emotes, meaning as wearables.
=> fix: Use Emotes FF to build entity to deploy

src/components/CollectionProvider/CollectionProvider.tsx, src/components/CollectionProvider/CollectionProvider.types.ts, src/components/ItemEditorPage/CenterPanel/CenterPanel.container.ts, src/components/ItemEditorPage/CenterPanel/CenterPanel.css, src/components/ItemEditorPage/CenterPanel/CenterPanel.tsx, src/components/ItemEditorPage/CenterPanel/CenterPanel.types.ts, src/components/ItemEditorPage/LeftPanel/Items/Items.tsx, src/components/ItemEditorPage/LeftPanel/Items/Items.types.ts, src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx, src/components/ItemEditorPage/LeftPanel/LeftPanel.types.ts, src/components/Modals/AddExistingItemModal/AddExistingItemModal.container.ts, src/components/Modals/AddExistingItemModal/AddExistingItemModal.tsx, src/components/Modals/AddExistingItemModal/AddExistingItemModal.types.ts, src/modules/item/sagas.ts, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
This PR allows showing single emotes in the play emotes dropdown button.
Emotes in the Items tab:
Emotes in the Collection tab:
=> fix: Show single emotes in the emote dropdown button

src/components/CollectionProvider/CollectionProvider.tsx
This PR fixes the message error shown in the right panel on the item editor page when loading an item as a curator.
Closes #2276
=> fix: Get the right page when redirecting to a paginated item in a collection

src/components/CollectionImage/CollectionImage.tsx, src/components/ItemEditorPage/RightPanel/RightPanel.tsx, src/modules/item/utils.ts
This PR verifies if the updated items' data by the migration: https://github.com/decentraland/builder-server/pull/591, are synced and matching with the new emote ADR74 data schema in the catalyst.
=> feat: Update old emote data to the new ADR74 schema

src/components/ItemEditorPage/RightPanel/RightPanel.tsx, src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx, src/components/Modals/CreateSingleItemModal/ImportStep/ImportStep.tsx
This PR fixes the data format sent to the backend when updating a emote's file using the CreateSingleItemModal.
Closes #2280
=> Fix: Emotes data format when updating a emote's file

src/modules/ens/sagas.ts
This PR fixes the issue of the names not showing up when the user has no lands.
The issue was caused due to having an empty array of coordinates being sent to the endpoint, making the endpoint fail thus preventing the rest of the operation to succeed.
=> fix: ENS not working when there's no LAND

src/components/ItemDetailPage/ItemDetailPage.tsx, src/components/ItemEditorPage/RightPanel/RightPanel.tsx, src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx, src/components/Modals/CreateSingleItemModal/ImportStep/ImportStep.tsx, src/modules/item/utils.ts, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
This PR cleans the model content when uploading a .zip file with male/female representations and processes the file structure to save the proper representation schema in DB.
Closes #2282
=> fix: Extract the models and images content from subfolders to the root level

src/components/ItemEditorPage/CenterPanel/CenterPanel.css, src/components/ItemEditorPage/CenterPanel/CenterPanel.tsx
This PR adds the zoom controls in the Item Editor Preview.
Closes #2291
=> feat: Add zoom controls in the Item Editor Preview

src/components/ItemEditorPage/CenterPanel/CenterPanel.css, src/components/ItemEditorPage/CenterPanel/CenterPanel.tsx, src/modules/item/sagas.spec.ts, src/modules/item/sagas.ts
This PR fetches the items when creating a new item on the Item Editor page and keeps visible the emote controls when opening the avatar customization options.
Closes #2299 
Closes #2306
=> fix: Reload left panel when creating a new item

src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
The condition was wrong, because the `isEmotePlayModeFeatureFlagOn` is used to DISABLE the `EmotePlayMode.LOOP` from the dropdown. [So when the flag is ON, the feature is OFF](https://github.com/decentraland/builder/blob/master/src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx#L779). 
What I did is I removed the ternary when setting the value of the `loop` prop to always be what is in `state`, since the we already have the check of the flag to disable the dropdown.
=> fix: looped emotes

src/modules/item/sagas.ts
When inside the item editor, but without opening any collection or item, the url is `/item-editor`, and there's no `paginationData`, but there is a `+` button to create an item. If you create an item in this particular page, the success saga at the end fails because `paginationSaga` is undefined. I added a check to make sure it exists.
=> fix: create emote from editor

src/modules/collection/sagas.ts
This PR re-computes hashes for emotes so they can be deployed to the catalyst (see #2315).
=> fix: Re-compute hash for emotes

src/lib/getModelData.ts
This PR fixes the computing of emotes' frames.
Closes #2316
=> fix: Computing the emotes metrics when tracks contain different sizes

src/components/CurationPage/CurationPage.container.ts, src/components/CurationPage/CurationPage.css, src/components/CurationPage/CurationPage.tsx, src/components/CurationPage/CurationPage.types.ts, src/components/ItemEditorPage/RightPanel/RightPanel.container.ts, src/components/ItemEditorPage/RightPanel/RightPanel.css, src/components/ItemEditorPage/RightPanel/RightPanel.tsx, src/components/ItemEditorPage/RightPanel/RightPanel.types.ts, src/lib/api/builder.ts, src/modules/collection/sagas.spec.ts, src/modules/features/selectors.ts, src/modules/features/types.ts, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
This PR adds support to filter collections by item tag in the curations page and a message for upcoming events below the tags container in the Item Editor Right Panel.
- Curation page toggle filter:
- Item Editor - Right Panel message:
Closes #2343
Closes #2342
=> feat: Add support to filter collections by items tag

src/components/EventBanner/EventBanner.css, src/components/EventBanner/EventBanner.tsx
This PR updates the component banner from the advertiser component to a plane div to avoid being blocked by ad blockers. 
Banner:
=> fix: Update event banner component

src/components/ItemEditorPage/LeftPanel/Items/Items.tsx, src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx, src/modules/item/sagas.ts
This PR fixes the pre-selected emote after its creation, allowing editing it properly.
Closes #2333
=> fix: Pre-selected item after emote creation

package-lock.json, package.json, src/components/Modals/CreateSingleItemModal/EditThumbnailStep/EditThumbnailStep.tsx
This PR shows a thin box around the emote model to show thumbnail boundaries when taking a screenshot
Closes #2335
depends on: https://github.com/decentraland/ui/pull/208
=> feat: Show the screenshot thumbnail boundaries on the EditThumbnailStep modal

package-lock.json, package.json
This PR upgrades the `decentraland-ui` version to `3.54.1`, which fixes the animation progress indicator that sometimes doesn't reach the end of the timeline.
Closes #2247
=> chore: Bump decentraland-ui

src/components/Modals/PublishWizardCollectionModal/ConfirmCollectionItemsStep/ConfirmCollectionItemsStep.css, src/components/Modals/PublishWizardCollectionModal/ConfirmCollectionItemsStep/ConfirmCollectionItemsStep.tsx, src/components/Modals/PublishWizardCollectionModal/ConfirmCollectionNameStep/ConfirmCollectionNameStep.tsx, src/components/Modals/PublishWizardCollectionModal/PayPublicationFeeStep/PayPublicationFeeStep.css, src/components/Modals/PublishWizardCollectionModal/PayPublicationFeeStep/PayPublicationFeeStep.tsx, src/components/Modals/PublishWizardCollectionModal/PublishWizardCollectionModal.tsx, src/components/Modals/PublishWizardCollectionModal/ReviewContentPolicyStep/ReviewContentPolicyStep.css, src/components/Modals/PublishWizardCollectionModal/ReviewContentPolicyStep/ReviewContentPolicyStep.tsx, src/components/Modals/PublishWizardCollectionModal/ReviewContentPolicyStep/ReviewContentPolicyStep.types.ts, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
This PR moves the step's state to the main container modal and fixes some UI issues.
ConfirmCollectionItems
ReviewContentPolicy
PayPublicationFee
Closes #2396
=> feat: Publish wizard flow preserve steps state

src/modules/ens/sagas.ts
This PR catches the errors when an ens resolver address is different from the DCL Resolver to load the names correctly.
Closes #2401
=> fix: ENS items don't show

src/modules/editor/sagas.ts
This PR closes the emotesChannel to avoid unexpected behavior in the browser because the channels were not closing when unmounting the Editor Center component.
Closes #2302
=> fix: Close emotesChannel to avoid unexpected behavior in the browser

src/components/CollectionImage/CollectionImage.container.ts, src/components/CollectionImage/CollectionImage.tsx, src/components/CollectionImage/CollectionImage.types.ts, src/components/ItemEditorPage/CenterPanel/CenterPanel.tsx, src/modules/item/actions.ts, src/modules/item/reducer.ts, src/modules/item/sagas.ts
This PR fixes showing wrong reviewed TP wearables on the curation page, refactoring the getting collection thumbnails and limiting getting collection's items in the CenterPanel only for standard collections.
Closes #2418
=> fix: Fetch pending curation items

src/components/Atlas/Atlas.tsx, src/components/Atlas/Atlas.types.ts, src/components/LandDetailPage/LandDetailPage.tsx, src/components/Modals/DeployModal/DeployToLand/DeployToLand.tsx, src/components/Modals/DeployModal/DeployToLand/LandAtlas/LandAtlas.tsx, src/components/Modals/DeployModal/DeployToLand/LandAtlas/LandAtlas.types.ts, src/components/SceneDetailPage/SceneDetailPage.tsx, src/modules/land/utils.ts
This PR fixes the layering of the Atlas component so when being a tenant, the rented LAND is shown as orange.
It also fixes some missing keys that some maps were missings.
Closes #2404
=> fix: Atlas not rendering tenants

src/components/LandDetailPage/LandDetailPage.tsx, src/components/RentalPeriod/RentalPeriod.tsx, src/modules/land/utils.spec.ts, src/modules/land/utils.ts
This PR removes the dropdown menu for tenant whose rental contract has finished.
Closes #2435
=> fix: Show update operator only if the rental has not finished

public/index.html, src/components/Preview/Preview.tsx, src/lib/urn.ts, src/routing/Routes.tsx, src/routing/utils.ts
This PR avoids loading unity scripts in mobile browsers because the scenes editor is only available for the desktop experience.
Closes #2441
=> fix: mobile homepage unity compatibility

.github/workflows/build-release.yaml
This PR adds `HUSKY=0` to env vars when installing dependencies to avoid installing git hooks on CI/CD
=> chore: Avoid install git hooks on CI/CD

src/components/HomePage/HomePage.css
This PR fixes the Homepage overview title vertical alignment.
=> fix: Homepage overview title vertical alignment

src/components/Intercom/Intercom.tsx, src/components/Intercom/Intercom.types.ts
This PR fixes intercom loading when adblockers are on. The current component implementation depends on the segment `anon_id` field, but if an adblocker is on, the segment library won't load, and the intercom component will be closed.
=> fix: Load intercom when adblockers on

src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx
This PR removes ordering done in the ui for the collections items in editor so that the order of the items remains the same one as in the collection detail page.
Closes #2409
=> feat: do not reorder items in editor

src/components/LandOperatorPage/LandOperatorPage.tsx, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
This PR changes the description shown when assigning an operator to the land so that the user better understands the permissions this operator has.
Closes #2419
=> feat: change operator description to better understand the behavior

src/components/CollectionDetailPage/CollectionItem/CollectionItem.container.ts, src/components/CollectionDetailPage/CollectionItem/CollectionItem.tsx, src/components/CollectionDetailPage/CollectionItem/CollectionItem.types.ts, src/components/CollectionsPage/CollectionsPage.container.ts, src/components/CollectionsPage/CollectionsPage.tsx, src/components/CollectionsPage/CollectionsPage.types.ts, src/components/ItemEditorPage/CenterPanel/CenterPanel.container.ts, src/components/ItemEditorPage/CenterPanel/CenterPanel.tsx, src/components/ItemEditorPage/CenterPanel/CenterPanel.types.ts, src/components/ItemEditorPage/LeftPanel/Header/Header.container.ts, src/components/ItemEditorPage/LeftPanel/Header/Header.tsx, src/components/ItemEditorPage/LeftPanel/Header/Header.types.ts, src/components/ItemEditorPage/LeftPanel/LeftPanel.container.ts, src/components/ItemEditorPage/LeftPanel/LeftPanel.tsx, src/components/ItemEditorPage/LeftPanel/LeftPanel.types.ts, src/components/ItemEditorPage/RightPanel/RightPanel.tsx, src/modules/collection/utils.ts, src/modules/item/actions.ts, src/modules/item/reducer.spec.ts, src/modules/item/reducer.ts, src/modules/item/sagas.spec.ts, src/modules/item/sagas.ts, src/modules/item/selectors.spec.ts, src/modules/item/selectors.ts, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
This PR updates the single items section, avoid creating new single items and lets the users move the currents to existing collections or delete them.
* Disable ability to create new single items
* Replace "Remove from collection" action in dropdown with "Remove item"
* Add confirm to the Remove item action
* Remove Collections/Single Items tabs if the user has no single items
* ![image](https://user-images.githubusercontent.com/3170051/203168245-666e9a3a-c3f1-4a7b-803b-ba248b67bbb7.png)
* ![image](https://user-images.githubusercontent.com/3170051/203168309-89dd4b5c-b5e8-4833-a8d3-2f50695269dc.png)
Closes #2346
=> feat: Update single items management

src/config/env/prod.json, src/config/env/stg.json
This PR solves the issue of not being able to set the update operator on a rented LAND due to the UI pointing to the old rentals contract on the production environments.
Contracts site: [https://contracts.decentraland.org/addresses.json](https://contracts.decentraland.org/addresses.json)
=> fix: Set rentals contract address in production

src/components/LoggedInDetailPage/LoggedInDetailPage.tsx
This PR fixes an issue that made the error be shown when it shouldn't as it was needed to be waited for the loading state to finish before showing it.
=> fix: Only show error when not loading ENS names

package-lock.json, package.json
This PR fixes the requirement of having an identity when requesting ENS names by updating the builder client to remove the authentication from those endpoints.
=> fix: Fix authentication requirement when loading ENS names

src/modules/editor/sagas.ts
This PR fixes a race condition when creating a scene and the editor scripts haven't loaded yet, loading them twice and losing the main editor reference
=> fix: Loading scripts twice when creating a scene racing condition occurs

src/components/ItemEditorPage/LeftPanel/Header/Header.css, src/components/ItemEditorPage/LeftPanel/Header/Header.tsx
This PR adds a link to the collection name in the Item Editor, allowing the user to return to the collection's details.
=> feat: Add link to collection details in Collection name

package-lock.json, package.json, src/modules/deployment/sagas.ts, src/modules/entity/sagas.spec.ts, src/modules/entity/sagas.ts
This PR upgrades the `decentraland-dapps` version to show a new error toast when a meta-txn fails by polygon network high congestion.
Depends on https://github.com/decentraland/decentraland-transactions/pull/62
=> feat: Upgrade decentraland-dapps version

package-lock.json, package.json, src/modules/collection/sagas.ts
This PR hides the high congestion error message in the modal to prioritize the toast error information.
Depends on https://github.com/decentraland/decentraland-dapps/pull/385
=> feat: Hide high congestion error message in the publish collection modal

src/components/Modals/CreateSingleItemModal/ImportStep/ImportStep.tsx, src/components/Modals/CreateSingleItemModal/ImportStep/ImportStep.types.ts, src/modules/item/errors.ts, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
This PR fixes update the representation of a created item using a different model type.
Closes #2576
=> fix: Upload model representation of wrong item type

package-lock.json, package.json
This PR updates the `decentraland-dapps` dependency to fix the issue with the `_getInternalBlockNumber` function being called from a nulled instance.
[Link to the decentraland-dapps PR](https://github.com/decentraland/decentraland-dapps/pull/404)
=> fix: Update dcl dapps to fix the provider lacking context issue

package-lock.json, package.json
Bump decentraland dapps version to include https://github.com/decentraland/decentraland-dapps/pull/443
=> feat: bump decentraland dapps version

src/components/SceneDetailPage/SceneDetailPage.container.ts
Do not show any status before all deployments are loaded. We needed to add a new condition to the isLoadingDeployments property as before the deplyoments request is triggered the FETCH_LANDS_REQUEST is called to fetch the lands in which we want the deployments
=> fix: loading scene status

src/components/SceneDetailPage/SceneDetailPage.tsx
This PR shows a delete confirmation modal when the user tries to delete a project/scene.
=> feat: Show delete project modal confirmation

src/components/Modals/DeployModal/DeployToLand/DeployToLand.container.ts, src/components/Modals/DeployModal/DeployToLand/DeployToLand.tsx, src/components/Modals/DeployModal/DeployToLand/DeployToLand.types.ts, src/modules/deployment/reducer.ts
This PR fixes the deploy scene to land.
Currently, when you're trying to deploy a scene to land, the modal that shows the map doesn't appear, or the flow breaks because you couldn't find a valid deployment(if it exists) to display the current cords.
=> fix: Deploy Scene to Land

src/components/Preview/Preview.css, src/components/Preview/Preview.tsx, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
This PR shows a Modal when the unity editor fails to load a scene.
The `Back button` and `Close Modal Action` redirect to the scene details page, forcing a fresh load to clean unity scripts.
The `Reload button` forces the browser to reload and load unity scripts again.
=> fix: Loading Scene Editor

src/modules/translation/languages/en.json
This PR updates the `Share in Twitter` wording to `Share on Twitter`.
=> fix: Share on Twitter wording

package-lock.json, package.json, src/modules/analytics/sagas.ts
- Removed [handleConnectWallet](https://github.com/decentraland/builder/pull/2672/files#diff-8e1726c7e66e850010f330d8b66f37af63e66dd0fffadfe164fa4eee66ba158dL132) as it was duplicating the Connect Wallet event being sent.
- Removed [handleConnectWalletSuccess](https://github.com/decentraland/builder/pull/2672/files#diff-8e1726c7e66e850010f330d8b66f37af63e66dd0fffadfe164fa4eee66ba158dL193) Because it is being handled in the same way by decentraland-dapps analytics module.
- Removed [handleLocationChange](https://github.com/decentraland/builder/pull/2672/files#diff-8e1726c7e66e850010f330d8b66f37af63e66dd0fffadfe164fa4eee66ba158dL203) For the same reason.
These changes make it possible to use the Connect Wallet tracking from decentraland-dapps.
=> fix: Update analytics module usage

src/lib/api/builder.ts
This PR fixes get the `empty-ground` image.
=> fix: Get public empty-ground.png image

src/components/SceneCard/SceneCard.tsx
This PR fixes the loading of the templates' thumbnail and video from public folder
=> fix: Load templates thumbnail and video from public folder

src/components/Modals/CloneTemplateModal/CloneTemplateModal.tsx, src/lib/api/builder.ts, src/modules/editor/types.ts, src/modules/project/actions.ts, src/modules/project/utils.ts, src/modules/scene/utils.ts
This PR fetches the templates manifest from `templates/:id/manifest` endpoint.
Depends on: https://github.com/decentraland/builder-server/pull/667
=> feat: Fetch templates manifest from templates/:id/manifest endpoint

src/modules/collection/utils.ts
Hardcode the realm to prevent it from using `poseidon` that currently has Sepolia content
=> fix: Hardcode realm

src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx, src/modules/deployment/contentUtils.ts
This PR updates the `SW` data representation to contain the `scene.json`. 
Also, it fixes sending the video content to the builder-server, removed previously in [[this PR]](https://github.com/decentraland/builder/pull/2785/files#diff-6e44a8ab5281e24e1251f5bee8340d324289f9b25dfbf8f77aba93077b4c71b5R539).
=> fix: SW contents

src/components/SceneViewPage/SceneViewPage.tsx, src/modules/common/sagas.ts, src/modules/common/store.ts, src/modules/inspector/actions.ts, src/modules/inspector/sagas.ts, src/modules/inspector/utils.ts, src/modules/scene/actions.ts, src/modules/scene/reducer.ts, src/modules/scene/types.ts, src/modules/sync/sagas.ts
This PR refactor all the server handlers into generators, so we can use redux (using selector, dispatching actions, using sagas' flow control) from within them (before they were async function without connection to redux).
It also adds the ability to save scenes. There is one thing that is not implemented yet which is the upload of assets, that will require a new endpoint, for now it is implemented in memory storing the assets in a map.
=> feat: save sdk7 scenes

src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx, src/components/Modals/CreateSingleItemModal/UploadVideoStep/UploadVideoStep.tsx
It considers the previous view to navigate using the back button in the header.
When the user is viewing the item's details and wants to modify the video, if the user clicks the back button, the component will consider that the previous view was the Item Details and render that again.
=> feat: Upload video back takes the previous view into account

src/components/CollectionDetailPage/CollectionItem/CollectionItem.tsx
Expand the first column when necessary to avoid collisions between the name, the smart badge, and the Rarity badge.
=> fix: Expand collection item first column

src/components/ItemDetailPage/ItemDetailPage.css, src/components/ItemDetailPage/ItemDetailPage.tsx, src/components/ItemEditorPage/RightPanel/RightPanel.tsx, src/components/ItemEditorPage/RightPanel/RightPanel.types.ts, src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx, src/themes/theme.css
This PR updates the CreateSingleItem modal to include the `EditPrice` step in the flow for all items.
Video Showcase:
https://github.com/decentraland/builder/assets/3170051/61c60385-c2de-415b-9a39-719fa1a91dfe
Also, updates the Item details design:
=> feat: Update CreateSingleItem modal

src/modules/project/export.ts
Fix download scenes in sdk6. Version was taking MAX values (migration 11) but the scene wasn't wrapped in sdk6 object
=> fix: download scene sdk6

package-lock.json, package.json
The latest version of `catalyst-client` throws when using the util `buildEntity` with a `(0, r.hashV1) is not a function`. 
It seems that it has to do with some of the changes from version `v3.0.0` to `v.3.0.3` of `@dcl/hashing`: https://github.com/decentraland/catalyst-client/releases/tag/21.5.4
=> fix: install older version of catalyst client

src/components/InspectorPage/InspectorPage.tsx
Fixes the issue with the redirect of the `inspector-index.html` to `index.html`
=> fix: point to inspector in CDN

src/modules/identity/sagas.ts
When the handleLogin is handled directly, it was not checking the identity in the iframe, thus asking the user to sign unnecessarily.
=> fix: SSO Login

package-lock.json, package.json
The new version updates the style of the iframe so it cannot be seen anymore.
=> fix: Update sso client

package-lock.json, package.json, src/components/InspectorPage/InspectorPage.container.ts, src/components/InspectorPage/InspectorPage.tsx, src/components/InspectorPage/InspectorPage.types.ts, src/components/Modals/EditProjectModal/EditProjectModal.tsx, src/modules/inspector/actions.ts, src/modules/inspector/reducer.ts, src/modules/inspector/sagas.ts, src/modules/inspector/selectors.ts, src/modules/inspector/utils.ts, src/modules/project/sagas.ts
This PR enabled resizing the SDK7 scenes using the `EditProjectModal`, same way as the SDK6 scenes.
It also disables the `Scene` component in the inspector because resizing the scene from there would not impact in the deployed scene.
It also changes the initial selected tab to be the `AssetPacks` tab.
=> feat: enable resize scene sdk7

.env.example, .gitignore, package-lock.json, package.json, scripts/postinstall.js, src/components/InspectorPage/InspectorPage.tsx, src/modules/inspector/sagas.ts
This PR makes the builder serve the `bin/index.js` file so it does not rely anymore on the builder server. This also makes deployments to land/worlds start working.
I also added a few env vars to setup the env to develop the `@dcl/asset-packs` repo from here.
=> feat: serve bin/index.js

src/lib/api/ens.spec.ts, src/lib/api/ens.ts
Closes #2889 
This client will be required to display ENS names for the new `Worlds For ENS Owners` feature.
=> feat: Add ens api to fetch owner ENS names

src/components/WorldListPage_WorldsForEnsOwnersFeature/NameTabs/NameTabs.container.ts, src/components/WorldListPage_WorldsForEnsOwnersFeature/NameTabs/NameTabs.spec.tsx, src/components/WorldListPage_WorldsForEnsOwnersFeature/NameTabs/NameTabs.tsx, src/components/WorldListPage_WorldsForEnsOwnersFeature/NameTabs/NameTabs.types.ts, src/components/WorldListPage_WorldsForEnsOwnersFeature/NameTabs/index.ts, src/components/WorldListPage_WorldsForEnsOwnersFeature/WorldListPage.tsx, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
- Integrates it inside WorldListPage just to check it out. The page will be completely overhauled.
- The selected tab depends on the `tab` query param
- Defaults to dcl tab query param if the provided one is invalid
Closes #2910 
Based but not exact to figma given that it is not the final design.
=> feat: Add NameTabs component

src/lib/api/ens.spec.ts, src/lib/api/ens.ts, src/lib/api/worlds.spec.ts, src/lib/api/worlds.ts, src/modules/ens/sagas.spec.ts, src/modules/ens/sagas.ts
+ Changed the name of the function to fetch external names so it is similar to the rest of the app
Closes #2911
=> feat: Add function to fetch wallet world stats to the worlds api

package-lock.json, package.json, src/components/WorldListPage_WorldsForEnsOwnersFeature/WorldListPage.tsx, src/components/WorldListPage_WorldsForEnsOwnersFeature/WorldsStorage/WorldsStorage.module.css, src/components/WorldListPage_WorldsForEnsOwnersFeature/WorldsStorage/WorldsStorage.spec.tsx, src/components/WorldListPage_WorldsForEnsOwnersFeature/WorldsStorage/WorldsStorage.tsx, src/components/WorldListPage_WorldsForEnsOwnersFeature/WorldsStorage/WorldsStorage.types.ts, src/components/WorldListPage_WorldsForEnsOwnersFeature/WorldsStorage/index.ts, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
Displays how much storage left the user has for world deployments.
This is just a preview, the component can be later placed anywhere in the layout.
=> feat: Worlds Storage component

src/components/WorldListPage_WorldsForEnsOwnersFeature/WorldListPage.container.ts, src/components/WorldListPage_WorldsForEnsOwnersFeature/WorldListPage.tsx, src/components/WorldListPage_WorldsForEnsOwnersFeature/WorldListPage.types.ts, src/modules/common/sagas.ts, src/modules/worlds/actions.spec.ts, src/modules/worlds/actions.ts, src/modules/worlds/reducer.spec.ts, src/modules/worlds/reducer.ts, src/modules/worlds/sagas.spec.ts, src/modules/worlds/sagas.ts, src/modules/worlds/selectors.spec.ts, src/modules/worlds/selectors.ts
Closes #2929 
Uses real data from the endpoint:
```
GET https://worlds-content-server.decentraland.zone/wallet/0x24e5f44999c151f08609f8e27b2238c773c4d020/stats
{
"wallet": "0x24e5f44999c151f08609f8e27b2238c773c4d020",
"dclNames": [
{
"name": "nan2.dcl.eth",
"size": "780813"
},
{
"name": "niswoman.dcl.eth",
"size": "1206426"
},
{
"name": "alberto.dcl.eth",
"size": "1012688"
}
],
"ensNames": [
{
"name": "luffy.eth",
"size": "1012682"
}
],
"usedSpace": "2999927",
"maxAllowedSpace": "15728640000"
}
```
=> feat: Show real data in worlds storage component

src/components/Modals/DeployModal/DeployToWorld_WorldsForEnsOwnersFeature/DeployToWorld.tsx
=> fix: Allow publishing world when only owning ens names

src/components/Modals/WorldsYourStorageModal/WorldsYourStorageModal.tsx, src/modules/worlds/sagas.spec.ts, src/modules/worlds/sagas.ts
On clear deployment and deployment success
=> fix: Re-request wallet stats

src/modules/collection/utils.ts
This PR removes the `DISABLE_backpack_editor_v2` var. Items not deployed are supported now by the backpack v2.
=> fix: Remove DISABLE_backpack_editor_v2 explorer var

src/modules/editor/utils.ts
Change regex to remove any non ascii character from base64 wearable
=> fix: collection name with emoji

package-lock.json, package.json, src/components/Modals/CustomLayoutModal/CustomLayoutModal.container.ts, src/components/Modals/CustomLayoutModal/CustomLayoutModal.tsx, src/components/Modals/CustomLayoutModal/CustomLayoutModal.types.ts, src/lib/api/builder.ts, src/modules/common/store.ts, src/modules/features/selectors.spec.ts, src/modules/features/selectors.ts, src/modules/features/types.ts, src/modules/project/sagas.spec.ts, src/modules/project/sagas.ts, src/modules/project/selectors.ts, src/modules/project/utils.ts
This PR does the following:
- Shows templates from `@dcl/builder-templates` package instead of loading them from the Builder Server
- Adds support for SDK7 templates
- Removes the creation flow of SDK6 scenes (if a user has SDK6 scenes they can still open them on the legacy builder).
- Everything is behind feature flags (one for enabling the SDK7 templates and one to enable the create from scratch only with SDK7)
=> feat: SDK7 templates

src/components/Modals/CustomLayoutModal/CustomLayoutModal.tsx
This PR fixes an issue with feature flags. 
When both feature flags `builder-create-scene-only-sdk7` and `builder-sdk7-templates` are OFF (as it is the case in PRD) everything is fine. When both flags are ON as they were in DEV and STG then everything is fine too. 
The problem is when `builder-sdk7-templates` is ON and `builder-create-scene-only-sdk7` is OFF, then the scene creation flow allows you to choose which SDK version to use, but it will always create the scene using SDK7... this was because the `isSDK7TemplatesEnabled` property was wrongly used in the submit handler of the scene creation flow.. 
This PR fixes that issue so the two feature flags can be used separately, which is necessary to release the SDK7 templates without disabling the creation of SDK6 scenes.
=> fix: wrong feature flag

package-lock.json, package.json, src/components/ENSDetailPage/ENSDetailPage.module.css, src/components/ENSDetailPage/ENSDetailPage.spec.tsx, src/components/ENSDetailPage/ENSDetailPage.tsx, src/components/ENSListPage/ENSListPage.css, src/components/ENSListPage/ENSListPage.tsx, src/components/LandAssignENSPage/LandAssignENSForm/LandAssignENSForm.tsx, src/components/LandAssignENSPage/LandAssignENSForm/LandAssignENSForm.types.ts, src/components/LandAssignENSPage/LandAssignENSPage.container.ts, src/components/LandAssignENSPage/LandAssignENSPage.tsx, src/components/LandAssignENSPage/LandAssignENSPage.types.ts, src/components/Modals/ReclaimNameModal/ReclaimNameModal.container.ts, src/components/Modals/ReclaimNameModal/ReclaimNameModal.module.css, src/components/Modals/ReclaimNameModal/ReclaimNameModal.spec.tsx, src/components/Modals/ReclaimNameModal/ReclaimNameModal.tsx, src/components/Modals/ReclaimNameModal/ReclaimNameModal.types.ts, src/components/Modals/ReclaimNameModal/index.ts, src/components/Modals/index.ts, src/components/SignInPage/SignInPage.tsx, src/modules/ens/sagas.ts, src/modules/ens/selectors.ts, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
=> feat: add reclaim name flow

package-lock.json, package.json, scripts/postinstall.cjs, src/ecsScene/scene.ts, src/modules/project/export.ts
This PR fixes the export scenes and publishes legacy scenes.
Depends on: https://github.com/decentraland/js-sdk-toolchain/pull/886
=> fix: Export Scenes

src/components/InspectorPage/TopBar/TopBar.tsx
So users don't have to see the greeting page each time they want to preview.
=> fix: Skip setup explorer url

src/components/AssetPackEditor/AssetPackEditor.tsx, src/modules/analytics/track.ts
The following events were sending the whole action with big payloads.
asset_pack_editor_edit_asset
delete_item
delete_item_error
open_modal
save_item
save_item_error
set_price_and_beneficiary
These are also sending big payloads but I cannot find them :S
deploy_item_contents
deploy_item_contents_error
=> fix: Remove huge payloads from tracked events

package-lock.json, package.json
This PR upgrades the package `@dcl/sdk` to the version to `7.4.5`
=> chore: Update @dcl/sdk version to 7.4.5

.github/workflows/audit.yml, package-lock.json, package.json, src/components/DeployButton/DeployButton.container.ts, src/components/EditorPage/Metrics/Metrics.container.ts, src/components/InspectorPage/InspectorPage.tsx, src/components/InspectorPage/TopBar/TopBar.container.ts, src/components/InspectorPage/TopBar/TopBar.tsx, src/components/InspectorPage/TopBar/TopBar.types.ts, src/components/Modals/DeployModal/DeployToWorld/DeployToWorld.tsx, src/components/Modals/DeployModal/DeployToWorld/DeployToWorld.types.ts, src/components/SDK6TopBar/SDK6TopBar.container.ts, src/modules/deployment/utils.ts, src/modules/inspector/utils.ts, src/modules/scene/actions.ts, src/modules/scene/constants.ts, src/modules/scene/reducer.ts, src/modules/scene/selectors.ts, src/modules/scene/types.ts, src/modules/sync/sagas.ts
This PR fixes the layout base generation because there was a mismatch between how the layout is shown in the preview and how it is stored to be deployed.
`2 rows` x `1 col` is interpreted in the preview as `1 row` x `2 cols`.
It also adds the validations to avoid publishing a scene when the scene has entities outside the layout or the metrics exceed the limits.
Depends on: https://github.com/decentraland/js-sdk-toolchain/pull/906
=> fix: Inspector layout

src/components/InspectorPage/TopBar/TopBar.tsx
This PR removes the validation to publish scenes when the limits are exceeded
=> fix: Only show the warning when scene limits are exceeded

src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
This PR fixes the `rarity_descriptions` for the exotic rarity which was missing.
=> fix: Rarity descriptions

.github/workflows/audit.yml, .github/workflows/build-release.yaml, .github/workflows/test.yaml, package-lock.json, package.json, src/modules/location/sagas.spec.ts
This PR updates the build process to use node 20.
=> fix: Use node 20

src/components/Modals/DeployModal/DeployToWorld/DeployToWorld.tsx, src/components/SceneDetailPage/DeploymentDetail/DeploymentDetail.tsx, src/components/WorldListPage/WorldListPage.tsx
The `decentraland.org/play/world/<ens>` url is not working (I dunno since when, if this was intended or not) so in order to get this fixed in prod I'm swiching to the `play?realm=<ens>` url that works fine.
=> fix: world urls

src/components/Modals/DeployModal/DeployToWorld/DeployToWorld.tsx, src/components/SceneDetailPage/DeploymentDetail/DeploymentDetail.tsx, src/components/WorldListPage/WorldListPage.tsx
This PR reverts commit 89d921d2c897820a7f60ecd9f4ce50d288c5b5b4 because the redirect is now fixed
=> Revert "fix: world urls"

src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
This PR fixes the permanent loading state when creating a smart wearable and uploading a video preview
=> fix: Create SW loading state does not change after selecting the video preview

src/modules/item/export.ts
Right now, when editing a representation, for the final size calculation, it will add the previous model + the new one, so if the old one has 1.5MB and the new one 1.6M, it will be clearly exceeding the max allowed (currently set at 2MB)
=> fix: avoid counting models twice for the final size

package-lock.json, package.json
Upgrade `@dcl/sdk` to [v7.4.18](https://github.com/decentraland/js-sdk-toolchain/releases/tag/7.4.18)
* fix: prevent race condition between loading Nodes component and GLTFs by @cazala in https://github.com/decentraland/js-sdk-toolchain/pull/933
**Full Changelog**: https://github.com/decentraland/js-sdk-toolchain/compare/7.4.17...7.4.18
=> feat: upgrade @dcl/sdk to v7.4.18

src/modules/item/export.ts
For the SW items, don't take into account the video size since it will reach the limit (2MB) easily.
=> fix: do not take into account videos for SW limit size

package-lock.json, package.json
This PR upgrades the package `@dcl/sdk` to the version `7.4.21`
=> chore: Upgrade the @dcl/sdk package to the version 7.4.21

src/components/ItemDetailPage/ItemDetailPage.css
This PR adds the `word-break` CSS property to the description and utility attributes.
=> fix: Item description and utility not breaking

src/components/Modals/CustomLayoutModal/CustomLayoutModal.container.ts, src/components/Modals/CustomLayoutModal/CustomLayoutModal.types.ts, src/lib/api/builder.ts, src/modules/features/selectors.spec.ts, src/modules/features/selectors.ts, src/modules/inspector/sagas.ts, src/modules/project/sagas.spec.ts, src/modules/project/sagas.ts
This PR fixes an issue where opening the Local Assets on a scene created from a template would crash the Web Editor.
The problem was that the `main.composite` file was being returned twice by the file system interface, and that resulted in the directory tree breaking.
I also took the chance to remove an usused feature flag on this PR: `sdk7-templates`
=> fix: builder templates local assets tab

package-lock.json, package.json, src/components/ItemDetailPage/ItemDetailPage.css
This PR fixes the sizing issues with the utility and the description, which now, occupy the 50% of the container by default.
=> fix: Utility and description sizing

src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.tsx
This PR changes the logic to keep the overrides after modifying the item representations.
=> feat: Keep overrides after changing a representation

src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
This PR removes the smart items'(already implemented) upcoming text for the sdk7.
Closes: https://github.com/decentraland/dapps-issues/issues/131
=> fix: Update smart items upcoming text

src/components/ItemEditorPage/RightPanel/RightPanel.tsx
When editing a collection it doesn't matter what is changed its causing the collection to be uunsync, this is because the new field `blockVrmExport` is added to the data all the time causing the hash to change. This PR is to add that field only if the data already has it or it has been changed, so when changing only utility in old collections for example it won't trigger the curation process
=> fix: unsync collections when changing utility

src/components/ENSDetailPage/ENSDetailPage.container.ts, src/components/ENSDetailPage/ENSDetailPage.spec.tsx, src/components/ENSDetailPage/ENSDetailPage.tsx, src/components/ENSDetailPage/ENSDetailPage.types.ts, src/modules/ens/selectors.ts
When fetching for names, if the name had any uppercase letter it wasn't able to find the correct ens in the state as it was being saved in lowercase. This PRs adds a fix that compares the subdomains in lowercase when searching for a specific name in the store
=> fix: ens indefinitely loading

src/components/Modals/DeployModal/DeployToWorld/DeployToWorld.tsx
When the user only has contributable names do not show the "Empty view" as if there is no available world where the scene can be deployed
=> fix empty deploy contributable names

package-lock.json, package.json
This PR updates the package `@dcl/sdk` to version `7.5.5`.
=> chore: Update @dcl/sdk package to version 7.5.5

src/modules/inspector/sagas.ts
This PR fixes an inspector error when building the scene asset tree and the `thumbnail.png` file is already present.
error:
=> fix: Avoid push thumbnails if they already exist in the path

src/components/Modals/CreateSingleItemModal/CreateSingleItemModal.container.ts
This PR fixes the way we're setting the collection id for the items in the `CreateSingleItemModal` component.
=> fix: Collection id in create single item modal

src/components/MappingEditor/MappingEditor.module.css, src/components/MappingEditor/MappingEditor.tsx
This PR changes the way we're processing the multiple token ids form so the commas can be easily deleted.
=> fix: Not able to remove commas in Multiple mappings

src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.tsx
This PR fixes an issue where the Third Parties slots number will never stop loading.
=> fix: Third Party slots loading

src/modules/item/sagas.spec.ts, src/modules/item/sagas.ts
This PR changes the way we're saving the upserted item to use the old behavior if the `isLinkedWearablesV2Enabled` FF is active.
=> fix: Only use upserted item if FF is enabled

src/components/CollectionDetailPage/CollectionDetailPage.container.ts, src/components/CollectionDetailPage/CollectionDetailPage.tsx, src/components/CollectionDetailPage/CollectionDetailPage.types.ts, src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.container.ts, src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.tsx, src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.types.ts, src/modules/ui/location/action.ts, src/modules/ui/location/reducer.spec.ts, src/modules/ui/location/reducer.ts, src/modules/ui/location/selector.spec.ts, src/modules/ui/location/selector.ts, src/modules/ui/reducer.ts, src/routing/AppRoutes/AppRoutes.container.ts, src/routing/AppRoutes/AppRoutes.tsx, src/routing/AppRoutes/AppRoutes.types.ts, src/routing/AppRoutes/index.ts
This PR fixes the Collection Details Page not going back correctly as the button was always set to go to the `/collections` route but it wasn't taking into consideration the complete location where it came from (type of collections, sorting, page, etc).
To fix this, we need to know the last path the user was on. The last path is now stored in the redux state and consumed in each of the pages that need it.
=> fix: Collection Details Page not going back correctly

src/components/Modals/CreateThirdPartyCollectionModal/CreateThirdPartyCollectionModal.tsx
This PR fixes the network dropdown, showing the available networks uniquely.
=> fix: Show unique networks when creating a linked collection

src/components/Modals/CreateThirdPartyCollectionModal/CreateThirdPartyCollectionModal.tsx, src/components/NetworkIcon/NetworkIcon.tsx, src/components/NetworkIcon/NetworkIcon.types.ts, src/components/NetworkIcon/index.ts, src/components/NetworkIcon/utils.ts, src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.tsx, src/components/ThirdPartyImage/ThirdPartyImage.module.css, src/components/ThirdPartyImage/ThirdPartyImage.spec.tsx, src/components/ThirdPartyImage/ThirdPartyImage.tsx
This PR adds the network item in the Third Party Image component:
=> feat: Show network in third party image

src/components/MappingEditor/MappingEditor.module.css
This PR changes the mapping type default icon styling so it does not appear when clicking on the field.
Before:
After:
=> fix: Mapping type default value icon

src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.tsx
The `thirdParty` is missing from the update variables.
=> fix: Third Party Detail Page not updating when third party is loaded

src/components/Modals/CreateAndEditMultipleItemsModal/CreateAndEditMultipleItemsModal.container.ts, src/components/Modals/CreateAndEditMultipleItemsModal/CreateAndEditMultipleItemsModal.tsx, src/components/Modals/CreateAndEditMultipleItemsModal/CreateAndEditMultipleItemsModal.types.ts
This PR processes the mappings in the `wearable.json` file only if the FF is enabled.
=> fix: Multiple items creation with mappings only on LW v2

src/components/CollectionsPage/CollectionsPage.tsx
Third PR fixes and issue where all users were shown the TP tab in the collections page even if they weren't third party managers.
=> fix: Only show the LW tab if TP manager or payments is enabled

src/lib/array.ts, src/modules/curations/itemCuration/sagas.ts, src/modules/ens/utils.ts
When the use has more than 150 parcels, the `getLandRedirectionHashes` client call fails because the server can only answer 150 coordinates at a time. This PR fixes that by batching the requests.
=> fix: Requesting coordines for more than 150 hashes

src/components/Modals/CreateCollectionSelectorModal/CreateCollectionSelectorModal.container.ts, src/components/Modals/CreateCollectionSelectorModal/CreateCollectionSelectorModal.module.css, src/components/Modals/CreateCollectionSelectorModal/CreateCollectionSelectorModal.spec.tsx, src/components/Modals/CreateCollectionSelectorModal/CreateCollectionSelectorModal.tsx, src/components/Modals/CreateCollectionSelectorModal/CreateCollectionSelectorModal.types.ts, src/components/Modals/CreateCollectionSelectorModal/constants.ts, src/components/Modals/CreateThirdPartyCollectionModal/CreateThirdPartyCollectionModal.tsx, src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.container.ts, src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.module.css, src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.tsx, src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.types.ts, src/lib/api/builder.ts, src/modules/thirdParty/actions.ts, src/modules/thirdParty/reducer.spec.ts, src/modules/thirdParty/reducer.ts, src/modules/thirdParty/sagas.spec.ts, src/modules/thirdParty/sagas.ts, src/modules/thirdParty/selectors.spec.ts, src/modules/thirdParty/selectors.ts
This PR changes the disabled restriction on the `CreateCollectionSelectorModal` to allow anyone to create a new LW collection. The modal will be shown only if the flag is set. This check is done in the `CollectionsPage` component.
=> fix: Allow anyone to create a LW collection

package-lock.json, package.json, src/components/CollectionsPage/CollectionsPage.tsx, src/components/MappingEditor/MappingEditor.module.css, src/components/Modals/PublishWizardCollectionModal/ConfirmCollectionItemsStep/ConfirmCollectionItemsStep.module.css, src/components/Modals/PublishWizardCollectionModal/ConfirmCollectionItemsStep/ConfirmCollectionItemsStep.tsx, src/components/Modals/PublishWizardCollectionModal/PayPublicationFeeStep/PayPublicationFeeStep.tsx, src/components/Modals/PublishWizardCollectionModal/PublishWizardCollectionModal.container.tsx, src/components/Modals/PublishWizardCollectionModal/PublishWizardCollectionModal.tsx, src/components/Modals/PublishWizardCollectionModal/PublishWizardCollectionModal.types.ts, src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.tsx, src/lib/api/builder.ts, src/modules/collection/selectors.ts, src/modules/curations/itemCuration/reducer.spec.ts, src/modules/curations/itemCuration/reducer.ts, src/modules/item/reducer.spec.ts, src/modules/item/reducer.ts, src/modules/thirdParty/actions.ts, src/modules/thirdParty/reducer.spec.ts, src/modules/thirdParty/reducer.ts, src/modules/thirdParty/sagas.spec.ts, src/modules/thirdParty/sagas.ts, src/modules/thirdParty/selectors.spec.ts, src/modules/thirdParty/selectors.ts, src/specs/item.ts
This PR improves the LW publishing flow by:
- Showing the user the item's mapping when confirming the items to be published.
- Changing the payment sagas to have separated phases, that is, waiting for the transaction to be accepted, processing the transaction and publishing items and changes. This implies a more ordered flow for the users.
And fixes:
- The publishing flow crashing due to lack of retries on the publishing API calls.
- The missing third party publishing status function when wrapping the publishing modal with the withAuthorization wrapper.
- The auto-sizing of the MappingEditor component, which was missing the `min-width` property.
- The edit name icon in the ThirdPartyCollectionDetail page being pushed to the right so much it wasn't visible.
- Removes the capability to …
=> feat: LW improvements and fixes

src/modules/location/selectors.ts
The Third Parties forum post is done by using the query parameter `collectionId` instead of `collection`, which is the one used for standard collections. This PR is a fix that allows older forum posts to keep linking to the collection.
=> fix: Retrieving TP by id

src/components/ActivityPage/Transaction/TransactionDetail/TransactionDetail.tsx, src/components/CollectionImage/CollectionImage.tsx, src/components/CollectionImage/constants.ts, src/components/CollectionImage/index.ts, src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.module.css, src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.tsx, src/components/ThirdPartyImage/ThirdPartyImage.container.ts, src/components/ThirdPartyImage/ThirdPartyImage.module.css, src/components/ThirdPartyImage/ThirdPartyImage.spec.tsx, src/components/ThirdPartyImage/ThirdPartyImage.tsx, src/components/ThirdPartyImage/ThirdPartyImage.types.ts, src/components/ThirdPartyImage/index.ts, src/lib/api/builder.ts, src/modules/common/store.ts, src/modules/deployment/sagas.spec.ts, src/modules/poolGroup/sagas.ts, src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json, src/specs/utils.tsx
This PR does two things:
- Improves the LW Header with a new `ThirdPartyImage` that uses the `CollectionImage` and the collection type.
- Changes some tests and mocks in order to avoid loading the sagas or the store when running tests.
=> feat: LW Header Improvements

src/modules/thirdParty/sagas.spec.ts, src/modules/thirdParty/sagas.ts
This PR removes the errors in the `PublishWizardCollectionModal` when closed.
=> feat: Clear LW errors on modal close

package-lock.json, package.json, src/components/MappingEditor/MappingEditor.module.css, src/components/MappingEditor/MappingEditor.tsx, src/components/MappingEditor/MappingEditor.types.ts, src/components/Modals/CreateAndEditMultipleItemsModal/CreateAndEditMultipleItemsModal.module.css, src/components/Modals/PublishWizardCollectionModal/ConfirmCollectionItemsStep/ConfirmCollectionItemsStep.module.css, src/components/Modals/PublishWizardCollectionModal/ConfirmCollectionItemsStep/ConfirmCollectionItemsStep.tsx
This PR solves a couple of reported issues:
- Removes the max length label for read only fields and removes their message, making the fields slimmer.
- Updates the UI package so the select and input field are more aligned.
- Resizes the images in the step to select between programmatic and standard collections (it was not as high as it was needed).
- Groups both the gender and the category badges in the confirm items step so they're now together and aligned.
=> fix: LW element aligment issues

src/components/ENSListPage/ENSListPage.css, src/components/Icon/sprite.css
=> feat: move pin icon to fit in space

src/modules/translation/languages/en.json, src/modules/translation/languages/es.json, src/modules/translation/languages/zh.json
This PR removes the date from the banner.
=> fix: Metaverse banner text

src/components/Modals/PublishWizardCollectionModal/PublishWizardCollectionModal.tsx
When on Polygon, the Magic user must pay for the transaction gas, including the authorization. This PR changes the authorization process so the Authorization modal gets shown when the user is on the Polygon Network.
=> feat: Show authorization modal for Magic users when publishing on Polygon

src/modules/collection/utils.ts
This PR adds the new `self-preview-builder-collections` and `dclenv` parameters to make it possible for collections to be tested in the E@.
=> feat: Add E@ collection preview parameters

src/components/Modals/DeployModal/DeployToWorld/DeployToWorld.tsx
This PR fixes the subdomain property that is used when deploying DCL names by adding the `dcl.eth` at the end of the domain.
=> fix: Deploy to world without complete name

package-lock.json, package.json, src/config/env/dev.json, src/config/env/prod.json, src/config/env/stg.json, src/modules/common/sagas.ts
This PR updates the `decentraland-dapps` dependency to fix the Banners that come from the CMS endpoint.
=> fix: Update decentraland-dapps to fix CMS banners

package-lock.json, package.json, src/components/Navbar/Navbar.container.ts, src/components/Navbar/Navbar.tsx, src/components/Navbar/Navbar.types.ts, src/modules/features/selectors.ts, src/modules/features/types.ts
This PR introduces a new feature flag (`launcherLinks`) that enables fetching dynamic launcher download links. These links will be used in the Navbar's "Download" button, allowing the client to update download targets without requiring code changes.
Depends on: https://github.com/decentraland/decentraland-dapps/pull/709
=> feat: Add feature flag to fetch dynamic launcher links for Navbar's Download button
